### ISSUE TITLE
Autotools fails on macOS in Travis build

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#101]
Originally commented by @tlepoint 

> Why do we have a fail on macOS not caught by Travis?
> 
> ```
> ./test_kex
> dyld: Library not loaded: /usr/local/lib/libntruencrypt.0.dylib
>   Referenced from: /Users/travis/build/open-quantum-safe/liboqs/./test_kex
>   Reason: image not found
> make: *** [test] Trace/BPT trap: 5
> ```

**Comment by dstebila** [comment]
@smashra Can you take a look?

**Comment by tlepoint** [comment]
More generally, I think that from my tests when I set up travis, doing
```
- CC=$CC_OQS ./.travis-tests.sh
```
did not allow to catch all the errors. @smashra, could you please ensure that it fails correctly if any of the tests fail?

Thanks.

**Comment by smashra** [comment]
Fixed after building static ntru library.

**Comment by dstebila** [comment]
This is breaking the build due to two issues, namely global name spacing and pretty print. With respect to namespacing, it looks like they're all prefixed with ntru, which seems clear enough, so perhaps we should edit the Travis check script to allow ntru_ as a prefix.
