### ISSUE TITLE
Correct claimed NIST level for Kyber768_90s

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1012]
As per https://github.com/open-quantum-safe/oqs-provider/issues/23 , [Kyber768_90s](https://github.com/open-quantum-safe/liboqs/blob/f8e339dcae8432b41e60621d25a4a3596bd14a14/src/kem/kyber/kem_kyber_768_90s.c#L18) has inherited the wrong NIST level, breaking #1011

**Comment by bhess** [comment]
Can be addressed with a new copy_from_upstream after https://github.com/pq-crystals/kyber/pull/40 is merged.
