### ISSUE TITLE
OQS-OpenSSH v8 fails to build on macOS due to explicit_bzero

### ISSUE THREAD

**Issue by xvzcf** [open-quantum-safe/liboqs#1022]
On macOS, building [our fork of OpenSSH v8](https://github.com/open-quantum-safe/openssh) against the latest liboqs commit fails with the following error:

```
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ssh-agent] Error 1
duplicate symbol '_explicit_bzero' in:
    openbsd-compat//libopenbsd-compat.a(explicit_bzero.o)
    /Users/wxyz/Projects/openssh/src/oqs/lib/liboqs.a(compat.c.o)
```

The fix should include removing `explicit_bzero` [here](https://github.com/open-quantum-safe/liboqs/blob/main/tests/test_namespace.py#L35).

**Comment by jschanck** [comment]
Ideally Picnic would use our `OQS_MEM_cleanse` instead of `explicit_bzero`. We also have `OQS_MEM_aligned_alloc` and `OQS_MEM_aligned_free`. So we have everything in picnic's compat.h except timingsafe_bcmp. I suggest we remove Picnic's compatibility layer and improve ours.

**Comment by xvzcf** [comment]
Agreed.

**Comment by baentsch** [comment]
> So we have everything in picnic's compat.h except timingsafe_bcmp. 

Now I remember: `timingsafe_bcmp` was the symbol that made building oqs-openssh on alpine impossible (also `duplicate symbol` error during linking). After switching to debian, problem was gone. I didn't quite understand why, though, as the symbol was still there in both object files...
