### ISSUE TITLE
Remove old versions of BIKE

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#1024]
As discussed with @dkostic in https://github.com/open-quantum-safe/liboqs/pull/1013.

**Comment by baentsch** [comment]
Please also see https://github.com/open-quantum-safe/liboqs/pull/1037#issuecomment-869091204: Does removing old BIKE versions indeed mean BIKE's not supported on 32bitters any more? Or was BIKE never meant to run on such chips?
