### ISSUE TITLE
Add NTRU HPS-4096-1229

### ISSUE THREAD

**Issue by mouse07410** [open-quantum-safe/liboqs#1031]
NTRU team submitted Security Category 5 parameter set `NTRU-HPS-4096-1229` (available source is at https://github.com/jschanck/ntru).

Could you please add it to the library?

**Comment by baentsch** [comment]
Isn't this issue basically the same as #1026, @jschanck ?

**Comment by mouse07410** [comment]
It would've been the same if PQClean had the updated NTRU code. See https://github.com/PQClean/PQClean/issues/399 ;-)

**Comment by thomwiggers** [comment]
> Isn't this issue basically the same as #1026, @~jschanck ?

NTRU Prime is a different NIST submission.

**Comment by baentsch** [comment]
Ouch. Right.

**Comment by baentsch** [comment]
Not quite added to liboqs. Will work on this now that https://github.com/PQClean/PQClean/pull/427 has landed.
