### ISSUE TITLE
Remove OQS_KEM_DEFAULT and OQS_SIG_DEFAULT

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#1043]
The original motivation for these (allowing easy swapping of which algorithm is used in the OQS-OpenSSL integration) is no longer needed since we have all algorithms now available in OQS-OpenSSL.

Some people use this to create a minimal build with just one algorithm (combined with the MINIMAL\_BUILD flag).  While it's possible to do that with the existing CMake flags, it woudl require manually setting many of them to off.  So we should create a better set of flags for this.

**Comment by baentsch** [comment]
> So we should create a better set of flags for this.

Please check #1044 for a proposal for this (basically, passing a semicolon-delimited list of algorithms to _enable_ -- all others will automatically be disabled).

**Comment by baentsch** [comment]
Closed with #1044
