### ISSUE TITLE
inline keyword in SIKE

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#1056]
SIKE uses `__inline` to mark some inline code, but this appears to be an MSVC-specific keyword.  The more portable way seems to be either `inline` or `__inline__`, although there are some subtle differences between these two that I'm not entirely sure of.  @christianpaquin do you know if `__inline` was chosen for a specific reason?

**Comment by christianpaquin** [comment]
No, I don't know. I'll have to check if this is part of the upstream (@patricklonga, do you know?), or added in the OQS integration.

**Comment by christianpaquin** [comment]
So the `__inline` are from the upstream project; I'll defer to @patricklonga.

**Comment by christianpaquin** [comment]
FYI, I'll take a look at this when I'm back at the keyboard, starting next week.
