### ISSUE TITLE
undefined references to `OQS_KEM_frodokem_640_shake_keypair`

### ISSUE THREAD

**Issue by mnemocron** [open-quantum-safe/liboqs#1059]
I am compiling the liboqs using the waf/wscript building system for the `ave32-gcc` compiler.
Now I encounter the following errors during linking:

```
[218/220] Linking build/nanomind.elf
lib/liboqs/src/kem/frodokem/kem_frodokem640shake.c.2.o: In function `OQS_KEM_frodokem_640_shake_new':
/home/simon/workspace/OBC-devboard-1.2.1/build/../lib/liboqs/src/kem/frodokem/kem_frodokem640shake.c:9: undefined reference to `OQS_KEM_frodokem_640_shake_keypair'
/home/simon/workspace/OBC-devboard-1.2.1/build/../lib/liboqs/src/kem/frodokem/kem_frodokem640shake.c:9: undefined reference to `OQS_KEM_frodokem_640_shake_encaps'
/home/simon/workspace/OBC-devboard-1.2.1/build/../lib/liboqs/src/kem/frodokem/kem_frodokem640shake.c:9: undefined reference to `OQS_KEM_frodokem_640_shake_decaps'
```

I tried to search for the source file of the definition but I cannot find the implementation of these 3 funcitons.
A [search in the github repo](https://github.com/open-quantum-safe/liboqs/search?q=OQS_KEM_frodokem_976_aes_encaps) also only shows the 3 results.

```bash
> pwd
/home/simon/workspace/liboqs
> grep -rn . -e 'OQS_KEM_frodokem_976_aes_encaps'
./src/kem/frodokem/external/frodo976aes_params.h:29:#define crypto_kem_enc                OQS_KEM_frodokem_976_aes_encaps
./src/kem/frodokem/kem_frodokem.h:37:OQS_API OQS_STATUS OQS_KEM_frodokem_976_aes_encaps(uint8_t *ciphertext, uint8_t *shared_secret, const uint8_t *public_key);
./src/kem/frodokem/kem_frodokem976aes.c:27:	kem->encaps = OQS_KEM_frodokem_976_aes_encaps;
Binary file ./build/lib/liboqs.a matches
./build/include/oqs/kem_frodokem.h:37:OQS_API OQS_STATUS OQS_KEM_frodokem_976_aes_encaps(uint8_t *ciphertext, uint8_t *shared_secret, const uint8_t *public_key);
Binary file ./build/src/kem/frodokem/CMakeFiles/frodokem.dir/kem_frodokem976aes.c.o matches
Binary file ./build/src/kem/frodokem/CMakeFiles/frodokem.dir/external/frodo976aes.c.o matches
Binary file ./build/tests/test_kem_mem matches
Binary file ./build/tests/kat_kem matches
Binary file ./build/tests/test_kem matches
Binary file ./build/tests/speed_kem matches
Binary file ./build/tests/example_kem matches
```

Where are those functions implemented?
The binary files in the build directory are of no use to me since I use a different compiler.

**Comment by baentsch** [comment]
You may want to check FrodoKEMs [external](https://github.com/open-quantum-safe/liboqs/tree/main/src/kem/frodokem/external) folder and how it gets built in your environment.

**Comment by mnemocron** [comment]
Isn't this a definition for the default `crypto_kem_enc` pointing to a specific version of the function:
```
./src/kem/frodokem/external/frodo976aes_params.h:29:#define crypto_kem_enc                OQS_KEM_frodokem_976_aes_encaps
```

And this a **declaration** of the function
```
./src/kem/frodokem/kem_frodokem.h:37:OQS_API OQS_STATUS OQS_KEM_frodokem_976_aes_encaps(uint8_t *ciphertext, uint8_t *shared_secret, const uint8_t *public_key);
```

And this the assignment of a struct pointing to that function:
```
./src/kem/frodokem/kem_frodokem976aes.c:27:	kem->encaps = OQS_KEM_frodokem_976_aes_encaps;
```

But nowhere is the implementation of the function in a c-source file ?
Or do you mean the kem source code must be included separately from a different repo?

**Comment by baentsch** [comment]
> But nowhere is the implementation of the function in a c-source file ?

Hmm, doesn't kem/frodokem/external/kem.c contain the code? `crypto_kem_enc` (et.al.) containing the generic code that's "instantiated" for each variant via the "..._params.h" defines... Maybe reviewing the CMakeLists.txt and "#include" directives manually may be a way to see how things are put together (for x86_64 and arm using gcc&clang).

**Comment by dstebila** [comment]
`src/kem/frodokem/external/kem.c` is compiled multiple times with different headers (e.g., `src/kem/frodokem/external/frodo976aes_params.h`) yielding implementations of the different FrodoKEM variants.

**Comment by mnemocron** [comment]
I see, this lib is not meant to be built by any other autobuilder. I will try to add the avr-gcc compiler to the current CMakeFiles.

**Comment by mnemocron** [comment]
I forked the project and will continue the integration of the `avr32-gcc` compiler (and perhaps also the `arm-none-eabi-gcc`) on separate branches. Are you at all interested in having this library ported to microcontroller platforms and possibly support it on the upstream branch?

**Comment by baentsch** [comment]
It is our goal to have support for the widest possible range of platforms, Yes. That said, our team may not have the required bandwidth and/or capabilities to support platforms we're not familiar with. However, if you'd volunteer to maintain embedded platform support directly within our project, I see no reason why we should not welcome that. Please be aware, though, that we very much rely on CI; thus, any contribution that you may provide should have a CI component ensuring the (new) platforms "keep ticking" (or we are automatically made aware what/if sth fails in the future).

**Comment by mnemocron** [comment]
For the rest of 2021 i am funded by a research project where I need liboqs on avr32. I will certainly look into CMake and CI. I am open to maintaining what I added but time will tell what I can achieve.

**Comment by mnemocron** [comment]
How important is the C11 requirement?
Unfortunately the latest `avr32-gcc` (3.4.2) only supports up to C99.
If delete the `set(CMAKE_C_STANDARD_REQUIRED ON)`, the build process obviously fails with:

```
cc1: error: unrecognized command line option "-Wpedantic"
```

**Comment by baentsch** [comment]
> How important is the C11 requirement?

I'd say "rather relevant for reasonably portable code". But then again, if you have a(n old) compiler for an old architecture, what speaks against conditionally (upon compiler/architecture) setting `cmake` property C_STANDARD suitably (`99` for avr32, `11` for everything else) or --less desirable-- switching off `CMAKE_C_STANDARD_REQUIRED` *only* for avr32?

**Comment by mnemocron** [comment]
Yes, for now I am digging through the error messages while having `CMAKE_C_STANDARD_REQUIRED=OFF`. Turns out, there are many more problems.

First there is the unsupported `#pragma`s
```
../src/kem/bike/additional_r3/types.h:25: error: #pragma pack(push[, id], <n>) is not supported on this target
../src/kem/bike/additional_r3/types.h:120: error: #pragma pack(pop[, id], <n>) is not supported on this target
```
which means, I would also have to wire more preprocessor directives into all these source files and not just the CMake scripts.

And then the endless errors which really should not happen
(meaning, something is really wrong with perhaps the included files..)
```bash
simon@vbvox ~/w/l/build (avr32-build)> ninja
[1/1066] Building C object src/kem/sike/CMakeFiles/sike.dir/external/P751/P751.c.obj
FAILED: src/kem/sike/CMakeFiles/sike.dir/external/P751/P751.c.obj 
/usr/local/avr32/bin/avr32-gcc -DCOMPILER_GCC -D_AVR32_ -D_GENERIC_ -Iinclude -fPIC -fvisibility=hidden   -Werror -Wall -Wextra -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -Wno-unused-function -Wno-error -std=gnu99 -MD -MT src/kem/sike/CMakeFiles/sike.dir/external/P751/P751.c.obj -MF src/kem/sike/CMakeFiles/sike.dir/external/P751/P751.c.obj.d -o src/kem/sike/CMakeFiles/sike.dir/external/P751/P751.c.obj   -c ../src/kem/sike/external/P751/P751.c
In file included from ../src/kem/sike/external/P751/P751.c:10:
../src/kem/sike/external/P751/P751_internal.h:98: error: 'NWORDS_FIELD' undeclared here (not in a function)
../src/kem/sike/external/P751/P751_internal.h:100: warning: type defaults to 'int' in declaration of 'f2elm_t'
In file included from ../src/kem/sike/external/P751/P751.c:164:
../src/kem/sike/external/P751/generic/fp_generic.c: In function 'rdc_mont':
../src/kem/sike/external/P751/generic/fp_generic.c:193: error: 'p751_ZERO_WORDS' undeclared (first use in this function)
../src/kem/sike/external/P751/generic/fp_generic.c:193: note: each undeclared identifier is reported only once for each function it appears in
In file included from ../src/kem/sike/external/P751/P751.c:167:
../src/kem/sike/external/P751/../fpx.c: In function 'fp2_encode':
../src/kem/sike/external/P751/../fpx.c:76: warning: passing argument 1 of 'encode_to_bytes' makes pointer from integer without a cast
../src/kem/sike/external/P751/../fpx.c:41: note: expected 'const digit_t *' but argument is of type 'int'
../src/kem/sike/external/P751/../fpx.c:77: warning: passing argument 1 of 'encode_to_bytes' makes pointer from integer without a cast
../src/kem/sike/external/P751/../fpx.c:41: note: expected 'const digit_t *' but argument is of type 'int'
../src/kem/sike/external/P751/../fpx.c: In function 'fp2_decode':
```

**Comment by dstebila** [comment]
I don't have a good sense of how far the present code is from being C99 compliant. I know that some code in liboqs does use alignment-related features (e.g., `aligned_alloc`) which I believe is new to C11, which would make it problematic to revert everything to C99.

**Comment by mnemocron** [comment]
> 
> I know that some code in liboqs does use alignment-related features (e.g., `aligned_alloc`) 

Yes, I already had trouble with the alignment features.
Simply replacing it with `malloc` did the trick of compiling without errors. However, I have not debugged this on actual hardware yet. I fear that I require deep knowledge of the algorithms usage of the target instruction set in order to decide if I can just replace it with `malloc`. 

Anyhow, I was just able to compile a minimal static library using kyber:
`cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../.CMake/toolchain_avr32.cmake -DOQS_DIST_BUILD=ON -DOQS_USE_OPENSSL=OFF -DCMAKE_BUILD_TYPE=Release -DOQS_BUILD_ONLY_LIB=ON -DOQS_MINIMAL_BUILD="OQS_ENABLE_KEM_kyber_512" ..`

Doing the same thing with `OQS_ENABLE_KEM_sike_p751` yields many pointer conversion warnings
```
../src/kem/sike/external/P751/../ec_isogeny.c:16: warning: passing argument 1 of 'fp2sqr751_mont' from incompatible pointer type
../src/kem/sike/external/P751/../fpx.c:256: note: expected 'const digit_t (*)[24]' but argument is of type 'digit_t (*)[24]'
```

**Comment by mnemocron** [comment]
Ultimately we decided not to build the full liboqs project for our avr32 target and just use kyber-512 from the [pq-crystals/kyber](https://github.com/pq-crystals/kyber) project, which compiles right away for `avr32-gcc`.

**Comment by baentsch** [comment]
Thanks for letting us know. Please also let us know if/when you see a need for other algorithms on that platform.

**Comment by mnemocron** [comment]
Follow up for the interested reader:
Our work using kyber on AVR32 will be presented & published at the 2022 [smallsat](https://smallsat.org/) conference.
- Arxiv [Link](https://arxiv.org/abs/2206.00978)
- AVR32 version of kyber: [kyber-avr32](https://github.com/fhnw-ise-qcrypt/kyber-avr32)
- in context with satellite firmware: [PQKEX-nanosat-src](https://github.com/fhnw-ise-qcrypt/PQKEX-nanosat-src)

**Comment by baentsch** [comment]
Too bad you couldn't use `liboqs` b/o C11/aligned alloc. But then again, I'm not sure other algorithms would have been small/performant enough for your "space adventure". Thanks for letting us know, anyway: Cool stuff!
