### ISSUE TITLE
Investigate constant time test errors

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1087]
Constant time tests keep failing when CPU extensions are activated: [Sep 5](https://app.circleci.com/pipelines/github/open-quantum-safe/liboqs/1766/workflows/bacfb0fa-fa72-49d7-b40a-30fc6aec05da/jobs/15531) , [Sep 12](https://app.circleci.com/pipelines/github/open-quantum-safe/liboqs/1772/workflows/22a6d567-df7c-486d-bb39-6ff9c15aa3ae/jobs/15550).

A quick analysis:
```
> python3 testcompare.py tests-20210905.log 
85 tests started, 84 passed: 
  SPHINCS+-SHA256-256s-robust not passed
> python3 testcompare.py tests-20210912.log 
85 tests started, 80 passed: 
  SPHINCS+-SHA256-128s-robust not passed
  SPHINCS+-SHA256-192s-robust not passed
  SPHINCS+-SHA256-256s-robust not passed
  Rainbow-V-Compressed not passed
  SPHINCS+-SHA256-192s-simple not passed
```

Suggestions for improvement solicited: Extending `no_output_timeout` beyond 1h? Dropping some algs from testing? Re-running and debugging locally?...

**Comment by dstebila** [comment]
I think we should drop these algorithms from the test, and make a note on the release page for the wiki that these tests should be run locally before release.
