### ISSUE TITLE
test_style failed with 127 and test_spdx - assert False

### ISSUE THREAD

**Issue by nasastry** [open-quantum-safe/liboqs#1096]
git head is at 9be13d2

Re-create steps:

```
                git clone -b main https://github.com/open-quantum-safe/liboqs.git
                cd liboqs

        and build:

                mkdir build && cd build
                cmake -GNinja ..
                ninja
```

Due to the error https://github.com/open-quantum-safe/liboqs/issues/1095 commented out '--numprocesses=auto' in `build.ninja` file.

And ran the tests:
```
FAILED tests/test_code_conventions.py::test_style - AssertionError: Got unexpected return code 127
FAILED tests/test_code_conventions.py::test_spdx - assert False
======================= 2 failed, 615 passed, 251 skipped in 261.89s (0:04:21) =======================
```
[liboqs_run_tests.txt](https://github.com/open-quantum-safe/liboqs/files/7233256/liboqs_run_tests.txt)
Attached the full run log.

Thanks!!

**Comment by baentsch** [comment]
Your run log contains this error message:

> xargs: astyle: No such file or directory

-> `astyle` is missing. Is it possible you didn't read https://github.com/open-quantum-safe/liboqs#linuxmacos? This would also explain #1095 ... Please follow all statements in [the README](https://github.com/open-quantum-safe/liboqs) and close #1095 and #1096 if things improve then.

**Comment by baentsch** [comment]
Closing assuming https://github.com/open-quantum-safe/liboqs/issues/1095#issuecomment-927570521 applies here too.

**Comment by oDinZu** [comment]
Today on compilation  via Arch Linux; I received the same error. `[gw0] [ 33%] FAILED tests/test_code_conventions.py::test_style` It was the only error that failed the tests. 

I currently have `astyle 3.4.10-1` installed

I am doing a fresh compile again and will update this post if anything changes.
