### ISSUE TITLE
liboqs on Ubuntu 20

### ISSUE THREAD

**Issue by manzarmoradi** [open-quantum-safe/liboqs#1099]
Hi all,

I tried liboqs, but fail. 

project@project:~/liboqs/build$ cmake -GNinja ..
-- The C compiler identification is GNU 9.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at .CMake/gcc_clang_intrinsics.cmake:9 (message):
  Could not compile .CMake/detect_gcc_clang_intrinsics.cChange Dir:
  /home/project/liboqs/build/CMakeFiles/CMakeTmp

  

  Run Build Command(s):/usr/bin/ninja cmTC_f6544 && [1/2] Building C object
  CMakeFiles/cmTC_f6544.dir/detect_gcc_clang_intrinsics.c.o

  FAILED: CMakeFiles/cmTC_f6544.dir/detect_gcc_clang_intrinsics.c.o

  /usr/bin/cc -fPIE -march=native -o
  CMakeFiles/cmTC_f6544.dir/detect_gcc_clang_intrinsics.c.o -c
  /home/project/liboqs/.CMake/detect_gcc_clang_intrinsics.c

  cc1: error: bad value (‘tigerlake’) for ‘-march=’ switch

  cc1: note: valid arguments to ‘-march=’ switch are: nocona core2
  nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell
  core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client
  icelake-server cascadelake bonnell atom silvermont slm goldmont
  goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000
  nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64
  athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4
  znver1 znver2 btver1 btver2 native

  cc1: error: bad value (‘tigerlake’) for ‘-mtune=’ switch

  cc1: note: valid arguments to ‘-mtune=’ switch are: nocona core2
  nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell
  core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client
  icelake-server cascadelake bonnell atom silvermont slm goldmont
  goldmont-plus tremont knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000
  nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64
  athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4
  znver1 znver2 btver1 btver2 generic native

  ninja: build stopped: subcommand failed.

  

Call Stack (most recent call first):
  .CMake/compiler_opts.cmake:49 (include)
  CMakeLists.txt:89 (include)

-- Configuring incomplete, errors occurred!
See also "/home/project/liboqs/build/CMakeFiles/CMakeOutput.log".

Ubuntu version and GCC version:
ubuntu1~20.04
gcc version 9.3.0 

Thank you,

**Comment by jschanck** [comment]
This is an issue with how Ubuntu packaged gcc-9. You might try upgrading to gcc-10. Alternatively, if you have clang installed you can try building with `cmake -GNinja -DCMAKE_C_COMPILER=clang ..`

**Comment by manzarmoradi** [comment]
I got an error. 

project@project:~/liboqs/build$ cmake -GNinja -DCMAKE_C_COMPILER=clang ..
CMake Error at .CMake/gcc_clang_intrinsics.cmake:9 (message):
  Could not compile .CMake/detect_gcc_clang_intrinsics.cChange Dir:
  /home/project/liboqs/build/CMakeFiles/CMakeTmp

  

  Run Build Command(s):/usr/bin/ninja cmTC_59afc && [1/2] Building C object
  CMakeFiles/cmTC_59afc.dir/detect_gcc_clang_intrinsics.c.o

  FAILED: CMakeFiles/cmTC_59afc.dir/detect_gcc_clang_intrinsics.c.o

  /usr/bin/cc -fPIE -march=native -o
  CMakeFiles/cmTC_59afc.dir/detect_gcc_clang_intrinsics.c.o -c
  /home/project/liboqs/.CMake/detect_gcc_clang_intrinsics.c

  cc1: error: bad value (‘tigerlake’) for ‘-march=’ switch

  cc1: note: valid arguments to ‘-march=’ switch are: nocona core2
  nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell
  core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client
  icelake-server cascadelake bonnell atom silvermont slm goldmont
  goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000
  nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64
  athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4
  znver1 znver2 btver1 btver2 native

  cc1: error: bad value (‘tigerlake’) for ‘-mtune=’ switch

  cc1: note: valid arguments to ‘-mtune=’ switch are: nocona core2
  nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell
  core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client
  icelake-server cascadelake bonnell atom silvermont slm goldmont
  goldmont-plus tremont knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000
  nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64
  athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4
  znver1 znver2 btver1 btver2 generic native

  ninja: build stopped: subcommand failed.

  

Call Stack (most recent call first):
  .CMake/compiler_opts.cmake:49 (include)
  CMakeLists.txt:89 (include)


-- Configuring incomplete, errors occurred!
See also "/home/project/liboqs/build/CMakeFiles/CMakeOutput.log".
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_C_COMPILER= clang

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by baentsch** [comment]
The last run still seems to use cc1 and not clang. You may want to clear the `build` folder completely and _then_ run the command suggested by @jschanck in that clean setup.

**Comment by manzarmoradi** [comment]
@baentsch  Thank you for helpful comment.

**Comment by manzarmoradi** [comment]
@jschanck  Thank you for helpful comment. Your solution solves the issue.
