### ISSUE TITLE
--enable-mcbits needs --with-mcbits-dir option

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#110]
On my macOS, `./configure --enable-mcbits` doesn't find libsodium, despite it having been installed with `brew install libsodium`.  Can you add a `--with-mcbits-dir` similar to the `--with-openssl-dir` and `--with-gmp-dir` options?

**Comment by tlepoint** [comment]
+1, I ran into this problem recently on Linux. What if libsodium is not in the usual directories?
I would suggest a `--with-libsodium-dir`.
