### ISSUE TITLE
Link NTRU using static libraries rather than dynamic libraries

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#111]
Building with `--enable-ntru` fails on my macOS.  More specifically, the liboqs build completes, but then trying to run `./test_kex` fails with the following error:

~~~
dyld: Library not loaded: /usr/local/lib/libntruencrypt.0.dylib
  Referenced from: /Users/dstebila/Desktop/liboqs/./test_kex
  Reason: image not found
~~~

Can you change the build process so it statically links in libntruencrypt.a at compile time rather than dynamically linking in libntruencrypt.dylib at runtime?

**Comment by sebastianv89** [comment]
I believe we should instead include the NTRU code in the project (see #116)
