### ISSUE TITLE
Constant time checks for aarch64

### ISSUE THREAD

**Issue by Martyrshot** [open-quantum-safe/liboqs#1119]
As per a comment by @baentsch on this [PR](https://github.com/open-quantum-safe/liboqs/pull/1117#pullrequestreview-793886320), do we want to add constant time checks for aarch64?

**Comment by dstebila** [comment]
That does seem like a good idea. We'll need to run those test suites on an ARM machine though, since it's a runtime test.

**Comment by baentsch** [comment]
> That does seem like a good idea. We'll need to run those test suites on an ARM machine though, since it's a runtime test.

Yes. FWIW/reminder: We have an `aarch64` VM at AWS that's regularly running profiling on that architecture and which might be used for this, too.
