### ISSUE TITLE
SIKE not properly disabled on unsupported architectures

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#1128]
With Debian now trying to [package liboqs](https://tracker.debian.org/pkg/liboqs), they build on a lot more platforms than we support, many of which [the build fails on](https://buildd.debian.org/status/package.php?p=liboqs).  I'm not suggesting we try to support those at this point in time.  However, one set of build failures (see e.g. [this build log](https://buildd.debian.org/status/fetch.php?pkg=liboqs&arch=mips64el&ver=0.7.0.27.gba5b61a7%2Bdfsg-1&stamp=1637141544&raw=0)) seems to be related to SIKE's config.h header file thinking it's on an unsupported architecture, but apparently CMake still tried to compile SIKE.  In other words, there seems to be a mismatch between architectures where CMake thinks it should try compiling SIKE and architectures that SIKE's config.h header file is willing to support.

**Comment by christianpaquin** [comment]
SIKE's config does explicitly reject unsupported platforms. I can add a compile guard in the CMakeLists building on non-supported platform. Do we have an environment to test this?

**Comment by baentsch** [comment]
> there seems to be a mismatch between architectures where CMake thinks it should try compiling SIKE and architectures that SIKE's config.h header file is willing to support

I'm not sure this is the case: There [already is a guard](https://github.com/open-quantum-safe/liboqs/blob/8df1a81dd7e01901456f8666456b107cb2ab972d/CMakeLists.txt#L68-L72) explicitly overruled in this build.

> I can add a compile guard in the CMakeLists building on non-supported platform. 

Given the pre-existing guard, what about just adding a SIKE-disablement instruction into that guard (and maybe for all other algorithms we know fail building on something unknown)?

> Do we have an environment to test this?

I'm not aware we have a test or cross-dev environment for MIPS.

**Comment by christianpaquin** [comment]
> There [already is a guard](https://github.com/open-quantum-safe/liboqs/blob/8df1a81dd7e01901456f8666456b107cb2ab972d/CMakeLists.txt#L68-L72) explicitly overruled in this build.

I was thinking about adding a guard [here in the CMakeLists](https://github.com/open-quantum-safe/liboqs/blob/main/src/kem/sike/CMakeLists.txt#L3) to list the SIKE supported archs, to avoid the preprocessor's failure [here in the config](https://github.com/open-quantum-safe/liboqs/blob/main/src/kem/sike/external/config.h#L73
).
