### ISSUE TITLE
Fallout of removal of non-free files

### ISSUE THREAD

**Issue by merkys** [open-quantum-safe/liboqs#1130]
Debian can ship only software which is explicitly free and open source. liboqs does a great job by listing licenses of its components in `README.md`, as well as adding `SPDX-License-Identifier` fields to all its files.

However, the following files have undefined licenses and contain notices "All rights reserved", thus signalling non-free code:
* `src/common/pqclean_shims/nistseedexpander.c`
* `src/common/pqclean_shims/nistseedexpander.h`
* `src/common/rand/rand_nist.c`

To package liboqs for Debian, these files have to be excluded, resulting in `kat_kem` and `kat_sig` being disabled.

I am thinking how this situation could be alleviated. Maybe the aforementioned files have been relicensed already, or maybe they could be replaced with freely distributable software?

**Comment by baentsch** [comment]
These files seem to originate with the [NIST competition](https://csrc.nist.gov/projects/post-quantum-cryptography) and considering NIST's publicly stated "open stance" it should be possible to get NIST to change those license statements (if not already done). Second option, glancing the code over, IMO it doesn't appear to be very complicated, inventive or a lot of code that would be hard to re-write. 
Any preference (or contacts helping the decision) which way to go, @dstebila @christianpaquin @bhess ?
When looking at the code's etymology --which seems to be rather well-documented [here](https://csrc.nist.gov/CSRC/media/Projects/Post-Quantum-Cryptography/documents/example-files/api-notes.pdf)-- one may think that these files' license statements are unnecessarily or even incorrectly restrictive, so maybe asking NIST is truly very straightforward.

**Comment by dstebila** [comment]
NIST has kindly updated the licenses in the original files in question; see the [updated archive](https://csrc.nist.gov/csrc/media/Projects/post-quantum-cryptography/documents/example-files/source-code-files-for-kats.zip).  We'll need to update our files accordingly, but hopefully that will resolve this and allow the KAT binaries to be distributed. I don't think there's a `SPDX-License-Identifier` exactly for this scenario, but we can just include the full text.

**Comment by baentsch** [comment]
@merkys As I am no lawyer, could you please take a look at #1142 and let us know whether this indeed resolves the issue? I refrained from completely removing the previous text as it allows one to follow the code's origin and modification history. We arguably could do that, though, as the "new" NIST code files don't contain those traces either.
@dstebila : Your opinion?

**Comment by merkys** [comment]
It is really great that NIST has added an explicit statement. I read it as fulfilling [https://www.debian.org/social_contract#guidelines](Debian's Free Software Guidelines), as it explicitly allows free distribution and modifications of the source code. Thus there should be no more problems with shipping the aforementioned files.

NIST statement does not seem to fall under any of the SPDX-approved licenses, thus `SPDX-License-Identifier` should probably stay `Unknown`. But again, this is not a problem anymore.

@baentsch To me #1142 looks like an appropriate solution. With this I no longer need to remove any files. I agree with you that previous text should remain in the files for reference.

Thanks a lot for sorting this issue out!
