### ISSUE TITLE
OQS_DIST_BUILD not working for aarch64

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1146]
When working through https://github.com/open-quantum-safe/liboqs/issues/1145 it became apparent that [OQS_DIST_BUILD](https://github.com/open-quantum-safe/liboqs/wiki/Customizing-liboqs#oqs_dist_build) is not implemented for `aarch64`: This also explains initially surprisingly good performance results for "distributable" (presumed 'reference') ARM64 code (https://github.com/open-quantum-safe/profiling/issues/68). See for example https://github.com/open-quantum-safe/liboqs/blob/8e22871ff6cfdc69dba6748bbd902ed0fb316fc3/src/kem/kyber/kem_kyber_512.c#L67-L83 for missing `OQS_DIST_BUILD` guards in the case of `aarch64` code. Instead of changing the implementation we could of course also document `OQS_DIST_BUILD` as not applicable for ARM64.

**Comment by Martyrshot** [comment]
I think it's probably worthy fixing this. I'm not sure when I'll have a chance to resolve this oversight, but I'll take a look at it asap.

**Comment by baentsch** [comment]
If I'm not utterly mistaken, the reason for the problem is that "required-flags" for `aarch64` is empty, thus skipping the [logic otherwise adding the OQS_DIST_BUILD ifdefs](https://github.com/open-quantum-safe/liboqs/blob/8e22871ff6cfdc69dba6748bbd902ed0fb316fc3/scripts/copy_from_upstream/src/kem/family/kem_scheme.c#L90-L94). So the question is [can this be done differently](https://github.com/open-quantum-safe/liboqs/blob/8e22871ff6cfdc69dba6748bbd902ed0fb316fc3/scripts/copy_from_upstream/copy_from_upstream.py#L524-L529) (i.e., keeping it for OQS code generation purposes, but dropping it when compiling -- if necessary)?

**Comment by dstebila** [comment]
I think it is the case that aarch64 always has NEON instructions available, so there's no need for an extra required flag.

Which would mean that even distributable builds for aarch64 should always have NEON activated.  Though they might not necessarily have AES or SHA-2 extensions.

**Comment by baentsch** [comment]
> I think it is the case that aarch64 always has NEON instructions available, so there's no need for an extra required flag. 

This page concurs with this thinking: https://en.wikipedia.org/wiki/AArch64

In that case, #1148 arguably is pointless -- at best it might set the stage for a time when there is code introduced that relies on truly _optional_ ARM64 instructions. In this light I'm fine with closing #1146 either way (not doing anything or adding #1148).
