### ISSUE TITLE
liboqs.so: found executable STACK entry: GNU_STACK RWE

### ISSUE THREAD

**Issue by vt-alt** [open-quantum-safe/liboqs#1159]
I decided to enable strict ELF checker in ALT Linux when building liboqs package, and it reported that `liboqs.so` have executable stack:

`verify-elf: ERROR: ./usr/lib64/liboqs.so.0.7.1: found executable STACK entry:   GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RWE 0x10`

This is output of `readelf --wide --segments -- ./usr/lib64/liboqs.so.0.7.1` and executable stack is marked with letter `E' in flags column.

Executable stack is rare occurrence these days so you might want to fix it somehow.

**Comment by vt-alt** [comment]
After some investigation it seems related to compiling asm (.S) files which does not contain proper [markings](https://www.win.tue.nl/~aeb/linux/hh/protection.html).

It helped locally to build with `-DCMAKE_ASM_FLAGS=` with added `-Wa,--noexecstack`.

**Comment by dstebila** [comment]
Thanks for the issue.  I've tried to add this option via #1161.  Can you check if that resolves the issue?  I don't have the full toolchain installed to easily check.
