### ISSUE TITLE
Build failures with gcc on Apple M1

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#1164]
Building liboqs with gcc-11 on an Apple M1 Mac yields build failures related to Kyber and Saber NTT code.

Reproduce by checking out 0.7.1, and then running `cmake -GNinja -DCMAKE_C_COMPILER=gcc-11 ..`.  (Note that there are other build failures on HEAD when building with gcc-11 on macOS which are independent of this which I'll create a separate issue for.)

```
[667/1230] Building ASM object src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_base_mul.S.o
FAILED: src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_base_mul.S.o 
/opt/homebrew/bin/gcc-11  -I/Users/dstebila/Dev/OQS/liboqs/build/include -I/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64 -I/Users/dstebila/Dev/OQS/liboqs/src/common/pqclean_shims -arch arm64 -fPIC -mcpu=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,-dead_strip -MD -MT src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_base_mul.S.o -MF src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_base_mul.S.o.d -o src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_base_mul.S.o -c /Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_base_mul.S
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_base_mul.S:10:3: error: unknown directive
  .type PQCLEAN_KYBER1024_AARCH64_asm_point_mul_extended, %function
  ^
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_base_mul.S:77:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_asymmetric_mul, %function
^
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_base_mul.S:232:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_asymmetric_mul_montgomery, %function
^
[668/1230] Building ASM object src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_iNTT.S.o
FAILED: src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_iNTT.S.o 
/opt/homebrew/bin/gcc-11  -I/Users/dstebila/Dev/OQS/liboqs/build/include -I/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64 -I/Users/dstebila/Dev/OQS/liboqs/src/common/pqclean_shims -arch arm64 -fPIC -mcpu=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,-dead_strip -MD -MT src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_iNTT.S.o -MF src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_iNTT.S.o.d -o src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_iNTT.S.o -c /Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_iNTT.S
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_iNTT.S:8:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_intt_SIMD_bot, %function
^
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_iNTT.S:94:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_intt_SIMD_top, %function
^
[669/1230] Building ASM object src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_NTT.S.o
FAILED: src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_NTT.S.o 
/opt/homebrew/bin/gcc-11  -I/Users/dstebila/Dev/OQS/liboqs/build/include -I/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64 -I/Users/dstebila/Dev/OQS/liboqs/src/common/pqclean_shims -arch arm64 -fPIC -mcpu=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,-dead_strip -MD -MT src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_NTT.S.o -MF src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_NTT.S.o.d -o src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_NTT.S.o -c /Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_NTT.S
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_NTT.S:8:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_ntt_SIMD_top, %function
^
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_NTT.S:177:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_ntt_SIMD_bot, %function
^
[671/1230] Building ASM object src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_poly.S.o
FAILED: src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_poly.S.o 
/opt/homebrew/bin/gcc-11  -I/Users/dstebila/Dev/OQS/liboqs/build/include -I/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64 -I/Users/dstebila/Dev/OQS/liboqs/src/common/pqclean_shims -arch arm64 -fPIC -mcpu=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,-dead_strip -MD -MT src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_poly.S.o -MF src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_poly.S.o.d -o src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_poly.S.o -c /Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_poly.S
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_poly.S:8:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_add_reduce, %function
^
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_poly.S:72:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_sub_reduce, %function
^
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_poly.S:136:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_add_add_reduce, %function
^
[676/1230] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_6960119f_vec.dir/pqclean_mceliece6960119f_vec/controlbits.c.o
ninja: build stopped: subcommand failed.
```

**Comment by baentsch** [comment]
Did you try `brew install x86_64-elf-gcc` and run that instead of "plain" gcc-11 (in the hope of using a different assembler)?

**Comment by dstebila** [comment]
> Did you try `brew install x86_64-elf-gcc` and run that instead of "plain" gcc-11 (in the hope of using a different assembler)?

I'd never trid that before.  I just installed it and tried `cmake -GNinja -DCMAKE_C_COMPILER=x86_64-elf-gcc ..` which fails with the following output:

```
CMake Error at /usr/local/Cellar/cmake/3.22.1/share/cmake/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/usr/local/bin/x86_64-elf-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/dstebila/Dev/OQS/liboqs/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/local/bin/ninja cmTC_04763 && [1/2] Building C object CMakeFiles/cmTC_04763.dir/testCCompiler.c.o
    [2/2] Linking C executable cmTC_04763
    FAILED: cmTC_04763 
    : && /usr/local/bin/x86_64-elf-gcc -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/cmTC_04763.dir/testCCompiler.c.o -o cmTC_04763   && :
    /usr/local/opt/x86_64-elf-binutils/bin/x86_64-elf-ld: Error: unable to disambiguate: -search_paths_first (did you mean --search_paths_first ?)
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:15 (project)
```

**Comment by baentsch** [comment]
What has generated the option "-Wl,-search_paths_first " ? It seems to be missing a second "-" (whatever that option is -- it's nowhere in the `liboqs` code tree). What about trying to run `cmake` with `-DCMAKE_VERBOSE_MAKEFILE=ON` (instead of `-GNinja`) and then run `make --trace`? May also help in the case of #1166.

**Comment by ChristianOConnor** [comment]
Are there clear instructions yet on how to build this on an M1 Mac? I want to build it or at least use a pre-built binary and I have a MacBook M1 Pro.

**Comment by ChristianOConnor** [comment]
> > Are there clear instructions yet on how to build this on an M1 Mac? I want to build it or at least use a pre-built binary and I have a MacBook M1 Pro.
> 
> If you use Apple's built-in clang, then it will build just fine on an M1 Mac. But we don't have a solution yet for gcc builds on M1.

Oh okay I will try that. After I build it I can run the binary natively? Like I can just import the dylib file into my project that uses liboqs-python and that will work?

**Comment by dstebila** [comment]
> Oh okay I will try that. After I build it I can run the binary natively? Like I can just import the dylib file into my project that uses liboqs-python and that will work?

I don't see any reason why shouldn't be able to use the binary.

**Comment by ChristianOConnor** [comment]
> > Oh okay I will try that. After I build it I can run the binary natively? Like I can just import the dylib file into my project that uses liboqs-python and that will work?
> 
> I don't see any reason why shouldn't be able to use the binary.

Yeah it works! Thanks!

**Comment by baentsch** [comment]
Sorry for being a killjoy but the issue is not fully resolved: Execute `cmake -GNinja -DCMAKE_C_COMPILER=gcc-11 -DBUILD_SHARED_LIBS=ON -DOQS_USE_OPENSSL=OFF ..` and see this

```[857/1233] Building C object src/common/CMakeFiles/common.dir/sha2/sha2_ni.c.o
FAILED: src/common/CMakeFiles/common.dir/sha2/sha2_ni.c.o 
/opt/homebrew/bin/gcc-11 -DOQS_HAVE_GETENTROPY -I/Users/baentsch/git/liboqs/build/include -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.0.sdk -fPIC -fvisibility=hidden -mcpu=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,-dead_strip -Wbad-function-cast -std=gnu11 -MD -MT src/common/CMakeFiles/common.dir/sha2/sha2_ni.c.o -MF src/common/CMakeFiles/common.dir/sha2/sha2_ni.c.o.d -o src/common/CMakeFiles/common.dir/sha2/sha2_ni.c.o -c /Users/baentsch/git/liboqs/src/common/sha2/sha2_ni.c
In file included from /Users/baentsch/git/liboqs/src/common/sha2/sha2_ni.c:10:
/Users/baentsch/git/liboqs/src/common/sha2/sha2_ni.c: In function 'crypto_hashblocks_sha256_ni':
/opt/homebrew/Cellar/gcc/11.2.0_3/lib/gcc/11/gcc/aarch64-apple-darwin21/11/include/arm_neon.h:25281:1: error: inlining failed in call to 'always_inline' 'vsha256h2q_u32': target specific option mismatch
25281 | vsha256h2q_u32 (uint32x4_t __hash_efgh, uint32x4_t __hash_abcd, uint32x4_t __wk)
[...]
```

**Comment by Martyrshot** [comment]
Looking into this a bit, it looks like gcc-11 thinks that the m1 doesn't have crypto extension support (when it indeed does). This is likely because apple is failing to advertise them, or is advertising them in a non-standard way. (We have to look for them indirectly in our own scripts, even when using appleclang)

In order to tell gcc-11 "no, trust me it's there, insert those instructions", I need to specify an arm version and enable the crypto extensions.

One option to fix this is to specify the arm abi version and compiling for that version. The m1 series chips are version 8.5-A, however we would likely want to use something like 8.1 to support more of their hardware? The minimum would be 8.0-A, which supports A7 and newer chips. I'm not sure how using an older abi version would effect compilation and the gcc's instruction choices. Does anyone have any insight or thoughts into this?

**Comment by baentsch** [comment]
> Does anyone have any insight or thoughts into this?

Nope :-( Personally I wouldn't want to "second guess" Apple's choice of ARM abis, though. Thus I'd favour a very specific fix for an ABI version we know fits their current CPUs. If they move to another ARM version this might break again -- or they'll contribute to `gcc` for this madness to not happen again: `liboqs` can't be the only code base fighting with this (?) Looking at https://gcc.gnu.org/bugzilla/ I didn't immediately find a report -- maybe worth while submitting one?

**Comment by Martyrshot** [comment]
After running `speed_common` it looks like the results between armv8-a and armv8.5-a are basically the same. I am only specifying the architecture for the sha2 native instructions compile unit so as long as these are similar enough then we shouldn't see performance degradation elsewhere. 

Here is the output from `speed_common` for the two arm versions:

`armv8-a` (Oldest armv8)
Speed test
==========
Started at 2022-02-01 09:36:00
Operation                      | Iterations | Total time (s) | Time (us): mean | pop. stdev | High-prec time (ns): mean | pop. stdev
------------------------------ | ----------:| --------------:| ---------------:| ----------:| -------------------------:| ----------:
OQS_AES128_ECB_load+free_sch   |    1861200 |          1.000 |           0.537 |      0.515 |                      2815 |    3147686
OQS_AES128_ECB_enc_sch         |    3056813 |          1.000 |           0.327 |      0.475 |                       298 |        465
OQS_AES128_ECB_enc             |    1203167 |          1.000 |           0.831 |      0.404 |                       802 |        429
OQS_AES256_ECB_load+free_sch   |    1442334 |          1.000 |           0.693 |      0.484 |                       664 |        497
OQS_AES256_ECB_enc_sch         |    2294261 |          1.000 |           0.436 |      0.512 |                       406 |        509
OQS_AES256_ECB_enc             |     898795 |          1.000 |           1.113 |      0.356 |                      1083 |        328
OQS_SHA2_sha256                |    7564246 |          1.000 |           0.132 |      0.346 |                      1806 |    2703650
OQS_SHA2_sha384                |    2702287 |          1.000 |           0.370 |      0.690 |                       341 |        684
OQS_SHA2_sha512                |    2733980 |          1.000 |           0.366 |      0.500 |                       336 |        492
OQS_SHA3_sha3_256              |    2521594 |          1.000 | 7315509187327.638 | 11616680775110636.000 |                       367 |        506
OQS_SHA3_sha3_384              |    2514829 |          1.000 |           0.398 |      0.508 |                       368 |        502
OQS_SHA3_sha3_512              |    2589494 |          1.000 |           0.386 |      0.499 |                      3674 |    3774511
OQS_SHA3_shake128              |    2590370 |          1.000 |           0.386 |      0.497 |                       357 |        491
OQS_SHA3_shake256              |    2585989 |          1.000 |           0.387 |      0.494 |                       357 |        487


`armv8.5-a` (Version apple m1 uses)
Speed test
==========
Started at 2022-02-01 09:38:57
Operation                      | Iterations | Total time (s) | Time (us): mean | pop. stdev | High-prec time (ns): mean | pop. stdev
------------------------------ | ----------:| --------------:| ---------------:| ----------:| -------------------------:| ----------:
OQS_AES128_ECB_load+free_sch   |    1908159 |          1.000 |           0.524 |      0.513 |                       495 |        516
OQS_AES128_ECB_enc_sch         |    3165989 |          1.000 |           0.316 |      0.468 |                       288 |        458
OQS_AES128_ECB_enc             |    1232912 |          1.000 |           0.811 |      0.421 |                       783 |        445
OQS_AES256_ECB_load+free_sch   |    1497969 |          1.000 |           0.668 |      0.485 |                       639 |        497
OQS_AES256_ECB_enc_sch         |    2383210 |          1.000 |           0.420 |      0.506 |                       391 |        501
OQS_AES256_ECB_enc             |     935588 |          1.000 |           1.069 |      0.329 |                      1040 |        295
OQS_SHA2_sha256                |    7804267 |          1.000 |           0.128 |      0.341 |                       100 |        307
OQS_SHA2_sha384                |    2799614 |          1.000 |           0.357 |      0.496 |                       329 |        487
OQS_SHA2_sha512                |    2821947 |          1.000 |           0.354 |      0.494 |                       326 |        485
OQS_SHA3_sha3_256              |    2580407 |          1.000 |           0.388 |      0.525 |                      2023 |    2673031
OQS_SHA3_sha3_384              |    2574009 |          1.000 |           0.388 |      0.524 |                       359 |        515
OQS_SHA3_sha3_512              |    2518129 |          1.000 |           0.397 |      6.006 |                       365 |       5289
OQS_SHA3_shake128              |    2584426 |          1.000 |           0.387 |      0.568 |                       357 |        556
OQS_SHA3_shake256              |    2553368 |          1.000 |           0.392 |      0.629 |                       362 |        618

**Comment by baentsch** [comment]
Thanks for the test (and results), @Martyrshot. So code specifically built for M1 is 2.5-4% faster on all operations except SHA_shake. This indeed is not really a lot, but IMO a bit too consistent to not be mentioned somewhere; what about adding a notice (pointing to these results) for interested folks, e.g., in a (new) "Performance optimization" section in the [how-to-configure-liboqs Wiki](https://github.com/open-quantum-safe/liboqs/wiki/Customizing-liboqs), stating we opted for a more "generic" ARM level as default build option?
