### ISSUE TITLE
Rainbow update

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1192]
Following the [discussions here](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/KFgw5_qCXiI?pli=1) this issue is to track required adaptations to Rainbow: Already discussed:

- [x] Adding warnings to the liboqs documentation
- [ ] Removing Rainbow level 1
- [ ] Downgrading higher Rainbow levels
- [ ] Rebuilding all OQS downstream software packages (incl. new oqs-openssl hybrids) 

Final resolution of this issue is expected when NIST announces the next PQC evaluation decisions.

**Comment by baentsch** [comment]
Suggest to close as being covered by #1245

**Comment by dstebila** [comment]
As much as it might cause some downstream pain, I am now thinking we probably should remove Rainbow level 1 before the 0.7.2 release, since it is known-broken.

**Comment by baentsch** [comment]
> we probably should remove Rainbow level 1 before the 0.7.2 release, since it is known-broken

No objections. To the contrary, I now feel vindicated for doing [this](https://github.com/openssl/openssl/blob/2837b19fcba4bf4ff2ecdc8435c650bf18c27552/test/recipes/95-test_external_oqsprovider_data/oqsprovider.sh#L57)...

**Comment by baentsch** [comment]
> As much as it might cause some downstream pain, 

Thinking about that part of the statement again, what pain would the _complete removal_ of Rainbow cause? Not doing a release simply means running all templating scripts and CI on all project "main" branches. Should be smooth. Doing a release (for all components) just for that would be tedious. A re-set of strengths (and retaining) some Rainbow variants would have been tedious. Outright pruning should be straightforward. We just need to make sure no IDs assigned to Rainbow variants are (re)used, e.g., in OpenSSL. If there are no objections, will do a PR right away...

**Comment by baentsch** [comment]
Confirmed (by doing it): Complete removal of Rainbow works well through the whole stack.

Now what? As [discussed elsewhere](https://github.com/PQClean/PQClean/issues/447#issuecomment-1179012231) implement the issue in full (removal only of level 1 _and_ corresponding downgrade of all other levels as [per the Rainbow author's recommendation](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/KFgw5_qCXiI/m/cr66AGOfAgAJ) _and_ downstream changes, incl. assignments of new OIDs and code points) OR alternatively some (in my eyes) "incomplete" approach of only removing the broken L1 (and leaving the weaker-than-stated L3&L5 as-is)?

Worthwhile asking the Rainbow authors for their opinion? Or the IBM team that broke it? Would be fair for the latter to also close out the issue... :-)

My personal preference (driven by thinking about users of the library not expecting acknowledged "sub-optimal" (aka broken or weak) algorithms in it) would be outright removal of the whole family.

**Comment by dstebila** [comment]
We'll remove Rainbow level 1 for 0.7.2 via #1263 and then remove the remaining Rainbow after that.

**Comment by baentsch** [comment]
All right -- that then means no new (OpenSSL) OIDs, just dropping (piece-meal) the rainbow ones (1 for 0.7.2; the rest afterwards), right? If so, downstream changes are small indeed.
