### ISSUE TITLE
Want to integerate in iOS app 

### ISSUE THREAD

**Issue by BTManiKandan** [open-quantum-safe/liboqs#1198]
Hai 

I have developed my iOS application in swift language and I like to integrate liboqs in my application. Let me know the possibility and process to integrate this in my application

**Comment by dstebila** [comment]
Sorry, but we don't have any SDKs or examples specifically for iOS.  However you should be able to compile liboqs for Apple A-series chips without a problem, as we have tested liboqs compilation for Apple M1 chips.  If you come up with any working example code that you'd like to share, we'd be happy to receive it as a pull request.

**Comment by baentsch** [comment]
@BTManiKandan FYI, a swift Google search (pardon the pun) returns this: https://theswiftdev.com/how-to-call-c-code-from-swift . Seems pretty straightforward.
