### ISSUE TITLE
Unable to Import a Post Quantum Certificate in PQ Chromium

### ISSUE THREAD

**Issue by scottthomas007** [open-quantum-safe/liboqs#1205]
Bonjour,

I created a CA of rsa3072_falcon512. When i try to import it in [PQCACerts.zip](https://github.com/open-quantum-safe/liboqs/files/8574550/PQCACerts.zip) as a trusted Root CA. I get the following error:

[3742:3742:0426/180506.505104:ERROR:nsNSSCertificateDB.cpp(89)] PK11_ImportCert failed with error -8168

I tried to import other certificate files which are part of the HTTPD & NGINX dockers 
https://hub.docker.com/r/openquantumsafe/httpd
https://hub.docker.com/r/openquantumsafe/nginx

All the certs are attached as PQCACerts.zip

Please guide me on this.

Regards
Scott Thomas

**Comment by baentsch** [comment]
Closing as discussion ongoing [here](https://github.com/open-quantum-safe/oqs-demos/issues/142).
