### ISSUE TITLE
Build fails on arm64: fatal error: 'asm/hwcap.h' file not found

### ISSUE THREAD

**Issue by yurivict** [open-quantum-safe/liboqs#1208]
```
FAILED: src/common/CMakeFiles/common.dir/common.c.o 
/usr/bin/cc  -I/wrkdirs/usr/ports/security/liboqs/work/.build/include -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -fPIC -fvisibility=hidden -Wall -Wextra -Wpedantic -Wno-unused-command-line-argument -O3 -fomit-frame-pointer -Wbad-function-cast -Wcast-qual -Wnarrowing -Wconversion -std=gnu11 -MD -MT src/common/CMakeFiles/common.dir/common.c.o -MF src/common/CMakeFiles/common.dir/common.c.o.d -o src/common/CMakeFiles/common.dir/common.c.o -c /wrkdirs/usr/ports/security/liboqs/work/liboqs-0.7.1/src/common/common.c
/wrkdirs/usr/ports/security/liboqs/work/liboqs-0.7.1/src/common/common.c:96:10: fatal error: 'asm/hwcap.h' file not found
#include <asm/hwcap.h>
         ^~~~~~~~~~~~~
1 error generated.
```

OS: FreeBSD 13

**Comment by baentsch** [comment]
I'm not exactly familiar with arm64 but the include file seems rather "generic" -- at least for gnu compilers. What `cc` are you using in this build? Any suggestions how we can reproduce? @Martyrshot : Any thoughts?

**Comment by Martyrshot** [comment]
I'll need to verify this, but from what I can tell FreeBSD doesn't ship with the `asm/hwcap.h` header. We might need to do something like [this](https://github.com/xmrig/xmrig/pull/2340).

**Comment by Martyrshot** [comment]
@yurivict Could you please provide the commands you use to build liboqs? I've installed FreeBSD 13.1 rc6, but I'm getting different compilation errors than you. I had to patch the `tests/ds_benchmark.h` file, is there any others you modified to get to this point?

**Comment by yurivict** [comment]
```
cd /usr/ports/security/liboqs && make
```

**Comment by yurivict** [comment]
@baentsch 
> I'm not exactly familiar with arm64 but the include file seems rather "generic" -- at least for gnu compilers. What cc are you using in this build?

clang-13

**Comment by Martyrshot** [comment]
Thanks @yurivict. I should have resolved the hwcap.h issue. I'm currently experiencing a lot of undefined references when building tests for sike. Specifically it looks like the .S files aren't being included in the shared library. I seem to remember there being an issue like this in the past, but I haven't been able to find it. @baentsch @dstebila, do either of you remember, or am I making that up?

**Comment by baentsch** [comment]
I do recall issues with SIKE on "surprising" platforms in Debian, but `arm64` should work, right , @christianpaquin? @Martyrshot : Do you mind sharing (via draft PR) what you did (as well as the error messages)? Maybe more eyes have an idea how to resolve this...

**Comment by Martyrshot** [comment]
@baentsch Done! Pr: #1210

**Comment by clausecker** [comment]
`asm/hwcap.h` is a Linux-only header.  It's not generic in any way.  Luckily the actual way to detect the availability of CPU features is the same on FreeBSD: just check the ELF aux vectors.

**Comment by Martyrshot** [comment]
@yurivict, would you mind verifying if the fix provided on the `jg-freebsd-cpu-features` resolves your issue?

**Comment by Martyrshot** [comment]
Ok, sounds good. Thank you!

**Comment by yurivict** [comment]
It looks like there are no more failures on arm64.
