### ISSUE TITLE
Windows-msys2 build failing on picnic

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1218]
There's a recurring [CI error](https://ci.appveyor.com/project/dstebila/liboqs/builds/43744511/job/4f372pki566y29s9) on main branch that's apparently now also holding #1210. Who knows about/looks after that environment? @christianpaquin ? Or shall we drop this? Anyone using this? But then again, the consistent error message about an array index error in picnic may be worth while checking out...

**Comment by christianpaquin** [comment]
I'm not interested in the platform, personally. I'm ok to drop picnic per #1220.

**Comment by sebastinas** [comment]
I'd appreciate to be pinged on issues with Picnic.

**Comment by baentsch** [comment]
@sebastinas thanks for your interest in getting involved with Picnic issues we find. What's your preference on this issue then: Do you want to look into this/provide a solution or shall we close/drop/disregard it?

**Comment by sebastinas** [comment]
My understanding is that msys2 support is being dropped in #1222. So I'll eventually look into fixing it upstream, but it's not a priority.
