### ISSUE TITLE
Integrate SIKE v3.5.1

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/liboqs#1227]
https://github.com/microsoft/PQCrypto-SIDH/releases/tag/v3.5.1  ([diff](https://github.com/microsoft/PQCrypto-SIDH/compare/effa607f244768cdd38f930887076373604eaa78...v3.5.1))

**Comment by baentsch** [comment]
Good opportunity to also resolve the "missing symbols in Windows" mystery (discussed in #1224) at the same time?
