### ISSUE TITLE
Issue with compiling tests/example_sig.c on Ubuntu 

### ISSUE THREAD

**Issue by eimalnuaimi** [open-quantum-safe/liboqs#1230]
Hello, 

I tried to compile the tests/example_sig.c by running `$CC -Ibuild/include -Lbuild/lib tests/example_sig.c -o example_sig -loqs` in the top level directory of liboqs. However, I ended up getting the following error message: 

> bash: -Ibuild/include: No such file or directory

Prior to running the command I made sure to install the dependencies and build the source code which both were successful. What could be wrong here?

**Comment by baentsch** [comment]
Did you set `$CC` to a valid compiler, e.g., `export CC=gcc`? When I run the command quoted verbatim as written above (and setting CC=gcc) all builds just fine... (on Linux -- what is your environment?)

**Comment by eimalnuaimi** [comment]
Thank you. This helped!
