### ISSUE TITLE
Unable to cross compile liboqs for windows in ubuntu 18.04

### ISSUE THREAD

**Issue by evil-user** [open-quantum-safe/liboqs#1235]
Followed instructions on https://github.com/open-quantum-safe/liboqs/wiki/Platform-specific-notes-for-building-liboqs#cross-compiling-on-debianubuntu-linux-for-windows and also installed dependencies mentioned in https://openquantumsafe.org/liboqs/getting-started.html for ubuntu . But i get compile error.
![compileerror](https://user-images.githubusercontent.com/82881725/175820155-d2d64247-342f-4397-842e-cc73e7be5a21.png)

**Comment by evil-user** [comment]
Contents of CMakeOutput.log are : - 

The target system is: Windows -  - AMD64
The host system is: Linux - 5.4.0-120-generic - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/x86_64-w64-mingw32-gcc 
Build flags: 
Id flags:  

The output was:
0


Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"

The C compiler identification is GNU, found in "/home/haha/liboqs/build/CMakeFiles/3.10.2/CompilerIdC/a.exe"

Determining if the C compiler works passed with the following output:
Change Dir: /home/haha/liboqs/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_e1aa2"
[1/2] Building C object CMakeFiles/cmTC_e1aa2.dir/testCCompiler.c.obj
[2/2] Linking C executable cmTC_e1aa2.exe


Detecting C compiler ABI info compiled with the following output:
Change Dir: /home/haha/liboqs/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_aee2c"
[1/2] Building C object CMakeFiles/cmTC_aee2c.dir/CMakeCCompilerABI.c.obj
[2/2] Linking C executable cmTC_aee2c.exe
Using built-in specs.
COLLECT_GCC=/usr/bin/x86_64-w64-mingw32-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/lto-wrapper
Target: x86_64-w64-mingw32
Configured with: ../../src/configure --build=x86_64-linux-gnu --prefix=/usr --includedir='/usr/include' --mandir='/usr/share/man' --infodir='/usr/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir='/usr/lib/x86_64-linux-gnu' --libexecdir='/usr/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --enable-shared --enable-static --disable-multilib --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --libdir=/usr/lib --enable-libstdcxx-time=yes --with-tune=generic --with-headers=/usr/x86_64-w64-mingw32/include --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libgomp --enable-languages=c,c++,fortran,objc,obj-c++,ada --enable-lto --with-plugin-ld --enable-threads=win32 --program-suffix=-win32 --program-prefix=x86_64-w64-mingw32- --target=x86_64-w64-mingw32 --with-as=/usr/bin/x86_64-w64-mingw32-as --with-ld=/usr/bin/x86_64-w64-mingw32-ld --enable-libatomic --enable-libstdcxx-filesystem-ts=yes
Thread model: win32
gcc version 7.3-win32 20180312 (GCC) 
COMPILER_PATH=/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/:/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/:/usr/lib/gcc/x86_64-w64-mingw32/:/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/:/usr/lib/gcc/x86_64-w64-mingw32/:/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/../../../../x86_64-w64-mingw32/bin/
LIBRARY_PATH=/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/:/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/../../../../x86_64-w64-mingw32/lib/
COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_aee2c.exe' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/collect2 -m i386pep -Bdynamic -o cmTC_aee2c.exe /usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/../../../../x86_64-w64-mingw32/lib/crt2.o /usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/crtbegin.o -L/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32 -L/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/../../../../x86_64-w64-mingw32/lib CMakeFiles/cmTC_aee2c.dir/CMakeCCompilerABI.c.obj --out-implib libcmTC_aee2c.dll.a --major-image-version 0 --minor-image-version 0 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt /usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/crtend.o
COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_aee2c.exe' '-mtune=generic' '-march=x86-64'


Parsed C implicit link information from above output:
  link line regex: [^( *|.*[/\])(x86_64-w64-mingw32-ld|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\]+-)?ld|collect2)[^/\]*( |$)]
  ignore line: [Change Dir: /home/haha/liboqs/build/CMakeFiles/CMakeTmp]
  ignore line: []
  ignore line: [Run Build Command:"/usr/bin/ninja" "cmTC_aee2c"]
  ignore line: [[1/2] Building C object CMakeFiles/cmTC_aee2c.dir/CMakeCCompilerABI.c.obj]
  ignore line: [[2/2] Linking C executable cmTC_aee2c.exe]
  ignore line: [Using built-in specs.]
  ignore line: [COLLECT_GCC=/usr/bin/x86_64-w64-mingw32-gcc]
  ignore line: [COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/lto-wrapper]
  ignore line: [Target: x86_64-w64-mingw32]
  ignore line: [Configured with: ../../src/configure --build=x86_64-linux-gnu --prefix=/usr --includedir='/usr/include' --mandir='/usr/share/man' --infodir='/usr/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir='/usr/lib/x86_64-linux-gnu' --libexecdir='/usr/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --enable-shared --enable-static --disable-multilib --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --libdir=/usr/lib --enable-libstdcxx-time=yes --with-tune=generic --with-headers=/usr/x86_64-w64-mingw32/include --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libgomp --enable-languages=c,c++,fortran,objc,obj-c++,ada --enable-lto --with-plugin-ld --enable-threads=win32 --program-suffix=-win32 --program-prefix=x86_64-w64-mingw32- --target=x86_64-w64-mingw32 --with-as=/usr/bin/x86_64-w64-mingw32-as --with-ld=/usr/bin/x86_64-w64-mingw32-ld --enable-libatomic --enable-libstdcxx-filesystem-ts=yes]
  ignore line: [Thread model: win32]
  ignore line: [gcc version 7.3-win32 20180312 (GCC) ]
  ignore line: [COMPILER_PATH=/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/:/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/:/usr/lib/gcc/x86_64-w64-mingw32/:/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/:/usr/lib/gcc/x86_64-w64-mingw32/:/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/../../../../x86_64-w64-mingw32/bin/]
  ignore line: [LIBRARY_PATH=/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/:/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/../../../../x86_64-w64-mingw32/lib/]
  ignore line: [COLLECT_GCC_OPTIONS='-v' '-o' 'cmTC_aee2c.exe' '-mtune=generic' '-march=x86-64']
  link line: [ /usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/collect2 -m i386pep -Bdynamic -o cmTC_aee2c.exe /usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/../../../../x86_64-w64-mingw32/lib/crt2.o /usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/crtbegin.o -L/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32 -L/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/../../../../x86_64-w64-mingw32/lib CMakeFiles/cmTC_aee2c.dir/CMakeCCompilerABI.c.obj --out-implib libcmTC_aee2c.dll.a --major-image-version 0 --minor-image-version 0 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt /usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/crtend.o]
    arg [/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/collect2] ==> ignore
    arg [-m] ==> ignore
    arg [i386pep] ==> ignore
    arg [-Bdynamic] ==> ignore
    arg [-o] ==> ignore
    arg [cmTC_aee2c.exe] ==> ignore
    arg [/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/../../../../x86_64-w64-mingw32/lib/crt2.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/crtbegin.o] ==> ignore
    arg [-L/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32] ==> dir [/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32]
    arg [-L/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/../../../../x86_64-w64-mingw32/lib] ==> dir [/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/../../../../x86_64-w64-mingw32/lib]
    arg [CMakeFiles/cmTC_aee2c.dir/CMakeCCompilerABI.c.obj] ==> ignore
    arg [--out-implib] ==> ignore
    arg [libcmTC_aee2c.dll.a] ==> ignore
    arg [--major-image-version] ==> ignore
    arg [0] ==> ignore
    arg [--minor-image-version] ==> ignore
    arg [0] ==> ignore
    arg [-lmingw32] ==> lib [mingw32]
    arg [-lgcc] ==> lib [gcc]
    arg [-lgcc_eh] ==> lib [gcc_eh]
    arg [-lmoldname] ==> lib [moldname]
    arg [-lmingwex] ==> lib [mingwex]
    arg [-lmsvcrt] ==> lib [msvcrt]
    arg [-ladvapi32] ==> lib [advapi32]
    arg [-lshell32] ==> lib [shell32]
    arg [-luser32] ==> lib [user32]
    arg [-lkernel32] ==> lib [kernel32]
    arg [-lmingw32] ==> lib [mingw32]
    arg [-lgcc] ==> lib [gcc]
    arg [-lgcc_eh] ==> lib [gcc_eh]
    arg [-lmoldname] ==> lib [moldname]
    arg [-lmingwex] ==> lib [mingwex]
    arg [-lmsvcrt] ==> lib [msvcrt]
    arg [/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/crtend.o] ==> ignore
  remove lib [gcc_eh]
  remove lib [msvcrt]
  remove lib [gcc_eh]
  remove lib [msvcrt]
  collapse library dir [/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32] ==> [/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32]
  collapse library dir [/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/../../../../x86_64-w64-mingw32/lib] ==> [/usr/x86_64-w64-mingw32/lib]
  implicit libs: [mingw32;gcc;moldname;mingwex;advapi32;shell32;user32;kernel32;mingw32;gcc;moldname;mingwex]
  implicit dirs: [/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32;/usr/x86_64-w64-mingw32/lib]
  implicit fwks: []




Detecting C [-std=c11] compiler features compiled with the following output:
Change Dir: /home/haha/liboqs/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_a0e51"
[1/2] Building C object CMakeFiles/cmTC_a0e51.dir/feature_tests.c.obj
[2/2] Linking C executable cmTC_a0e51.exe


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_restrict
    Feature record: C_FEATURE:1c_static_assert
    Feature record: C_FEATURE:1c_variadic_macros


Detecting C [-std=c99] compiler features compiled with the following output:
Change Dir: /home/haha/liboqs/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_c6c6e"
[1/2] Building C object CMakeFiles/cmTC_c6c6e.dir/feature_tests.c.obj
[2/2] Linking C executable cmTC_c6c6e.exe


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:1c_variadic_macros


Detecting C [-std=c90] compiler features compiled with the following output:
Change Dir: /home/haha/liboqs/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/ninja" "cmTC_a5b56"
[1/2] Building C object CMakeFiles/cmTC_a5b56.dir/feature_tests.c.obj
[2/2] Linking C executable cmTC_a5b56.exe


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:0c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:0c_variadic_macros

**Comment by baentsch** [comment]
Can you please provide the complete `cmake` command you issued? Looking at the code I wonder... can you please retry with the `cmake` parameter `-DOQS_DIST_BUILD=ON`? To get a clean slate, be sure to wipe the build directory before.

**Comment by evil-user** [comment]
@baentsch i gave cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../.CMake/toolchain_windows-amd64.cmake .. 
command for above logs

**Comment by evil-user** [comment]
Now i tried cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../.CMake/toolchain_windows-amd64.cmake -DOQS_DIST_BUILD=ON -DBUILD_SHARED_LIBS=ON ..
after clearing the contents of build directory and got logs:-

[1/1507] Building ASM object src/kem/sike/CMakeFiles/sike.dir/external/P503/AMD64/fp_x64_asm.S.obj
FAILED: src/kem/sike/CMakeFiles/sike.dir/external/P503/AMD64/fp_x64_asm.S.obj 
/usr/bin/x86_64-w64-mingw32-gcc -DCOMPILER_GCC -DUSE_SIKEP503_ASM -DUSE_SIKEP751_ASM -D_AMD64_ -Iinclude -Wa,--noexecstack -fPIC   -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -Wno-maybe-uninitialized -Wno-unused-function -Wno-pedantic -MD -MT src/kem/sike/CMakeFiles/sike.dir/external/P503/AMD64/fp_x64_asm.S.obj -MF src/kem/sike/CMakeFiles/sike.dir/external/P503/AMD64/fp_x64_asm.S.obj.d -o src/kem/sike/CMakeFiles/sike.dir/external/P503/AMD64/fp_x64_asm.S.obj -c ../src/kem/sike/external/P503/AMD64/fp_x64_asm.S
/usr/bin/x86_64-w64-mingw32-as: unrecognized option '--noexecstack'
[2/1507] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/sk_gen.c.obj
[3/1507] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/operations.c.obj
[4/1507] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/gf.c.obj
[5/1507] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/pk_gen.c.obj
[6/1507] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/fft_tr.c.obj
ninja: build stopped: subcommand failed.

i am using ubuntu 18.04 with 4GB ram and  intel i5 8th generation cpu with 4 cores.

**Comment by baentsch** [comment]
This looks like a separate error in the Windows cross-build code for SIKE. In the short run, you can get around that by disabling SIKE (by adding `-DOQS_ENABLE_KEM_SIKE=OFF -DOQS_ENABLE_KEM_SIDH=OFF` to the `cmake` command line -- again, after clearing build directory contents). On one of my machines, it is also necessary to disable Picnic (`-DOQS_ENABLE_SIG_PICNIC=OFF`).

There's clearly several things wrong with the cross-build... Thanks for making us aware of these issues. 

Please let us know if this is urgent for you or whether you can keep going for the time being by using the Unix-only library and executables.

**Comment by baentsch** [comment]
@evil-user If you're in a rush, please try the Windows-crossbuild again after checking out branch ["mb-fixwincrossbuild"](https://github.com/open-quantum-safe/liboqs/tree/mb-fixwincrossbuild) (and disabling SIKE as per the above) to confirm this would fix the issue for you.

**Comment by evil-user** [comment]
@baentsch i can keep going using unix only library , i can wait , thanks for guiding me i will try solutions mentioned above and update 👍

**Comment by evil-user** [comment]
i tried compiling using branch https://github.com/open-quantum-safe/liboqs/tree/mb-fixwincrossbuild and disabled sike and picnic now i got liboqs.dll thanks a lot for support.

**Comment by baentsch** [comment]
Thanks for letting me know. So it also did not work without disabling Picnic on your machine?

**Comment by evil-user** [comment]
@baentsch  yes i had to disable Picnic on my machine to make it work.

**Comment by baentsch** [comment]
@sebastinas FYI above.

**Comment by sebastinas** [comment]
@evil-user What's the error that you got for Picnic?

**Comment by evil-user** [comment]
@sebastinas  i got the following output when Picnic wasn't disabled : - 

[1/1475] Building C object src/sig/picnic/CMakeFiles/picnic.dir/external/lowmc_192_192_30.c.obj
[2/1475] Building C object src/sig/picnic/CMakeFiles/picnic.dir/external/lowmc_192_192_4.c.obj
[3/1475] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/transpose.c.obj
[4/1475] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/util.c.obj
[5/1475] Building C object src/sig/picnic/CMakeFiles/picnic.dir/external/lowmc_128_128_20.c.obj
[6/1475] Building C object src/sig/picnic/CMakeFiles/picnic.dir/external/lowmc_256_256_38.c.obj
[7/1475] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/sk_gen.c.obj
[8/1475] Building C object src/common/CMakeFiles/common.dir/sha3/xkcp_sha3x4.c.obj
[9/1475] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/pk_gen.c.obj
[10/1475] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/vec.c.obj
[11/1475] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/aes256ctr.c.obj
[12/1475] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/decrypt.c.obj
[13/1475] Building C object src/common/CMakeFiles/common.dir/common.c.obj
[14/1475] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/kem_classic_mceliece_8192128.c.obj
[15/1475] Building C object src/sig/picnic/CMakeFiles/picnic.dir/external/io.c.obj
[16/1475] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/benes.c.obj
[17/1475] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128f_vec.dir/pqclean_mceliece8192128f_vec/vec.c.obj
[18/1475] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128f_vec.dir/pqclean_mceliece8192128f_vec/transpose.c.obj
[19/1475] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128f_vec.dir/pqclean_mceliece8192128f_vec/util.c.obj
[20/1475] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/bm.c.obj
[21/1475] Building C object src/common/CMakeFiles/common.dir/aes/aes256_ni.c.obj
[22/1475] Building C object src/common/CMakeFiles/common.dir/aes/aes128_ni.c.obj
[23/1475] Building C object src/sig/picnic/CMakeFiles/picnic.dir/external/lowmc.c.obj
FAILED: src/sig/picnic/CMakeFiles/picnic.dir/external/lowmc.c.obj 
/usr/bin/x86_64-w64-mingw32-gcc -DOQS -DPICNIC_EXPORT="" -DWITH_AVX2 -DWITH_KKW -DWITH_LOWMC_128_128_20 -DWITH_LOWMC_129_129_4 -DWITH_LOWMC_192_192_30 -DWITH_LOWMC_192_192_4 -DWITH_LOWMC_255_255_4 -DWITH_LOWMC_256_256_38 -DWITH_OPT -DWITH_SSE2 -DWITH_UNRUH -DWITH_ZKBPP -Iinclude -I../src/sig/picnic/external -fvisibility=hidden   -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -Wno-maybe-uninitialized -Wno-missing-braces -std=gnu11 -MD -MT src/sig/picnic/CMakeFiles/picnic.dir/external/lowmc.c.obj -MF src/sig/picnic/CMakeFiles/picnic.dir/external/lowmc.c.obj.d -o src/sig/picnic/CMakeFiles/picnic.dir/external/lowmc.c.obj   -c ../src/sig/picnic/external/lowmc.c
../src/sig/picnic/external/lowmc.c:1157:1: error: AVX vector return without AVX enabled changes the ABI [-Werror=psabi]
 }
 ^
cc1: all warnings being treated as errors
[24/1475] Building C object src/sig/picnic/CMakeFiles/picnic.dir/external/picnic.c.obj
[25/1475] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_8192128_vec.dir/pqclean_mceliece8192128_vec/controlbits.c.obj
[26/1475] Building C object src/kem/frodokem/CMakeFiles/frodokem.dir/external/frodo640shake.c.obj
[27/1475] Building C object src/common/CMakeFiles/common.dir/aes/aes_c.c.obj
[28/1475] Building C object src/kem/frodokem/CMakeFiles/frodokem.dir/external/frodo976aes.c.obj
ninja: build stopped: subcommand failed.
