### ISSUE TITLE
Classify algorithm status

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1245]
A concrete NIST announcement date, hurray: https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/7yLIZcFOMF0/m/vn43l1tQAQAJ

Bets still accepted.... :-) Eliminating McEliece and SPHINCS+ would be a boon for our CI runtime (and the world's power-consumption-induced CO2 emissions).

**Comment by baentsch** [comment]
Well, (combatting) global warming seems to have been no major decision criterion :-(

On the bright side it seems we now can claim/document to have all [selected](https://csrc.nist.gov/Projects/post-quantum-cryptography/selected-algorithms-2022) and all [round 4](https://csrc.nist.gov/Projects/post-quantum-cryptography/round-4-submissions) algorithms. Suggestion thus to prune (post 0.7.2)

- [ ] Frodo
- [ ] NTRU
- [ ] NTRU prime
- [ ] Rainbow

**Comment by jschanck** [comment]
I suggest keeping NTRU for now. There's a footnote on page 18 of the [round 3 status report](https://nvlpubs.nist.gov/nistpubs/ir/2022/NIST.IR.8413.pdf) which says that NTRU is the backup if the patent agreements for Kyber are not finalized by end-of-year.

**Comment by dstebila** [comment]
> I suggest keeping NTRU for now. There's a footnote on page 18 of the [round 3 status report](https://nvlpubs.nist.gov/nistpubs/ir/2022/NIST.IR.8413.pdf) which says that NTRU is the backup if the patent agreements for Kyber are not finalized by end-of-year.

Yes, I had in mind that we'd probably keep NTRU around for the time being due to that footnote. In today's status meeting we didn't make any firm decisions about what to prune, instead wanting to think more over the next couple of weeks and see whether there will be a future for any of the algorithms outside of NIST, e.g. resubmission to Round 4 or interest by other governments. We might provide some configure-time options to help people select certain bundles of algorithms.

**Comment by baentsch** [comment]
Agree. So the goal for the resolution of this issue is to define and create a mechanism to build `liboqs` such as to differentiate at configure time (at least) between "standardized", "round4" and "research" algorithms, leading to different levels of (CI) testing and default inclusion in library builds. A final class comprises algorithms to be completely pruned. 

So here's a first proposal:

"standard": kyber, dilithium, falcon, sphincs
"round4": bike, classic_mceliece, hqc, sike
"research": frodo, ntru, picnic
prune: rainbow, saber, ntruprime

Comments welcome. Regarding picnic, particularly by @christianpaquin; ntru as per the above (thanks, @jschanck) and frodo (thanks, @dstebila). Who could argue for the/a different classification of the "prune" candidates? Regarding ntruprime, what about touching base with the openssh community (whether they want to retain it regardless)?

**Comment by baentsch** [comment]
> would thus be in favor of keeping ntruprime (or at least sntrup761), at least until such time as it is removed from OpenSSH.

Thanks for the proposal. To help us collect some more background to this suggestion: Did you (or are you aware of anyone that did) test interoperation between the OpenSSH-sntrup761 with https://github.com/open-quantum-safe/openssh ? Does OpenSSH use `liboqs`?

**Comment by dstebila** [comment]
> > would thus be in favor of keeping ntruprime (or at least sntrup761), at least until such time as it is removed from OpenSSH.
> 
> Thanks for the proposal. To help us collect some more background to this suggestion: Did you (or are you aware of anyone that did) test interoperation between the OpenSSH-sntrup761 with https://github.com/open-quantum-safe/openssh ? Does OpenSSH use `liboqs`?

Interop between OpenSSH and OQS-OpenSSH on sntrup761 doesn't really make sense, because OQS-OpenSSH would include OpenSSH's sntrup761 suite without alteration.  As far as I know, OpenSSH natively includes an sntrup761 implementation, rather than using liboqs'.

**Comment by baentsch** [comment]
> Interop between OpenSSH and OQS-OpenSSH on sntrup761 doesn't really make sense, because OQS-OpenSSH would include OpenSSH's sntrup761 suite without alteration. As far as I know, OpenSSH natively includes an sntrup761 implementation, rather than using liboqs'.

In that case I wonder why `liboqs` should be

> keeping ntruprime (or at least sntrup761)

**Comment by tmcqueen-materials** [comment]
So to clarify: my point was not about incorporation in OpenSSH itself because, as noted, recent versions of OpenSSH include the reference sntrup761 implementation and does not rely on liboqs to provide it. 

My point is rather about the ecosystem of software that speaks SSH but does not leverage the OpenSSH codebase, particularly custom clients and servers -- in some of those cases, liboqs is the rational plug-in provider of pqcrypto implementations. Since various long-term stable linux distributions incorporate OpenSSH 8.9 (e.g. Ubuntu 22), even if OpenSSH moves to one of the NIST "to be standardized" algorithms, sntrup761 will remain in many cases as the only available pqcrypto choices for some time.

Worst case software that relies on OpenSSH pqcrypto interop currently using liboqs can either just stick with an old version of liboqs or modified to directly use the reference implementation, but it seems wrong for a wonderful "reference toolkit" of options (i.e. liboqs) to not support it, at least until it is (mostly) phased out [I guess another way to "depreciate" that actually would mesh well with the timescales of LTSs would be to move the "prune" algorithms to "included but not built by default" in v0.8.x, and then removed in v.0.9.x]

**Comment by dstebila** [comment]
Ah, I see what you're getting at: other SSH implementations that want to interop with OpenSSH will need an implementation of strnup761, and liboqs would be a convenient source for that, speaking to keeping strnup761 in liboqs. Duly noted, let's take that under consideration. Do you know if there any other algorithms from the NTRU Prime family that are relevant?  If we can even prune it down to just strnup761 and remove code for the rest of them, that would be helpful.

**Comment by xvzcf** [comment]
I've prepared the following summary of the status of our implementations. I thought it was best placed here, but I can break it out into another issue if need be.

# KEMS

| Algorithm Name   | Update?        | Comments                                                                                                                                                                                                                                                                                 |
|:-----------------|:---------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| BIKE             | Yes            | [Implementaton](https://github.com/open-quantum-safe/liboqs/blob/main/src/kem/bike/additional_r3/README.md) corresponds to `BIKE_Spec.2020.05.03.1.pdf` spec, whereas the [latest specification](https://bikesuite.org/#spec) is `BIKE_Spec.2022.10.10.1.pdf`.                           |
| Classic McEliece | Yes            | Already noted [here](https://github.com/open-quantum-safe/liboqs/issues/1314).                                                                                                                                                                                                           |
| FrodoKEM         | No             | -                                                                                                                                                                                                                                                                                        |
| HQC              | Yes            | Implementation taken from PQClean, whose [is based on the 2020-10-01 specification](https://github.com/PQClean/PQClean/blob/master/crypto_kem/hqc-rmrs-128/META.yml#L25). Latest version is [2021/06/06](https://pqc-hqc.org/implementation.html).                                       |
| Kyber            | Might as well? | Implementation based on commit [8e00ec73035147d18b27d06048dff322f8de1f29](https://github.com/pq-crystals/kyber/commit/8e00ec73035147d18b27d06048dff322f8de1f29), there is one commit (and merge commit) after, that fixes a comment typo.                                                |
| Kyber (ARM)      | Yes            | Taken from PQClean, which is based on `neon-ntt` commit [c6ffbcd1e5590e4dddbc604fc80d2ad756485b4d](https://github.com/neon-ntt/neon-ntt/tree/c6ffbcd1e5590e4dddbc604fc80d2ad756485b4d); a more recent commit `328d80a81ea9ff1f0bb72123460fd941795f6157` seems to have relevant changes. |
| NTRU             | No             | Taken from PQClean, where its been removed. The latest update to NTRU was on [2020-10-16](https://ntru.org/index.shtml).                                                                                                                                                                 |
| NTRU-Prime       | No. Remove     | No longer in the NIST PQC competition.                                                                                                                                                                                                                                                   |
| Saber            | No. Remove     | No longer in the NIST PQC competition.                                                                                                                                                                                                                                                   |

# Signatures

| Algorithm Name           | Update?     | Comments                                                                                                                                                                                                                        |
|:-------------------------|:------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| CRYSTALS-Dilithium       | Maybe?      | Implementation based on commit [61b51a71701b8ae9f546a1e5d220e1950ed20d06](https://github.com/pq-crystals/dilithium/commit/61b51a71701b8ae9f546a1e5d220e1950ed20d06). There is one commit after which adds an additonal license. |
| CRYSTALS-Dilithium (ARM) | Yes         | Same situation as Kyber (ARM).                                                                                                                                                                                                  |
| Falcon                   | Yes         | Already noted [here](https://github.com/PQClean/PQClean/issues/464).                                                                                                                                                            |
| Picnic                   | No. Remove. | No longer in the NIST PQC competition.                                                                                                                                                                                          |
| Rainbow                  | No. Remove. | No longer in the NIST PQC competition.                                                                                                                                                                                          |
| SPHINCS+                 | Yes         | Already noted [here](https://github.com/PQClean/PQClean/issues/446).                                                                                                                                                            |

**Comment by dstebila** [comment]
Thanks @xvzcf that's really helpful! Were you able to tell which updates were implementation updates and which were algorithm updates breaking interoperability?

**Comment by xvzcf** [comment]
> Thanks @xvzcf that's really helpful! Were you able to tell which updates were implementation updates and which were algorithm updates breaking interoperability?

I did not pay particular attention to that, but I add another column to the table indicating whether that is the case.

**Comment by xvzcf** [comment]
> I did not pay particular attention to that, but I can add another column to the table indicating whether that is the case.

Done.

**Comment by dstebila** [comment]
Thanks very much, Goutam! Let's discuss prioritizing these in tomorrow's meeting.

**Comment by bhess** [comment]
Thanks @xvzcf for the list! I opened a PR with the Dilithium/Kyber update: #1316.

**Comment by christianpaquin** [comment]
Just to confirm that Picnic is not part of Round 4; it can be removed as well.

**Comment by xvzcf** [comment]
In light of https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/4MBurXr58Rs/m/WX3u_lU_AQAJ, shall we remove NTRU as well?

**Comment by dstebila** [comment]
> In light of https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/4MBurXr58Rs/m/WX3u_lU_AQAJ, shall we remove NTRU as well?

@jschanck Any comments before we take a decision?  Are there any plans for NTRU to be considered for standardization elsewhere?

**Comment by jschanck** [comment]
Not that I'm aware of. I think it's safe to remove it.

**Comment by baentsch** [comment]
> In light of https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/4MBurXr58Rs/m/WX3u_lU_AQAJ, shall we remove NTRU as well?

In light of the same statement, shall we consider removing SPHINCS+ robust' variant, too? It would save substantial amounts of (also CI) computing/time.

**Comment by dstebila** [comment]
> > In light of https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/4MBurXr58Rs/m/WX3u_lU_AQAJ, shall we remove NTRU as well?
> 
> In light of the same statement, shall we consider removing SPHINCS+ robust' variant, too? It would save substantial amounts of (also CI) computing/time.

That makes sense too.  Although I can't find in that email chain where NIST mentioned the specific SPHINCS+ variants they are keeping, perhaps I missed it.

**Comment by baentsch** [comment]
At the very first mail in the chain, "Moody, Dustin (Fed)" writes

> We plan to include the simple (and NOT the robust) version.

**Comment by baentsch** [comment]
There's more algorithms as "not really favoured" on that list (e.g., Kyber/Dilithium AES variants)... We once discussed about creating a mechanism to build a library with only the "base set" (true "standard" algs) and an "extended research" set? We have something similar in the downstreams with the "enabled" flag (unset for various algorithms). What about the same in liboqs? This would facilitate a smaller (and faster) build for the "select few" and a larger (and slower) build for "all experimental algs". Worth its own issue? But then again, this could be as simple as a `cmake` variable setting a specific set of `OQS_ENABLE_XYZ` defines.

**Comment by dstebila** [comment]
Hmmm... I had thought that the extended research set would comprise things in Round 4 and the new signature call for proposals, with the base set being things selected for standardization.  I guess we could consider keeping the variants in the extended set, but are they really still of interest?

**Comment by loganaden** [comment]
It appears that the industry still trusts NTRU prime despite its status with NIST. I've opened an issue here https://github.com/open-quantum-safe/liboqs/issues/1329. Removing NTRU prime breaks interop between py-asyncssh and OpenSSH. This is an issue in my humble opinion. There is also a PR here: https://github.com/open-quantum-safe/liboqs/pull/1328

**Comment by baentsch** [comment]
> Removing NTRU prime breaks interop between asyncssh and OpenSSH. 

Thanks for the feedback -- very much in line with @dstebila 's [comment](https://github.com/open-quantum-safe/liboqs/issues/1245#issuecomment-1223375957)

> Ah, I see what you're getting at: other SSH implementations that want to interop with OpenSSH will need an implementation of strnup761, and liboqs would be a convenient source for that, speaking to keeping strnup761 in liboqs. Duly noted, let's take that under consideration. Do you know if there any other algorithms from the NTRU Prime family that are relevant? If we can even prune it down to just strnup761 and remove code for the rest of them, that would be helpful.

#1329 adds all NTRUPrime algs back, though -- would it be possible/sensible/sufficient to modify the PR such that it only brings back the algorithm(s) needed for OpenSSH?

**Comment by loganaden** [comment]
@baentsch sure. we will work on updating the PR.

**Comment by xvzcf** [comment]
Shall I convert this into a discussion? Seems like this is turning into one anyway ...

**Comment by loganaden** [comment]
@xvzcf although we are focused mostly on integrating pq into different internet protocols, we would be happy to maintain NTRU Prime and improve it. However, we would need some initial help :-)

**Comment by baentsch** [comment]
All algorithms to-be-removed are gone and all required updates are separately tracked. Thus closing this issue.
