### ISSUE TITLE
Unable to compile liboqs as shared library in Openbsd 7.1

### ISSUE THREAD

**Issue by evil-user** [open-quantum-safe/liboqs#1246]
I am following documentation from https://github.com/open-quantum-safe/liboqs/wiki/Platform-specific-notes-for-building-liboqs#cross-compiling and https://openquantumsafe.org/liboqs/getting-started.html.

i have installed all required dependencies but i get the following error.

[1/11] Linking C executable tests/speed_sig
FAILED: tests/speed_sig 
: && /usr/bin/cc   tests/CMakeFiles/speed_sig.dir/speed_sig.c.o -o tests/speed_sig -L/root/liboqs/build/lib -Wl,-z,origin,-rpath,/root/liboqs/build/lib  -lliboqs.so.0.7.2-dev  -lm  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib && :
ld: error: unable to find library -lliboqs.so.0.7.2-dev
cc: error: linker command failed with exit code 1 (use -v to see invocation)
[2/11] Linking C executable tests/test_sig_mem
FAILED: tests/test_sig_mem 
: && /usr/bin/cc   tests/CMakeFiles/test_sig_mem.dir/test_sig_mem.c.o -o tests/test_sig_mem -L/root/liboqs/build/lib -Wl,-z,origin,-rpath,/root/liboqs/build/lib  -lliboqs.so.0.7.2-dev  -lm  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib && :
ld: error: unable to find library -lliboqs.so.0.7.2-dev
cc: error: linker command failed with exit code 1 (use -v to see invocation)
[3/11] Linking C executable tests/test_kem
FAILED: tests/test_kem 
: && /usr/bin/cc   tests/CMakeFiles/test_kem.dir/test_kem.c.o -o tests/test_kem -L/root/liboqs/build/lib -Wl,-z,origin,-rpath,/root/liboqs/build/lib  -lliboqs.so.0.7.2-dev  -lm  -pthread  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib && :
ld: error: unable to find library -lliboqs.so.0.7.2-dev
cc: error: linker command failed with exit code 1 (use -v to see invocation)
[4/11] Linking C executable tests/example_sig
FAILED: tests/example_sig 
: && /usr/bin/cc   tests/CMakeFiles/example_sig.dir/example_sig.c.o -o tests/example_sig -L/root/liboqs/build/lib -Wl,-z,origin,-rpath,/root/liboqs/build/lib  -lliboqs.so.0.7.2-dev  -lm  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib && :
ld: error: unable to find library -lliboqs.so.0.7.2-dev
cc: error: linker command failed with exit code 1 (use -v to see invocation)
[5/11] Linking C executable tests/dump_alg_info
FAILED: tests/dump_alg_info 
: && /usr/bin/cc   tests/CMakeFiles/dump_alg_info.dir/dump_alg_info.c.o -o tests/dump_alg_info -L/root/liboqs/build/lib -Wl,-z,origin,-rpath,/root/liboqs/build/lib  -lliboqs.so.0.7.2-dev  -lm  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib && :
ld: error: unable to find library -lliboqs.so.0.7.2-dev
cc: error: linker command failed with exit code 1 (use -v to see invocation)
[6/11] Linking C executable tests/test_sig
FAILED: tests/test_sig 
: && /usr/bin/cc   tests/CMakeFiles/test_sig.dir/test_sig.c.o -o tests/test_sig -L/root/liboqs/build/lib -Wl,-z,origin,-rpath,/root/liboqs/build/lib  -lliboqs.so.0.7.2-dev  -lm  -pthread  -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib && :
ld: error: unable to find library -lliboqs.so.0.7.2-dev
cc: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

I can provide any additional logs if required i am currently using openbsd 7.1 as root user to test liboqs

**Comment by baentsch** [comment]
The library name as given on the command line looks suspicious: Can you manually try linking with this command instead (giving a more standard reference to the (shared lib) oqs: 

```
/usr/bin/cc tests/CMakeFiles/test_sig.dir/test_sig.c.o -o tests/test_sig -L/root/liboqs/build/lib -Wl,-z,origin,-rpath,/root/liboqs/build/lib -loqs -lm -pthread -Wl,-rpath-link,/usr/X11R6/lib:/usr/local/lib

``` 
? Please also confirm that `liboqs.so` has indeed been properly built into `/root/liboqs/build/lib`. Again, I don't have an OpenBSD system at my disposal to reproduce, sorry.
