### ISSUE TITLE
Picnic memory safety issues

### ISSUE THREAD

**Issue by thomwiggers** [open-quantum-safe/liboqs#1253]
I don't run windows, so I will have a hard time trying to reproduce this, but it seems as if Picnic is causing memory access violations on MSVC in the Rust wrapper. See the failed builds on https://github.com/open-quantum-safe/liboqs-rust/pull/146 and https://github.com/open-quantum-safe/liboqs-rust/pull/147 and https://github.com/open-quantum-safe/liboqs-rust/pull/149.

**Comment by baentsch** [comment]
@thomwiggers : Is there anything more than in https://github.com/open-quantum-safe/liboqs-rust/runs/7301430054?check_suite_focus=true to (try to) understand what's going wrong? @sebastinas FYI... Do you have a windows environment to check this apparent regression? @christianpaquin : Could you help (reproduce/fix) this apparently Windows-specific issue?

**Comment by thomwiggers** [comment]
From CI, not really. What I would do to try to get a more usable trace, is run the test suite single-threaded (to isolate the failing test, and check if it still happens) and then run it through Valgrind.

**Comment by thomwiggers** [comment]
oh, but Valgrind doesn't have Windows support...

**Comment by thomwiggers** [comment]
I've got a Windows VM running somewhere and it's definitely crashing in PicnicL1Fs. Note that the below build doesn't require OpenSSL and disables all other algorithms.

```
cargo test --no-default-features --features picnic -- --test-threads 1  PicnicL1Fs
```
![image](https://user-images.githubusercontent.com/974662/181200219-9c6bc233-c005-4129-b495-023a865274c4.png)

**Comment by baentsch** [comment]
Thanks very much @thomwiggers for these additional infos. @sebastinas FYI above.

**Comment by thomwiggers** [comment]
I think I've managed to collect some dump files. I'll see if I can figure out some more.

**Comment by thomwiggers** [comment]
Got to love how the debugger for the Windows 10 SDK is still a Windows 95 program at heart.

![image](https://user-images.githubusercontent.com/974662/181204800-0c2b32f7-78d2-4a58-b193-2463a27ba383.png)


Seems as if it's in ``picnic_mzd_xor_s256_128``.

![image](https://user-images.githubusercontent.com/974662/181205961-0f48894d-f567-4013-915f-debc650a7e60.png)
This stack trace is a bit suspect, why does it mention PicnicL5....??????!?

**Comment by thomwiggers** [comment]
[picnic-crash-investigation.zip](https://github.com/open-quantum-safe/liboqs/files/9196803/picnic-crash-investigation.zip)

I've attached the unit test binary (you can execute it as `oqs-<bla>.exe --test-threads 1 PicnicL1Fs::test_signing` if you only want to run the offending code). The zip file also contains a memory dump at the moment of the crash, obtained using `procdump -ma`.

**Comment by baentsch** [comment]
@dstebila : Given we define 0.7.2 as a "security" release, shouldn't this issue become part of the milestone?

**Comment by sebastinas** [comment]
I have reproduced the issue locally. I'll update the bug as soon as I have a fix.
