### ISSUE TITLE
Compiling on Windows ARM64 / ARMv7 with OQS_DIST_BUILD fails

### ISSUE THREAD

**Issue by darktohka** [open-quantum-safe/liboqs#1264]
Hello!

I am trying to compile liboqs for Windows ARM64 and ARMv7 with OQS_DIST_BUILD enabled, but both fail because the `src/common/common.c` does not provide implementations for ARM64/ARMv7 CPU feature detection on Windows. The build fails by failing to find the "<sys/auxv.h>" header, which only exists on Linux.

**Comment by baentsch** [comment]
Thanks for the bug report. Indeed I'm not sure we have someone in the team using an ARM-based Windows. Is there a specific test (ideally CI) environment that you could point to for us to debug & test this? Could you possibly contribute such functionality?
