### ISSUE TITLE
Remove SIDH/SIKE

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1268]
As per https://eprint.iacr.org/2022/975

**Comment by dstebila** [comment]
I emailed with @plonga and we've agreed that SIDH and SIKE should, unfortunately, be removed. I think it would be appropriate to include that in the 0.7.2 release.

**Comment by baentsch** [comment]
ACK. Shall #1267 then be re-based after this closes? I'd volunteer to update the downstream apps when you have a branch/PR ready for this.

**Comment by dstebila** [comment]
> ACK. Shall #1267 then be re-based after this closes? 

That probably makes sense.

> I'd volunteer to update the downstream apps when you have a branch/PR ready for this.

Thanks.  I'll try to pull something together today for this.
