### ISSUE TITLE
cmake file installed in wrong location: /usr/lib64/cmake/usr/lib64oqs/liboqsConfig.cmake

### ISSUE THREAD

**Issue by vt-alt** [open-quantum-safe/liboqs#1277]
I tested `0.7.2-rc1` and cmake files, such as `liboqsConfig.cmake`, are installed in `/usr/lib64/cmake/usr/lib64oqs`:
```
+ DESTDIR=/usr/src/tmp/liboqs-buildroot
+ /usr/bin/ninja -j20 install -C build
...
-- Installing: /usr/src/tmp/liboqs-buildroot/usr/lib64/cmake/usr/lib64oqs/liboqsConfig.cmake
-- Installing: /usr/src/tmp/liboqs-buildroot/usr/lib64/cmake/usr/lib64oqs/liboqsConfigVersion.cmake
...
-- Installing: /usr/src/tmp/liboqs-buildroot/usr/lib64/cmake/usr/lib64oqs/liboqsTargets.cmake
-- Installing: /usr/src/tmp/liboqs-buildroot/usr/lib64/cmake/usr/lib64oqs/liboqsTargets-relwithdebinfo.cmake
```
Previously they are correctly installed in `/usr/lib64/cmake/liboqs/liboqsConfig.cmake` under `DESTDIR`.
It seems that `liboqs` is expanded there to `/usr/lib64`.

**Comment by dstebila** [comment]
> Previously they are correctly installed in `/usr/lib64/cmake/liboqs/liboqsConfig.cmake` under `DESTDIR`. It seems that `liboqs` is expanded there to `/usr/lib64`.

"Previously" meaning version 0.7.1, or something more recent? I don't know enough about CMake to know how to solve this other than using git bisect to try to find when the behaviour changed.

**Comment by baentsch** [comment]
As far as I remember, the "proper way" to install `liboqs` for `cmake`-inclusion was created with #1191, i.e., long after 0.7.1... Glancing over the files changed (since) then also didn't flag anything immediately suspicious... Some more digging required... As stated by @dstebila any indication as to which commit was the last one working for you would be very helpful...

**Comment by baentsch** [comment]
When trying to reproduce your run, I changed this command:
> + DESTDIR=/usr/src/tmp/liboqs-buildroot
> + /usr/bin/ninja -j20 install -C build

to `DESTDIR=/tmp/liboqs-buildroot ninja install` and ran that inside `build` (to avoid messing with '/usr'): OK?

So the question to you, @vt-alt : How did you generate the ninja setup, i.e., which parameters did you pass to `cmake`? When trying `cmake -GNinja -DCMAKE_INSTALL_PREFIX=/tmp/usr/lib64/cmake/liboqs ..` (again within `build`), a plain `ninja install` placed `liboqsConfig.cmake` as expected into `/tmp/usr/lib64/cmake/liboqs/lib/cmake/liboqs/` (or into `/tmp/liboqs-buildroot/tmp/usr/lib64/cmake/liboqs/lib/cmake/liboqs/` when running the DESTDIR-prefixed install.

-> Is any of this not as you'd expect it, @vt-alt ? Any further information for us to reproduce your setup? When trying the above, I used Linux Mint 20.1., ninja 1.10.0 and cmake 3.16.3 (and liboqs-0.7.2-rc1).

**Comment by vt-alt** [comment]
Sorry for a delay.

> "Previously" meaning version 0.7.1, or something more recent?

`0.7.1` was installing correctly.

> I changed this command:

Yes, sorry, it was `DESTDIR=/tmp/liboqs-buildroot ninja ... install ` but I was just copy pasting bash trace log (with `set -x` which `rpmbuild` shows), where it's shown as separate commands.

> So the question to you, @vt-alt : How did you generate the ninja setup, i.e., which parameters did you pass to cmake? 

Following you questions I found mistake in our build script. We had a line `sed -i '\!DESTINATION!s!lib!%_libdir!' src/CMakeLists.txt` which was intended to relocate `/usr/lib/cmake/liboqs` to `/usr/lib64/cmake/liboqs` (appropriate in our distribution) by replacing only first occurrence of `lib`, but in newer version of liboqs `src/CMakeLists.txt` introduced `CMAKE_INSTALL_LIBDIR` and `sed` replaces incorrectly second occurrence of `lib` causing such install error.

I am very sorry for the false alarm!

**Comment by vt-alt** [comment]
Just to confirm, when I removed that `sed` line from our build script it how installs correctly to `/usr/lib64/cmake/liboqs`.
Thanks for the help!
