### ISSUE TITLE
Travis is failing

### ISSUE THREAD

**Issue by tlepoint** [open-quantum-safe/liboqs#128]
Because `libm4ri-dev` does not exist, introduced in [3aaa26aacee5e332a517f2de6436fe1c665e0785](https://github.com/open-quantum-safe/liboqs/commit/3aaa26aacee5e332a517f2de6436fe1c665e0785)

@smashra It is important to only do PR and to not directly commit to master, otherwise we do not catch this.
@dstebila: is it possible to forbid commits to master and force to go through PR?

**Comment by dstebila** [comment]
Good suggest Tancrede.  I didn't know this was an option but I've now found it in the Github configuration and turned it on.  If I interpret the option correctly, master now prevent "force pushes" and instead requires code to come on a pull request.  I think it might also demand at least one review on every PR before it can be merged, but I am not certain about that option yet -- we shall see!

**Comment by tlepoint** [comment]
Fixed by #134.
