### ISSUE TITLE
Signature algorithm x not enabled

### ISSUE THREAD

**Issue by alexandra-buzatoiu** [open-quantum-safe/liboqs#1289]
I am trying to understand and run the liboqs tests. I have to mention that I have liboqs and the oqs-opensll fork. I have tested the signature and kem examples from the github and I get this output which I find positive.

└─$ ./example_sig                      
[example_stack] OQS_SIG_dilithium_2 operations completed.
[example_heap]  OQS_SIG_dilithium_2 operations completed.

As these examples use dilithium2, I think as they work, the algorithm should be enabled. Anyways, when I try to compile and run test_sig.c, test_sig_mem.c, when executing the resulting executable file, I get this message: 

┌──(kali㉿kali)-[~/task5/liboqs/build/tests]
└─$ ./test_sig_mem 0 Dilithium2
Configuration info
==================
Target platform:  x86_64-Linux-5.16.0-kali7-amd64
Compiler:         gcc (11.3.0)
Compile options:  [-march=native;-Werror;-Wall;-Wextra;-Wpedantic;-Wstrict-prototypes;-Wshadow;-Wformat=2;-Wfloat-equal;-Wwrite-strings;-O3;-fomit-frame-pointer;-fdata-sections;-ffunction-sections;-Wl,--gc-sections;-Wbad-function-cast]
OQS version:      0.7.2-rc1
Git commit:       3cf9849cc43545ad7fdeb3092a90f94ff1881680
OpenSSL enabled:  Yes (OpenSSL 3.0.4 21 Jun 2022)
AES:              NI
SHA-2:            OpenSSL
SHA-3:            C
OQS build flags:  OQS_OPT_TARGET=auto CMAKE_BUILD_TYPE=Release 
CPU exts compile-time:  AES AVX PCLMULQDQ POPCNT SSE SSE2 SSE3

Signature algorithm 0 not enabled!

I have even try to pass as an argv OQS_SIG_alg_dilithium_3, as in the example_sig.c: sig = OQS_SIG_new(OQS_SIG_alg_dilithium_3);

I have seen that there are some flags for cmake command https://github.com/open-quantum-safe/liboqs/wiki/Customizing-liboqs#OQS_ENABLE_KEM_<ALG>/OQS_ENABLE_SIG_<ALG>
The solution would be to install everything from the scratch and mention all the flags at cmake? Is there another way? 
Thank you in advance!

**Comment by baentsch** [comment]
> ./test_sig_mem 0 Dilithium2

is incorrect: The two parameters must be switched: `./test_sig_mem Dilithium2 0` works
