### ISSUE TITLE
Determining which port to use on test.quantumsafe.org

### ISSUE THREAD

**Issue by expressvpn-pete-m** [open-quantum-safe/liboqs#1291]
Hiya,

WolfSSL uses `liboqs` for its post quantum support, and to take advantage of this, I've added support for `liboqs` in my Rust crate `wolfssl-sys`. It works really well!

I do have one issue though...

I have an example app that ships as part of the Rust crate that demonstrates the library in operation. The example connects to `test.openquantumsafe.org` on port `6051`. At the time of writing, this was the port used for the equivalent of `WOLFSSL_P521_KYBER_LEVEL5`. Since then though (I guess it was restarted?) the assigned port numbers have changed, so this example no longer works.

I was wondering, is there a way to programmatically find the port for a given combo without having to parse the table  on https://test.openquantumsafe.org/ ?

Thanks!

**Comment by baentsch** [comment]
>  is there a way to programmatically find the port for a given combo

Yes: 

> For automated testing, a JSON file encoding all available SIG/KEM combinations and the respective ports where they can be found is [available for download here](https://test.openquantumsafe.org/assignments.json). We explicitly want to warn that algorithm/port combinations are subject to change. Be sure to download the most current JSON file before testing.


>

**Comment by expressvpn-pete-m** [comment]
Thanks for taking the time to answer and apologies for somehow missing that on the test page!

I'll add support to check for the correct port as part of the example application so that it will always find the correct one. Really excited to be able to leverage `liboqs`!
