### ISSUE TITLE
Error when building liboqs on ARM (armeabi-v7a, Android 11, root)

### ISSUE THREAD

**Issue by ilovevkapi** [open-quantum-safe/liboqs#1296]
Hello. I need to build liboqs on Android to develop a command-line HTTPS client with post-quantum cryptography support. I followed all instructions for building on Linux (because Android is actually Linux distributive). But got a compiling error at `ninja` step.
Here is what i did, and what I saw in terminal:

0. I have used [Termux](https://github.com/termux/termux-app?) as Linux-environment for Android.
1. I have ran `apt install astyle cmake gcc ninja-build libssl-dev python3-pytest python3-pytest-xdist unzip xsltproc doxygen graphviz python3-yaml valgrind`, output was: 
```
Checking availability of current mirror: ok
...
E:  Unable to locate package astyle
E:  Package gcc has no installation candidate, use libllvm instead
E:  Package ninja-build has no installation candidate, use ninja instead
E:  Package libssl-dev has no installation candidate, use openssl instead
E:  Package python3-pytest has no installation candidate, use 'pip install pytest' instead
E:  Package python3-pytest-xdist has no installation candidate, use 'pip install pytest-xdist' instead
E:  Package python3-yaml has no installation candidate, use 'pip install pyYAML' instead
```
Finally, I have installed all these packages manually, except for `astyle, graphviz`. (I haven't found any ARM-versions of them).
This is what happened after:

2. Did `git clone https://github.com/open-quantum-safe/liboqs.git`. Output was OK.
3. Did `cd liboqs && mkdir build && cd build`. OK too.
4. Did `cmake -GNinja ..` Output was:
```
-- The C compiler identification is Clang 14.0.6
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /data/data/com.termux/files/usr/bin/cc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning at .CMake/compiler_opts.cmake:44 (message):
  Setting OQS_OPT_TARGET=AUTO may not produce optimized code on this system.
Call Stack (most recent call first):
  CMakeLists.txt:111 (include)


-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Found OpenSSL: /data/data/com.termux/files/usr/lib/libcrypto.so (found suitable version "3.0.3", minimum required is "1.1.1")
-- Found Doxygen: /data/data/com.termux/files/usr/bin/doxygen (found version "1.9.4") found components: doxygen missing components: dot
-- Configuring done
-- Generating done
-- Build files have been written to: /data/data/com.termux/files/home/sys/liboqs/build
```
I think its okay, like previous.

5. Bulding with `ninja`, error is here, while processing "common.c.o" by `ninja`. Of course, full output:
```
~/sys/liboqs/build $ sudo ninja
[1/1067] Building C object src/common/CMakeFiles/common.dir/common.c.o
FAILED: src/common/CMakeFiles/common.dir/common.c.o
/data/data/com.termux/files/usr/bin/cc -I/data/data/com.termux/files/home/sys/liboqs/build/include -O2 -g -DNDEBUG -fPIC -fvisibility=hidden -Werror -Wall -Wextra -Wpedantic -Wno-unused-command-line-argument -g3 -fno-omit-frame-pointer -Wbad-function-cast -Wcast-qual -Wnarrowing -Wconversion -std=gnu11 -MD -MT src/common/CMakeFiles/common.dir/common.c.o -MF src/common/CMakeFiles/common.dir/common.c.o.d -o src/common/CMakeFiles/common.dir/common.c.o -c /data/data/com.termux/files/home/sys/liboqs/src/common/common.c
/data/data/com.termux/files/home/sys/liboqs/src/common/common.c:251:9: error: implicitly declaring library function 'aligned_alloc' with type 'void *(unsigned int, unsigned int)' [-Werror,-Wimplicit-function-declaration]
        return aligned_alloc(alignment, size);
               ^
/data/data/com.termux/files/home/sys/liboqs/src/common/common.c:251:9: note: include the header <stdlib.h> or explicitly provide a declaration for 'aligned_alloc'
1 error generated.
[10/1067] Building C object src/co...eFiles/common.dir/aes/aes_ossl.c.
ninja: build stopped: subcommand failed.
```

Please help me to properly compile the library, if you understand where is the problem and how to do it.

**Comment by baentsch** [comment]
Sorry, I don't have Android experience... But this looks related to #1072: Did you already review that discussion?

What about the suggestions at https://stackoverflow.com/questions/67044851/android-ndk-build-error-undefined-symbol-aligned-alloc ?

**Comment by ilovevkapi** [comment]
> Sorry, I don't have Android experience... But this looks related to #1072: Did you already review that discussion?
> 
> What about the suggestions at https://stackoverflow.com/questions/67044851/android-ndk-build-error-undefined-symbol-aligned-alloc ?

I tried, but it didn't work. When I specify C++ version to 17, I'm still getting the same error. Arm compiler doesn't know what is aligned_alloc(), but why...

**Comment by ilovevkapi** [comment]
> Sorry, I don't have Android experience...

Android is generally like Linux, I think the problem is in the ARM architecture, not operating system

**Comment by ilovevkapi** [comment]
> . But this looks related to #1072: Did you already review that discussion?

Error is the same, but #1072 is about cross-compiling FOR Android, on Linux. I am trying to direct compile liboqs ON Android.

**Comment by baentsch** [comment]
>  I am trying to direct compile liboqs ON Android.

OK, then the headers should be all there: Then what was the result when you followed the suggestion from the error message

> /data/data/com.termux/files/home/sys/liboqs/src/common/common.c:251:9: note: include the header <stdlib.h> or explicitly provide a declaration for 'aligned_alloc'

? Is this function not present in _any_ system include on your build machine?

**Comment by ilovevkapi** [comment]
> OK, then the headers should be all there

Already done, Linux kernel on my Android is `4.19.127-g171183e-dirty`.


> Then what was the result when you followed the suggestion from the error message

If you mean adding `#include <stdlib.h>` to C-file "common.c", I already tried it. The same error remained.


> ? Is this function not present in _any_ system include on your build machine?

_(If I got it correctly)_ On Linux PC with Intel x64 processor, the build succeeds. But not on ARM devices.

**Comment by baentsch** [comment]
> (If I got it correctly) When on Linux PC with Intel x64 processor, the build succeeds. But not on ARM devices. And not cross-compiling.

Hmm -- after googling some more, I wonder whether this gives the answer: https://github.com/android/ndk/issues/1339#issuecomment-676811636 :

> You can't use aligned_alloc directly unless you have minSdkVersion 28 or higher. 

-> what is your SDK version?

**Comment by ilovevkapi** [comment]
> -> what is your SDK version?

31


> Hmm -- after googling some more, I wonder whether this gives the answer: [android/ndk#1339 (comment)](https://github.com/android/ndk/issues/1339#issuecomment-676811636)

Thanks, I have edited common.c file, replaced function aligned_alloc() with memalloc(). Now the `ninja` successfully passes the build of common.c, but error at element 35. Output was:
```
~/sys/liboqs/build $ sudo ninja
[27/1067] Building C object src/si...iles/picnic.dir/external/lowmc.c.
FAILED: src/sig/picnic/CMakeFiles/picnic.dir/external/lowmc.c.o
/data/data/com.termux/files/usr/bin/cc -DOQS -DPICNIC_EXPORT="" -DWITH_KKW -DWITH_LOWMC_128_128_20 -DWITH_LOWMC_129_129_4 -DWITH_LOWMC_192_192_30 -DWITH_LOWMC_192_192_4 -DWITH_LOWMC_255_255_4 -DWITH_LOWMC_256_256_38 -DWITH_NEON -DWITH_OPT -DWITH_UNRUH -DWITH_ZKBPP -I/data/data/com.termux/files/home/sys/liboqs/build/include -I/data/data/com.termux/files/home/sys/liboqs/src/sig/picnic/external -O2 -g -DNDEBUG -fPIC -fvisibility=hidden -Werror -Wall -Wextra -Wpedantic -Wno-unused-command-line-argument -g3 -fno-omit-frame-pointer -Wno-missing-braces -Wno-unguarded-availability-new -std=gnu11 -MD -MT src/sig/picnic/CMakeFiles/picnic.dir/external/lowmc.c.o -MF src/sig/picnic/CMakeFiles/picnic.dir/external/lowmc.c.o.d -o src/sig/picnic/CMakeFiles/picnic.dir/external/lowmc.c.o -c /data/data/com.termux/files/home/sys/liboqs/src/sig/picnic/external/lowmc.c
/data/data/com.termux/files/home/sys/liboqs/src/sig/picnic/external/lowmc.c:781:28: error: use of undeclared identifier 'CPU_SUPPORTS_NEON'
  if (CPU_SUPPORTS_SSE2 || CPU_SUPPORTS_NEON) {
                           ^
/data/data/com.termux/files/home/sys/liboqs/src/sig/picnic/external/lowmc.c:1029:28: error: use of undeclared identifier 'CPU_SUPPORTS_NEON'
  if (CPU_SUPPORTS_SSE2 || CPU_SUPPORTS_NEON) {
                           ^
/data/data/com.termux/files/home/sys/liboqs/src/sig/picnic/external/lowmc.c:1140:28: error: use of undeclared identifier 'CPU_SUPPORTS_NEON'
  if (CPU_SUPPORTS_SSE2 || CPU_SUPPORTS_NEON) {
                           ^
3 errors generated.
[35/1067] Building C object src/si.../picnic.dir/external/mpc_lowmc.c.
FAILED: src/sig/picnic/CMakeFiles/picnic.dir/external/mpc_lowmc.c.o
/data/data/com.termux/files/usr/bin/cc -DOQS -DPICNIC_EXPORT="" -DWITH_KKW -DWITH_LOWMC_128_128_20 -DWITH_LOWMC_129_129_4 -DWITH_LOWMC_192_192_30 -DWITH_LOWMC_192_192_4 -DWITH_LOWMC_255_255_4 -DWITH_LOWMC_256_256_38 -DWITH_NEON -DWITH_OPT -DWITH_UNRUH -DWITH_ZKBPP -I/data/data/com.termux/files/home/sys/liboqs/build/include -I/data/data/com.termux/files/home/sys/liboqs/src/sig/picnic/external -O2 -g -DNDEBUG -fPIC -fvisibility=hidden -Werror -Wall -Wextra -Wpedantic -Wno-unused-command-line-argument -g3 -fno-omit-frame-pointer -Wno-missing-braces -Wno-unguarded-availability-new -std=gnu11 -MD -MT src/sig/picnic/CMakeFiles/picnic.dir/external/mpc_lowmc.c.o -MF src/sig/picnic/CMakeFiles/picnic.dir/external/mpc_lowmc.c.o.d -o src/sig/picnic/CMakeFiles/picnic.dir/external/mpc_lowmc.c.o -c /data/data/com.termux/files/home/sys/liboqs/src/sig/picnic/external/mpc_lowmc.c
/data/data/com.termux/files/home/sys/liboqs/src/sig/picnic/external/mpc_lowmc.c:1043:28: error: use of undeclared identifier 'CPU_SUPPORTS_NEON'
  if (CPU_SUPPORTS_SSE2 || CPU_SUPPORTS_NEON) {
                           ^
/data/data/com.termux/files/home/sys/liboqs/src/sig/picnic/external/mpc_lowmc.c:1158:28: error: use of undeclared identifier 'CPU_SUPPORTS_NEON'
  if (CPU_SUPPORTS_SSE2 || CPU_SUPPORTS_NEON) {
                           ^
2 errors generated.
[36/1067] Building C object src/co...lain-64bits/KeccakP-1600-opt64.c.
ninja: build stopped: subcommand failed.
```
I think I should get rid of this `if (CPU_SUPPORTS_NEON)` etc., by replacing it with `if (1 == 2)`.
Now im trying to do this.

**Comment by baentsch** [comment]
> Thanks, I have edited common.c file, replaced function aligned_alloc() with memalign().

Good to hear: Looks like a #define for aligned_malloc to `memalign` may be a general solution if `__ANDROID__` is defined.

> I think I should get rid of this if (CPU_SUPPORTS_NEON) etc., by replacing it with if (1 == 2).

Yes: Simply defining CPU_SUPPORTS_NEON by a suitable ANDROID- and ARM- "guarded #ifdef" to minimize the code change should let you get around this.

> Now im trying to do this.

Very good -- if you're successful, please consider a PR for others to benefit from this work.

**Comment by ilovevkapi** [comment]
> if you're successful

Today, I continued to do this. Edited 29 files, and then `ninja` builded 482 objects with success, but then new error occurred. I don't know how it can be fixed here. `ninja` output:
```
~/.../liboqs/build $ sudo ninja
[482/1067] Building C object...lean_sntrup653_clean/kem.c.
FAILED: src/kem/ntruprime/CMakeFiles/ntruprime_sntrup653_clean.dir/pqclean_sntrup653_clean/kem.c.o
/data/data/com.termux/files/usr/bin/cc  -I/data/data/com.termux/files/home/auto/liboqs/build/include -I/data/data/com.termux/files/home/auto/liboqs/src/kem/ntruprime/pqclean_sntrup653_clean -I/data/data/com.termux/files/home/auto/liboqs/src/common/pqclean_shims -O2 -g -DNDEBUG -fPIC -fvisibility=hidden -Werror -Wall -Wextra -Wpedantic -Wno-unused-command-line-argument -g3 -fno-omit-frame-pointer -std=gnu11 -MD -MT src/kem/ntruprime/CMakeFiles/ntruprime_sntrup653_clean.dir/pqclean_sntrup653_clean/kem.c.o -MF src/kem/ntruprime/CMakeFiles/ntruprime_sntrup653_clean.dir/pqclean_sntrup653_clean/kem.c.o.d -o src/kem/ntruprime/CMakeFiles/ntruprime_sntrup653_clean.dir/pqclean_sntrup653_clean/kem.c.o -c /data/data/com.termux/files/home/auto/liboqs/src/kem/ntruprime/pqclean_sntrup653_clean/kem.c
In file included from /data/data/com.termux/files/home/auto/liboqs/src/kem/ntruprime/pqclean_sntrup653_clean/kem.c:5:
In file included from /data/data/com.termux/files/home/auto/liboqs/src/common/pqclean_shims/randombytes.h:6:
In file included from /data/data/com.termux/files/home/auto/liboqs/build/include/oqs/rand.h:15:
In file included from /data/data/com.termux/files/home/auto/liboqs/build/include/oqs/common.h:14:
In file included from /data/data/com.termux/files/usr/include/stdlib.h:34:
In file included from /data/data/com.termux/files/usr/include/malloc.h:30:
/data/data/com.termux/files/usr/include/stdio.h:388:17: error: expected ')'
void free(void* p);
                ^
/data/data/com.termux/files/home/auto/liboqs/src/kem/ntruprime/pqclean_sntrup653_clean/params.h:31:11: note: expanded from macro 'p'
#define p 653
          ^
/data/data/com.termux/files/usr/include/stdio.h:388:10: note: to match this '('
void free(void* p);
         ^
/data/data/com.termux/files/usr/include/stdio.h:391:6: error: expected identifier or '('
        int p = getpid();
            ^
/data/data/com.termux/files/home/auto/liboqs/src/kem/ntruprime/pqclean_sntrup653_clean/params.h:31:11: note: expanded from macro 'p'
#define p 653
          ^
2 errors generated.
[491/1067] Building C object...4bits/KeccakP-1600-opt64.c.
ninja: build stopped: subcommand failed.
```
I tried to edit .../files/usr/include/stdio.h at line 388, adding ")" in various places, but it didn't help.

**Comment by dstebila** [comment]
You added a #include, right? Try adding that #include before all the other headers, rather than after.

**Comment by ilovevkapi** [comment]
> You added a #include, right? Try adding that #include before all the other headers, rather than after.

The issue with "CPU_SUPPORTS_NEON" was already solved, by batch-adding a line "int CPU_SUPPORTS_NEON = 0;" to All C-files.
It's all that I did. I didn't add any "#include" strings to files, etc..

**Comment by baentsch** [comment]
Can I ask about the current status? How exactly did you run `cmake` prior to the `ninja` call above? What did you change in the code?

> /data/data/com.termux/files/usr/include/stdio.h:391:6: error: expected identifier or '('

indicates IMO that a macro definition somewhere (probably just prior to the include for `stdio.h` in this case) is fishy...

**Comment by sebastinas** [comment]
> > Thanks, I have edited common.c file, replaced function aligned_alloc() with memalign().
> 
> Good to hear: Looks like a #define for aligned_malloc to `memalign` may be a general solution if `__ANDROID__` is defined.

In Picnic we have already done that work. See https://github.com/IAIK/Picnic/blob/master/compat.c#L42. The availability of the functions can easily checked with cmake: https://github.com/IAIK/Picnic/blob/master/CMakeLists.txt#L70

If there is interest in that, I can port it to liboqs.

**Comment by sebastinas** [comment]
The issue with CPU_SUPPORTS_NEON is a typo in the OQS clue code of Picnic. PR is coming up.

**Comment by baentsch** [comment]
> If there is interest in that, I can port it to liboqs.

If it's not too much of an effort, it'd be very nice to have.

**Comment by sebastinas** [comment]
Done in #1300.

**Comment by sebastinas** [comment]
@ilovevkapi Fixes for both issues are now merged into the main branch. Can you confirm that they fix the issues for you?

**Comment by baentsch** [comment]
@ilovevkapi Did you check whether @sebastinas fix resolves the issue for you? We'd close the issue due to inactivity otherwise.
