### ISSUE TITLE
Why not Rust?

### ISSUE THREAD

**Issue by dotridat** [open-quantum-safe/liboqs#1299]
Although liboqs-rust is written in Rust, but liboqs isn't.

**Comment by dotridat** [comment]
> (read: with as few people as possible :)

Rust compiler checks the code when developing, debugging in Rust is more economical than C. Pwn2Own is a computer hacking contest that includes contest on virtual machine escape targeting VMware and VirtualBox, debugging C/C++ code is much more expensive, it requires Pwn2Own to find virtual machine escape bugs.

**Comment by baentsch** [comment]
> debugging C/C++ code is much more expensive

Probably right. But the C code exists (and is being worked on upstream); Rust doesn't/isn't. So unless you (or anyone you know) would volunteer, this won't make our immediate task list.

**Comment by thomwiggers** [comment]
liboqs-rust is *not* written in Rust, it is a set of bindings to the C implementations of liboqs.

**Comment by baentsch** [comment]
Closing due to lack of resources. @dotridat feel free to reopen / provide PR if you have the bandwidth to do so.
