### ISSUE TITLE
Kyber1024 encapsulation causes shared secret to get mangled

### ISSUE THREAD

**Issue by LittleTimmy63** [open-quantum-safe/liboqs#1301]
I am trying to write a small program to encrypt and decrypt using Kyber1024.
However, I have discovered an issue. Despite issuing the same input (11111111111111111111111111111111), and using the same key, the output is different each time. By printing out values, I have deduced that OQS_KEM_encaps, when using Kyber1024, somehow turns the input into garbage.

Replication:
```
puts("pre encaps inp");
puts(inp);
if ((OQS_KEM_encaps(kem, *out, inp, pub)) == OQS_ERROR) exit(EXIT_FAILURE);
puts("post encaps inp");
puts(inp);
```

Expected output:
pre encaps inp
11111111111111111111111111111111
post encaps inp
11111111111111111111111111111111
Actual output:
pre encaps inp
11111111111111111111111111111111
post encaps inp
*{�c��_�@�p��H`�V���f@Ҳ�hb�S-��
         
It should be noted that the exact string of garbage is different each time.

**Comment by dstebila** [comment]
You seem to have misunderstood the difference between **key encapsulation mechanism** and **public key encryption** scheme.  Please read up on the differences between them: Kyber is a KEM, and does not allow for encryption of a user-chosen message.

**Comment by LittleTimmy63** [comment]
So an arbitrary key cannot be used?

**Comment by baentsch** [comment]
> So an arbitrary key cannot be used?

[A KEM API does not allow to encrypt chosen messages, the message gets created for you.](https://cryptopedia.dev/posts/kyber)

**Comment by LittleTimmy63** [comment]
I see. I suppose I must go rewrite my things then.
Cheers!
