### ISSUE TITLE
PKE

### ISSUE THREAD

**Issue by tbraun96** [open-quantum-safe/liboqs#1309]
Why is there no PKE support in OQS? Now that Kyber has been selected by the NIST, I'd expect public key encryption to be supported by the API. Was this a deliberate design/philosophy choice?

**Comment by dstebila** [comment]
The Kyber NIST submission is formulated solely as a KEM.  Definitely one can build a PKE from a KEM, but until/unless NIST gives a standardized version of that, we plan to stick with just the KEM formulation. There are many different design choices that can be made in creating a PKE via the KEM/DEM construction -- which symmetric key encryption scheme to use, etc -- that are better suited to general purpose cryptographic libraries.
