### ISSUE TITLE
Error when running speed test on ARM(Raspberry Pi 4)

### ISSUE THREAD

**Issue by SDust66** [open-quantum-safe/liboqs#1310]
Hello, I want to use liboqs in my Raspberry Pi, so I clone version 0.7.2 to Raspberry Pi. Then I compile on Raspberry Pi rather than use cross compilation. I use `cmake -GNinja -DOQS_USE_OPENSSL=OFF .. && ninja`, it can compile successfully.  I can run `example_kem`, it shows
```
[example_stack] OQS_KEM_frodokem_640_aes operations completed.
[example_heap]  OQS_KEM_frodokem_640_aes operations completed.
```
, I think it works well. But when I run `speed_kem`, some errors occurred, it shows `Illegal instruction`, the full output as follows:
```
pi@raspberrypi:~/liboqs-0.7.2/build/tests $ ./speed_kem
Configuration info
==================
Target platform:  armv7l-Linux-5.15.61-v7l+
Compiler:         gcc (10.2.1)
Compile options:  [-Werror;-Wall;-Wextra;-Wpedantic;-Wstrict-prototypes;-Wshadow;-Wformat=2;-Wfloat-equal;-Wwrite-strings;-Wstrict-overflow;-ggdb3;-Wbad-function-cast]
OQS version:      0.7.2
Git commit:       unknown
OpenSSL enabled:  No
AES:              C
SHA-2:            C
SHA-3:            C
OQS build flags:  OQS_OPT_TARGET=auto CMAKE_BUILD_TYPE=Debug
CPU exts compile-time:

Speed test
==========
Started at 2022-10-24 09:39:20
Operation                            | Iterations | Total time (s) | Time (us): mean | pop. stdev | CPU cycles: mean          | pop. stdev
------------------------------------ | ----------:| --------------:| ---------------:| ----------:| -------------------------:| ----------:
Classic-McEliece-348864              |            |                |                 |            |                           |
Illegal instruction
```
Please help me to solve this problem, thanks for your help.

**Comment by baentsch** [comment]
You may want to try building `liboqs` with [OQS_OPT_TARGET=generic](https://github.com/open-quantum-safe/liboqs/wiki/Customizing-liboqs#oqs_opt_target) as "Illegal instruction" errors often are caused by unsupported CPU instructions emitted by "auto"(matic) compiler optimizations not supported by the (runtime) CPU.

**Comment by SDust66** [comment]
Thanks for your reply, I try to building with `cmake -GNinja -DOQS_USE_OPENSSL=OFF -DOQS_OPT_TARGET=generic ..` and `cmake -GNinja -DOQS_USE_OPENSSL=OFF -DOQS_OPT_TARGET=cortex-a5 ..`. Unfortunately, I still see the same errors, any other suggestiions?

**Comment by SDust66** [comment]
I make a mistake, in `tests/ds_benchmark.h` line 84, it said `On Raspberry Pi, you need to additionally define the macro _RASPBERRY_PI since the high-precision cycle count register is not available to user-space programs.`. I do this and now it works  well. Thanks for your help again.

**Comment by baentsch** [comment]
@SDust66 : Thanks for letting us know what was the resolution to the problem. 
@dstebila : Would you know of a reason why `_RASPBERRY_PI` (or rather `USE_RASPBERRY_PI`) is not automatically set by the `cmake` config files (when they detect execution on R-Pi)? Would a PR be suitable to avoid others having to read the comments?

**Comment by dstebila** [comment]
> @SDust66 : Thanks for letting us know what was the resolution to the problem. @dstebila : Would you know of a reason why `_RASPBERRY_PI` (or rather `USE_RASPBERRY_PI`) is not automatically set by the `cmake` config files (when they detect execution on R-Pi)? Would a PR be suitable to avoid others having to read the comments?

I can't think of a reason that an appropriate flag is not set by CMake, other than that either (a) we didn't think about it or (b) we couldn't find a way to do it.  But if it can be done, then yes, let's do it.

**Comment by baentsch** [comment]
@SDust66 : As I don't have access to the same type of RPi that you have, would you be willing to try out https://github.com/open-quantum-safe/liboqs/pull/1313 (i.e., `git checkout mb-rasppi && cd build && cmake -GNinja -DOQS_USE_OPENSSL=OFF .. && ninja `) to see whether that solves the problem on your device automatically/sets the #define properly? The goal is to avoid future such "surprises" to other RPi users of `liboqs`. Thanks in advance (also for possible alternative suggestions to #1313).
