### ISSUE TITLE
Malleable Falcon signatures, may need upgrade to v1.2 spec

### ISSUE THREAD

**Issue by WizardOfMenlo** [open-quantum-safe/liboqs#1315]
Hi there,

The clean/avx2 implementations of Falcon-512 and Falcon-1024 seem to be unaligned with some changes introduced in v1.2 of the spec.

In particular, the implementation of the signature verification algorithm currently in libOQS accepts mauled signatures due to how `comp_decode` in `codec.c` is implemented. I attached an example program for ease of inspection.

Following Section 3.11.2 and Algorithms 17-18 in the Falcon spec v1.2, I believe that in order to enforce a unique encoding of compressed signatures, the decode implementation should not accept 100000001 ("-0") as a valid encoding of 0, and should check that signatures are padded using zeroes.

Kind Regards,
Giacomo Fenzi

Attached bug: [bug.c](https://gist.github.com/WizardOfMenlo/59e6e0457f94bf5caf13909f319007de)

**Comment by baentsch** [comment]
Hi Giacomo, thanks for raising this issue. We are planning an update to all algorithms as per https://github.com/open-quantum-safe/liboqs/discussions/1292. Falcon in particular is integrated to `liboqs` via https://github.com/PQClean/PQClean, so it may be good to raise the issue there, too.

**Comment by dstebila** [comment]
Falcon updates have landed at PQClean, we can now proceed updating liboqs.

**Comment by dstebila** [comment]
Closed by #1395
