### ISSUE TITLE
Remove NTRU-Prime, Saber, Rainbow, and Picnic.

### ISSUE THREAD

**Issue by xvzcf** [open-quantum-safe/liboqs#1317]
They're no longer in the NIST PQC competition and we lack other compelling reasons to keep them.

**Comment by baentsch** [comment]
@xvzcf FYI, Here are all downstream PRs readily accessible in one place.

**Comment by xvzcf** [comment]
Accomplished by PRs https://github.com/open-quantum-safe/liboqs/pull/1325, https://github.com/open-quantum-safe/liboqs/pull/1326, https://github.com/open-quantum-safe/liboqs/pull/1321, https://github.com/open-quantum-safe/liboqs/pull/1323
