### ISSUE TITLE
Update BIKE.

### ISSUE THREAD

**Issue by xvzcf** [open-quantum-safe/liboqs#1318]
[Our Implementaton](https://github.com/open-quantum-safe/liboqs/blob/main/src/kem/bike/additional_r3/README.md) corresponds to the `BIKE_Spec.2020.05.03.1.pdf` spec, whereas the [latest specification](https://bikesuite.org/#spec) is `BIKE_Spec.2022.10.10.1`.  The latest specification features a new vector sampling technique that results in new KATs.

**Comment by dstebila** [comment]
@crockeea Is there anyone from your team who is able to help with updating BIKE in liboqs to the newest version?

**Comment by dstebila** [comment]
Pinging @crockeea

**Comment by brian-jarvis-aws** [comment]
Hi there, we'll be able to have someone work on this starting soon. We are targeting the end of January to get a PR opened with the update.

**Comment by baentsch** [comment]
Closed via #1369
