### ISSUE TITLE
Update PQClean commit in `copy_from_upstream.yml`

### ISSUE THREAD

**Issue by xvzcf** [open-quantum-safe/liboqs#1322]
Once https://github.com/open-quantum-safe/liboqs/issues/1317 is done, we should also update the PQClean `git_commit` hash in [copy_from_upstream.yml](https://github.com/open-quantum-safe/liboqs/blob/main/scripts/copy_from_upstream/copy_from_upstream.yml#L6) to at least [b0fc0c098c7930e04931071a46cc7d520a1f8d1b](https://github.com/PQClean/PQClean/commit/b0fc0c098c7930e04931071a46cc7d520a1f8d1b) or more recent so we don't continue pulling removed algorithms.

**Comment by dstebila** [comment]
Looks like we can do this now, @xvzcf
