### ISSUE TITLE
Add NTRU prime back

### ISSUE THREAD

**Issue by loganaden** [open-quantum-safe/liboqs#1329]
Hi All,

We have been working on NTRU prime due to its interesting properties that make it an alternative choice to Kyber, despite its lack of NIST support. 

It would be worth pointing out that 
1) OpenSSH 9.0 (SSH server) ships with NTRU prime by default: https://www.openssh.com/txt/release-9.0
2) OpenIKED (VPN) ships with NTRU prime as well: https://github.com/openiked/openiked-portable/releases/tag/v7.0
3) Putty (SSH Client) now supports NTRU prime: https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

And the removal of NTRU prime breaks a popular SSH library which relies on liboqs-python for interop with OpenSSH:
https://github.com/ronf/asyncssh

A PR was sent for your consideration as well: https://github.com/open-quantum-safe/liboqs/pull/1328

**Comment by xvzcf** [comment]
OpenSSH at least plans to add support for Kyber "fairly soon": https://news.ycombinator.com/item?id=32360533#32366614

**Comment by loganaden** [comment]
@xvzcf agreed. However, it's likely that open source developers and companies could ignore NIST recommendations and ship with NTRU prime for a long time.

**Comment by loganaden** [comment]
@xvzcf https://cloud.google.com/blog/products/identity-security/why-google-now-uses-post-quantum-cryptography-for-internal-comms

**Comment by baentsch** [comment]
> @xvzcf agreed. However, it's likely that open source developers and companies could ignore NIST recommendations and ship with NTRU* for a long time.

Please see https://github.com/open-quantum-safe/liboqs/pull/1328#issuecomment-1352629540 on the topic of NTRUprime. Please also note that
- NTRU and NTRUprime are quite different and
- there is [a PR also removing NTRU from liboqs](https://github.com/open-quantum-safe/liboqs/pull/1335) that [has been approved "with cheers" by its principal submitter](https://github.com/open-quantum-safe/liboqs/pull/1335#pullrequestreview-1218577709):
 
Supporting things that are outdated costs time not available to other things that still are moving forward, particularly considering that old code/releases are not going away and can still be utilized (just without active support).

**Comment by bbbrumley** [comment]
> the removal of NTRU prime breaks a popular SSH library which relies on liboqs-python for interop with OpenSSH

> Supporting things that are outdated costs time

These statements seem conflicting to me.

I can assure you, NTRU Prime is not outdated.

I'll take a closer look at the PR now ...

**Comment by baentsch** [comment]
> I can assure you, NTRU Prime is not outdated.

Excellent -- such statement of support was missing until now.

> I'll take a closer look at the PR now ...

Thanks!

**Comment by romen** [comment]
I wanted to update the thread with a pointer to the message from the NTRU Prime team on the CFRG thread where an I-D is being discussed: https://mailarchive.ietf.org/arch/msg/cfrg/bkIRllgoqNIpureewvCjDH2FIag/

**Comment by baentsch** [comment]
@romen, Thanks for the additional statement of support documented in the link above. #1328 good to merge for me -- if @bbbrumley wants to take another look, please do.

**Comment by bbbrumley** [comment]
Yea the PR looks good :rocket: Thanks for the dialogue here, and on the PR thread :pray:

**Comment by baentsch** [comment]
Closed via #1328
