### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by k-Artin** [open-quantum-safe/liboqs#1330]
Hi,
I want to build liboqs on docker container. Information of my host and docker are in below. when I run "ninja", this error ocures.

> root@ec82cc506bf5:/home/liboqs/build# ninja
> [1062/1828] Building C object src/sig/falcon/CMakeFiles/falcon_1024_clean.dir/pqclean_falcon-1024_clean/keygen.c.o
FAILED: src/sig/falcon/CMakeFiles/falcon_1024_clean.dir/pqclean_falcon-1024_clean/keygen.c.o 
/usr/bin/cc  -Iinclude -I../src/sig/falcon/pqclean_falcon-1024_clean -I../src/common/pqclean_shims -fPIC -fvisibility=hidden   -march=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -Wa,--noexecstack -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -std=gnu11 -MD -MT src/sig/falcon/CMakeFiles/falcon_1024_clean.dir/pqclean_falcon-1024_clean/keygen.c.o -MF src/sig/falcon/CMakeFiles/falcon_1024_clean.dir/pqclean_falcon-1024_clean/keygen.c.o.d -o src/sig/falcon/CMakeFiles/falcon_1024_clean.dir/pqclean_falcon-1024_clean/keygen.c.o   -c ../src/sig/falcon/pqclean_falcon-1024_clean/keygen.c
cc: fatal error: Killed signal terminated program cc1
compilation terminated.

I can build liboqs on host, successfully, but don't underestand the main reason of this error.
host info:
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

docker info:
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Kind Regards,
Artin

**Comment by baentsch** [comment]
This trace does not contain sufficient information to allow giving meaningful feedback. I'd suggest you use/build the known-good Dockerfile at https://github.com/open-quantum-safe/oqs-demos/tree/main/curl to check your docker installation (and build liboqs in the process).

**Comment by k-Artin** [comment]
Thanks  Michael.

**Comment by k-Artin** [comment]
> UW. OK to close the issue?

Yes
