### ISSUE TITLE
`ninja run_tests` target does not build the `dump_alg_info` executable

### ISSUE THREAD

**Issue by xvzcf** [open-quantum-safe/liboqs#1334]
Running:

```
cmake -G"Ninja" ..
ninja run_tests
```
Causes some tests to fail since the `dump_alg_info` executable is not built.

**Comment by baentsch** [comment]
In which environment? This builds, works and tests just fine for me (and CI) -- admittedly "only" checked under Linux.

**Comment by xvzcf** [comment]
This was on my MacBook Pro, but I think the fix is simple, and I'll put one up one in some time.
