### ISSUE TITLE
Doxygen uses hardcoded output directory

### ISSUE THREAD

**Issue by iyanmv** [open-quantum-safe/liboqs#1341]
When running `ninja gen_docs`, `doxygen` always generate the docs on top of the `src` directory instead of using the build directory passed to `cmake`. This happens because of this line in Doxyfile

https://github.com/open-quantum-safe/liboqs/blob/2e42595804242d1e24e04f0f770a348c0c22313b/docs/.Doxyfile#L61

And it will fail to create the directory `docs` if `build` doesn't exist already.

**Comment by dstebila** [comment]
I don't understand what you mean by "generate the docs on top of the src directory" -- I see them being generated in build/docs.  That being said, I agree that we have hardcoded the directory in the Doxyfile to build/docs rather than whatever directory cmake was run in; I don't know how to fix that because the .Doxyfile is not generated by CMake.

**Comment by iyanmv** [comment]
I meant `src`/build/docs with `src` being the path of the source code. Probably this is not relevant for people just downloading the source code and compiling locally, but it can be an issue for packagers. I actually noticed this while creating a [package for Arch Linux](https://aur.archlinux.org/packages/liboqs). The "standard" way of dealing with cmake packages in Arch (and I guess other distros) when building in a clean chroot environment is to have the `src` and build in the same directory, not build inside `src` (see how I pass `-C` and `-S` to `cmake` in the `build()` function.

Isn't it possible to delete that line from the Doxyfile and handle that in the `CMakeLists.txt`?

**Comment by dstebila** [comment]
When you talk about `src`, are you talking about the `src` directory inside the liboqs directory, or is that `src/src` in your terminology?

**Comment by iyanmv** [comment]
Sorry for the confusion, maybe I should have used `source` instead of `src`. In my previous comments, that directory you mention is indeed `src/src`.

**Comment by dstebila** [comment]
Okay, I understand now.  I've tried to fix it in #1357, can you see if that does what you're looking for?
