### ISSUE TITLE
Question: Is there any standard way to uninstall , installed liboqs? 

### ISSUE THREAD

**Issue by evil-user** [open-quantum-safe/liboqs#1360]
Hi , I used https://openquantumsafe.org/liboqs/getting-started.html to install liboqs on my debian machine , i checked present documentation but couldnot find any documentation to uninstall , is there any standard procedure to uninstall liboqs conveniently.

**Comment by baentsch** [comment]
As we don't provide an installer (rpm/deb) there's no uninstaller either. So, if you simply ran `ninja install`you need to manually remove the files installed in that step (location dependent on the `CMAKE_INSTALL_PREFIX` you installed when building; if unset the default location [is /usr/local](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html)). The files installed are then in the usual `include` and `lib`directories (named `oqs` and `liboqs*` respectively).

**Comment by evil-user** [comment]
ok thank you sir
