### ISSUE TITLE
Kyber has non-namespaced global symbols

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#137]
Kyber has non-namespaced global symbols (see list below) and some of these conflict with Picnic (see @smashra's comment on pull request #120).  These are not being caught by Travis due to issue #130.  

Once #130 is fixed, these will need to be namespaced or made static.

```
0000000000000070 T barrett_reduce
0000000000000140 T bitrev_vector
00000000000002d0 T cbd
0000000000000100 T cmov
0000000000000090 T freeze
0000000000000fa0 T gen_matrix
0000000000001ad0 T indcpa_dec
00000000000014f0 T indcpa_enc
0000000000001140 T indcpa_keypair
0000000000000050 T montgomery_reduce
0000000000000190 T mul_coefficients
00000000000001d0 T ntt
0000000000000900 T poly_add
0000000000000380 T poly_compress
0000000000000470 T poly_decompress
0000000000000690 T poly_frombytes
0000000000000980 T poly_frommsg
00000000000007b0 T poly_getnoise
0000000000000870 T poly_invntt
0000000000000820 T poly_ntt
0000000000000940 T poly_sub
0000000000000570 T poly_tobytes
00000000000009d0 T poly_tomsg
0000000000000f40 T polyvec_add
0000000000000a60 T polyvec_compress
0000000000000bb0 T polyvec_decompress
0000000000000db0 T polyvec_frombytes
0000000000000e20 T polyvec_invntt
0000000000000df0 T polyvec_ntt
0000000000000e50 T polyvec_pointwise_acc
0000000000000d70 T polyvec_tobytes
00000000000000c0 T verify
```

**Comment by tlepoint** [comment]
They were not catch on my mac by running
```
nm -g liboqs.a | grep ' T ' | grep -E -v -i ' T [_]?[OQS|ntru_]+'
```
but they are catch with 
```
nm -g liboqs.a | grep ' T ' | grep -E -v -i ' T [_]?[OQS|ntru]+'
```

1. bug?
2. Now that NTRU is in liboqs (cf. #135), should we remove this exception and also force ntru to use `static`?

**Comment by dstebila** [comment]
My brain cannot tell why one regexp would work and the other not, but okay.  :)  I've made pull request #141 to change the check.

I am not inclined to change the ntru code to use static.  My goal is to have sufficient namespacing to avoid conflicts between different algorithms we are packaging up, and the ntru_ prefix is sufficient from my perspective.  If we were making a production library, then perhaps we would want all namespacing to be our namespacing, but that's not a priority to me.  Thoughts?
