### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1372]
This issue is to suggest updating the Wikis after the recent algorithm updates. 

Alternatively, shall we move Wiki content to the actual project documentation allowing catching algorithm updates more easily (via `grep -r` say)? Example: https://github.com/open-quantum-safe/liboqs/wiki/Customizing-liboqs

Concrete questions: 
Does BIKE still not work with cygwin as per https://github.com/open-quantum-safe/liboqs/wiki/Platform-specific-notes-for-building-liboqs#using-cygwin ? @dkostic ?
SIKE, SIDH, Picnic references should be removed completely, right @christianpaquin ?

**Comment by dkostic** [comment]
> Does BIKE still not work with cygwin as per https://github.com/open-quantum-safe/liboqs/wiki/Platform-specific-notes-for-building-liboqs#using-cygwin ? @dkostic ?

I don't really know, we never tested BIKE with cygwin and I don't have a Windows machine handy, but I can't think of a reason why it wouldn't work.

**Comment by baentsch** [comment]
> I don't have a Windows machine handy

I don't either, so I guess we then simply [leave BIKE disabled](https://github.com/open-quantum-safe/liboqs/blob/d9c39e24856e9e91e412bf676d319256dcb5d485/.CMake/alg_support.cmake#L76) for that arcane platform and wait if someone wants to run it there. Tagging again @christianpaquin in case he has an opinion to the opposite.

**Comment by baentsch** [comment]
Wiki update done as no voices heard regarding moving platform-specific build instructions into the liboqs file structure.
