### ISSUE TITLE
Docs/website out of date

### ISSUE THREAD

**Issue by thomwiggers** [open-quantum-safe/liboqs#1382]
https://openquantumsafe.org/liboqs/algorithms/ should be updated. Stuff I've noticed:

* [ ] Many removed algorithms are still listed: Rainbow, SABER, NTRU, Picnic
* [ ] BIKE still has IND-CCA secure variants (-FO) listed
* [ ] Most NTRUPrime parametersets are still listed

**Comment by dkostic** [comment]
Just chiming in regarding BIK -- the Round-4 spec does include the FO transform, but I think the team doesn't claim CCA security because of a missing formal proof.

**Comment by thomwiggers** [comment]
In section 4.1.3 in the BIKE spec it says 

> Key reuse or adapting BIKE to asynchronous protocols (e.g. email) require to secure long term static keys. Those usage models are possible but no longer provides forward secrecy and require IND-CCA security. Note that they are not compliant with BIKE’s current specification.
>https://bikesuite.org/files/v5.0/BIKE_Spec.2022.10.10.1.pdf

So there's no CCA-secure secure implementation. It indeed does still use the FO (section 4.3.4, "Why keep the Fujisaki-Okamoto transformation?") but the names of the parameters are now just "BIKE1-Level1" and "BIKE1-Level3" according to the spec.

**Comment by baentsch** [comment]
What about streamlining https://openquantumsafe.org/liboqs/algorithms/ to only list the algorithm families (still present -- ie, removing Picnic et.al.) with pointers to their respective .MD files in github (e.g., https://github.com/open-quantum-safe/liboqs/blob/main/docs/algorithms/kem/bike.md for BIKE)? That way the alg list on the "static" website is "automatically" up-to-date with the latest `liboqs` code.
