### ISSUE TITLE
Update CBOM after BIKE Round 4 update?

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#1383]
Do we need to update the CBOM #1336 after the BIKE Round 4 update #1369?  @bhess?

If so, we should also make some process to ensure we don't miss that type of thing next time -- maybe updating the PR template, maybe something more.

**Comment by dkostic** [comment]
I updated the CBOM manually in #1369 by running the `update_docs_from_yaml.py` script (the CI complained about documentation not being up to date before that).

**Comment by dstebila** [comment]
Ah, thanks for handling that!  Closing as already resolved.
