### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by Immortality-IMT** [open-quantum-safe/liboqs#1385]
What is this? Why I cannot use, configure, make, make install and have the headers to the /usr directory, so the headers can be found by C program?

Please no changes, source code install on Linux should always be?

./configure
make
sudo make install

Can you provide instructions for traditional compilation?

**Comment by baentsch** [comment]
`autoconf` is just one way to configure Linux software. This project has decided to use `cmake` instead -- also easing integration beyond Linux. 
To spell it out if you're unfamiliar with `cmake` just replace autoconf's "./configure" with `cmake -S . -B _build && cd _build` and use the rest of the commands you're familiar with. I would recommend reading up on `cmake` though as it provides a few more capabilities than `autoconf`.

**Comment by Immortality-IMT** [comment]
Cool, thanks
