### ISSUE TITLE
F38/Fedora rawhide test failures

### ISSUE THREAD

**Issue by beldmit** [open-quantum-safe/liboqs#1389]
Dear colleagues,

I came across a test failure on Fedora 38 and fedora rawhide. We use the 0.7.2 release 

https://copr.fedorainfracloud.org/coprs/g/fedora-review/fedora-review-2168929-liboqs/build/5521897/ is the build in question. https://download.copr.fedorainfracloud.org/results/@fedora-review/fedora-review-2168929-liboqs/fedora-rawhide-x86_64/05521897-liboqs/builder-live.log.gz is a log file with errors.

Could you please take a look?

**Comment by baentsch** [comment]
> Could you please take a look?

We did (and will continue): Looks like HQC simply doesn't properly work in that distro. How did you get around https://github.com/open-quantum-safe/liboqs/issues/1381 ?

"Some" followup questions: Does everything work OK in F37? If so, what's the difference between F37&38? gcc versions? Is F38 now generally available and would it be sensible/welcome that we add it to our CI? Is this a plain-and-simple x64 machine? Would testing on CircleCI or github be more sensible from your perspective?

**Comment by beldmit** [comment]
Yes, it runs OK for F37 and fails for F38/rawhide. 

https://copr.fedorainfracloud.org/coprs/g/fedora-review/fedora-review-2168929-liboqs/build/5521897/ lists all the builds for various Fedora versions, and builder-live.log.gz contains the package versions. I think there are more than one differences. 

As F38 is recently forked, I think it's worth adding F38 to CI. I think there are more than one differences.

**Comment by beldmit** [comment]
> How did you get around #1381 ?

I stripped -Werror, and currently build only NIST algorithms and without AVX2 support.

**Comment by baentsch** [comment]
> As F38 is recently forked, I think it's worth adding F38 to CI.

When checking docker hub, rawhide and 38 are identical -- so is 38 now fixed or still undergoing changes (as I'd assume rawhide is)? So I guess the question is: Should we use `fedora:38` from docker hub as the baseline docker image to build a CI image or something else?

**Comment by beldmit** [comment]
I think yes, fedora:38 is OK

**Comment by beldmit** [comment]
@baentsch I'm currently working on adding liboqs to Fedora. So the we need smth to rely on (a release, a release + reasonable set of patches) for our builds. The exact commit is also an option but the least desired.

**Comment by beldmit** [comment]
@baentsch could you please assist with identifying the changes necessary to apply to 0.7.2 to make it pass the tests?

**Comment by baentsch** [comment]
> @baentsch could you please assist with identifying the changes necessary to apply to 0.7.2 to make it pass the tests?

I'll give it a try. Hope it's not the major upstream update that corrected the HQC behaviour.... Stay tuned.

**Comment by baentsch** [comment]
Could I ask you to take a look at this Dockerfile, @beldmit ?

```
FROM fedora:38

RUN yum -y install yum-utils gcc cmake autoconf automake git openssl-devel libtool make python3-pip python3-devel wget clang doxygen doxygen-latex doxygen-doxywizard ninja-build && pip3 install -U nose rednose pytest pytest-xdist psutil pyyaml

RUN mkdir /projects && cd /projects && git clone https://github.com/open-quantum-safe/liboqs.git && cd liboqs && git checkout 0.7.2 && git cherry-pick -n 423b720c38985fd3fe8cc4874806fe0c5be6266e && mkdir build && cd build && cmake -GNinja .. && ninja && ninja run_tests 
```
"Problem": It works without fault. Can you point out a difference as to how you build and test (triggering the HQC problems at the start of this thread)?

**Comment by beldmit** [comment]
Thanks, I will try to apply the 423b720c38985fd3fe8cc4874806fe0c5be6266e tomorrow, currently I use vanilla 0.7.2 with stripped -Werror. Probably that's the culprit

**Comment by beldmit** [comment]
I tried to build with the https://github.com/open-quantum-safe/liboqs/commit/423b720c38985fd3fe8cc4874806fe0c5be6266e, got a different error.

```
{standard input}: Assembler messages:
{standard input}:21535: Error: unsupported instruction `vpcmpeqd'
[131/2317] /usr/bin/gcc  -I/builddir/build/BUILD/liboqs-0.7.2/redhat-linux-build/include -I/builddir/build/BUILD/liboqs-0.7.2/src/kem/classic_mceliece/pqclean_mceliece348864_avx -I/builddir/build/BUILD/liboqs-0.7.2/src/common/pqclean_shims -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -fPIC -fvisibility=hidden -march=native -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -Wstrict-overflow -ggdb3 -mavx2 -mpopcnt -Wno-language-extension-token -std=gnu11 -MD -MT src/kem/classic_mceliece/CMakeFiles/classic_mceliece_348864_avx.dir/pqclean_mceliece348864_avx/sk_gen.c.o -MF src/kem/classic_mceliece/CMakeFiles/classic_mceliece_348864_avx.dir/pqclean_mceliece348864_avx/sk_gen.c.o.d -o src/kem/classic_mceliece/CMakeFiles/classic_mceliece_348864_avx.dir/pqclean_mceliece348864_avx/sk_gen.c.o -c /builddir/build/BUILD/liboqs-0.7.2/src/kem/classic_mceliece/pqclean_mceliece348864_avx/sk_gen.c
ninja: build stopped: subcommand failed.
error: Bad exit status from /var/tmp/rpm-tmp.YbU3UQ (%build)
    Bad exit status from /var/tmp/rpm-tmp.YbU3UQ (%build)
```

My CMake command is ```/usr/bin/cmake -S . -B redhat-linux-build -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -GNinja -DBUILD_SHARED_LIBS=ON -DOQS_ALGS_ENABLED=NIST_R4 -DCMAKE_BUILD_TYPE=Debug **-DOQS_USE_AVX512_INSTRUCTIONS=OFF**```

**Comment by beldmit** [comment]
As `-DOQS_USE_AVX512_INSTRUCTIONS=OFF` I expect that `vpcmpeqd' will not be used...

**Comment by beldmit** [comment]
https://download.copr.fedorainfracloud.org/results/@fedora-review/fedora-review-2168929-liboqs/fedora-38-x86_64/05528439-liboqs/builder-live.log.gz and https://download.copr.fedorainfracloud.org/results/@fedora-review/fedora-review-2168929-liboqs/fedora-rawhide-x86_64/05528439-liboqs/builder-live.log.gz have different errors, BTW.

**Comment by baentsch** [comment]
> As `-DOQS_USE_AVX512_INSTRUCTIONS=OFF` I expect that `vpcmpeqd' will not be used...

I'm not a specialist in Intel assembly instructions, but isn't `vpcmpeqd` an AVX2 extension? What changes when you disable AVX2 (instead of AVX512)? Also FWIW, the problem doesn't reproduce on my machine when executing `mkdir /projects && cd /projects && git clone https://github.com/open-quantum-safe/liboqs.git && cd liboqs && git checkout 0.7.2 && git cherry-pick -n 423b720c38985fd3fe8cc4874806fe0c5be6266e && mkdir build && cd build && cmake -GNinja -DBUILD_SHARED_LIBS=ON -DOQS_ALGS_ENABLED=NIST_R4 -DCMAKE_BUILD_TYPE=Debug -DOQS_USE_AVX512_INSTRUCTIONS=OFF .. && ninja && ninja run_tests` in the above F38 docker image.... 

Do you know of another way to reproduce the build environment you're using?

**Comment by beldmit** [comment]
Sorry, you are right, it's both AVX512/AVX2 according to https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=vpcmpeqd

I've disabled AVX2 for the next iteration.

**Comment by baentsch** [comment]
> https://download.copr.fedorainfracloud.org/results/@fedora-review/fedora-review-2168929-liboqs/fedora-38-x86_64/05528439-liboqs/builder-live.log.gz and https://download.copr.fedorainfracloud.org/results/@fedora-review/fedora-review-2168929-liboqs/fedora-rawhide-x86_64/05528439-liboqs/builder-live.log.gz have different errors, BTW.

When checking these logs, there's something fishy: Your build has 2317 steps while mine (that is passing) has 2309. I now identically cloned your `cmake` command in my environment -- and still, everything passes. Puzzled....

**Comment by beldmit** [comment]
https://download.copr.fedorainfracloud.org/results/@fedora-review/fedora-review-2168929-liboqs/fedora-38-x86_64/05528467-liboqs/builder-live.log.gz is the build result with disabled AVX2, btw :(

**Comment by baentsch** [comment]
> https://download.copr.fedorainfracloud.org/results/@fedora-review/fedora-review-2168929-liboqs/fedora-38-x86_64/05528467-liboqs/builder-live.log.gz is the build result with disabled AVX2, btw :(

Woa -- building with AVX2 disabled should build _much_ fewer files... Lets me check this out.

**Comment by beldmit** [comment]
https://copr.fedorainfracloud.org/coprs/g/fedora-review/fedora-review-2168929-liboqs/build/5528467/ is the build page

**Comment by baentsch** [comment]
> https://copr.fedorainfracloud.org/coprs/g/fedora-review/fedora-review-2168929-liboqs/build/5528467/ is the build page

OK -- this section from the log is completely "impossible":

```
/usr/bin/cmake -S . -B redhat-linux-build -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -GNinja -DBUILD_SHARED_LIBS=ON -DOQS_ALGS_ENABLED=NIST_R4 -DCMAKE_BUILD_TYPE=Debug -DOQS_USE_AVX512_INSTRUCTIONS=OFF -DOQS_USE_AVX2_INSTRUCTIONS=OFF
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    OQS_ALGS_ENABLED


-- Build files have been written to: /builddir/build/BUILD/liboqs-0.7.2/redhat-linux-build
+ /usr/bin/cmake --build redhat-linux-build -j2 --verbose
[1/2303] 
```

--> If the disablement of AVX2 (i.e., `cmake` processing) had been successful, compilation of at most 1234 files makes sense (as all AVX2 optimized implementations were disabled). This exactly happens in my environment, so the question is whether there are differences in how your environment's `cmake`/CMakeList.txt processing operates. 

Do you possibly run not exactly the result of `git checkout 0.7.2 && git cherry-pick -n 423b720c38985fd3fe8cc4874806fe0c5be6266e` ? Why otherwise is there reference to "OQS_ALGS_ENABLED", a directive only introduced way after 0.7.2?

**Comment by beldmit** [comment]
I use the tar.gz from https://github.com/open-quantum-safe/liboqs/releases/tag/0.7.2 and apply the 423b720c38985fd3fe8cc4874806fe0c5be6266e and strip -Werror. Should it produce a different result?

**Comment by baentsch** [comment]
As you see in the Dockerfile, I'm using the tag directly from github and don't even have to strip -Werror. Can you share the _exact_ script you're running to get to what you compile? There's got to be something broken in the CMakeList.txt's somewhere judging from how little influence the `cmake` define directives have... In the mean time, let me try the tar.gz....

**Comment by beldmit** [comment]
I use the `rpmbuild -ba` using this spec https://dbelyavs.fedorapeople.org/liboqs.spec and this src.rpm:
https://dbelyavs.fedorapeople.org/liboqs-0.7.2-1.fc36.src.rpm (contains 2 patches and downloaded archive)

**Comment by baentsch** [comment]
> I use the `rpmbuild -ba` using this spec https://dbelyavs.fedorapeople.org/liboqs.spec and this src.rpm: https://dbelyavs.fedorapeople.org/liboqs-0.7.2-1.fc36.src.rpm (contains 2 patches and downloaded archive)

FYI, I have no experience with RPM (other than using it to install stuff), so will need some time to learn about it and understand the above. At first glance, there's substantial "messing" with .cmake files that could trigger these problems: Possibly, our `cmake` files don't handle well whatever this framework does with them. As usual: Stay tuned.

**Comment by beldmit** [comment]
The log files I refer to contains all the resulting commands so it may help

**Comment by baentsch** [comment]
> @baentsch What I'm concerned is that I see 2307 lines with any build options...

I'm not sure I understand this sentence... What lines are you referring-to? What do you see there?

**Comment by beldmit** [comment]
Sorry for unclarity. I mean that I get 2307 files compiled with any CMake options.

**Comment by baentsch** [comment]
Do you mean "...without" any CMake options (?) But that's normal, right? You should see the resultant Makefile options. Are they all there as you'd expect them? The ones I'm interested in of course are only visible in the Makefiles (that are not shown -- or I didn't find them yet).

**Comment by beldmit** [comment]
Sorry again. I tried a lot of options in the spec file - I changed the values for OQS_ALGS_ENABLED, OQS_USE_AVX512_INSTRUCTIONS, and OQS_USE_AVX2_INSTRUCTIONS. I always see 2307 lines to be compiled.

**Comment by baentsch** [comment]
Thanks for trying this. This should not happen, as AVX2 files should only be compiled if DIST_BUILD and/or AVX2 is explicitly requested. Could you possibly run `cmake` with the option `-LAH`to output the actual variable values set so we can compare our respective settings? Ideally, this is done on the (failing) F38 and the (passing) F37 builds: There must be a difference as the code is identical, right?

**Comment by beldmit** [comment]
Sure, here it is: https://copr.fedorainfracloud.org/coprs/g/fedora-review/fedora-review-2168929-liboqs/build/5529234/

**Comment by baentsch** [comment]
Thanks for this run. Please check it out yourself: By just adding `cmake` debug output, the complete build run succeeds and we wind up with HQC test errors instead. This is frustrating. Is there a way for me to ssh into your build system such as to debug this? Otherwise, please use my docker environment and show me how to reproduce the issue there.

**Comment by beldmit** [comment]
@baentsch 
Thank you for your efforts!

I think that the avx2-related failure depends on a specific machine on a farm where the build is performed.

Could you please confirm that the build directives I pass to CMake are correctly propagated through the make?

I will continue investigating the problem but probably next week.

**Comment by baentsch** [comment]
> Could you please confirm that the build directives I pass to CMake are correctly propagated through the make?

I can _not_ confirm this: You pass "-DOQS_USE_AVX2_INSTRUCTIONS=OFF" to `cmake` but (for example) the variable "OQS_ENABLE_KEM_classic_mceliece_348864_avx:BOOL=ON" is incorrectly reported. This is not the case when I try this locally: setting OQS_USE_AVX2_INSTRUCTIONS=OFF reliably turns off compilation of AVX-optimized code.

**Comment by beldmit** [comment]
Thank you! It's a sort of confirmation :)

**Comment by beldmit** [comment]
Found a bug in my specfile. Thanks for your patience, sorry for disturbing.
