### ISSUE TITLE
Falcon tests failing

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#1390]
https://github.com/open-quantum-safe/liboqs/actions/runs/4154153928/jobs/7186334170#step:6:3093

**Comment by baentsch** [comment]
It's more than that: Falcon's also the reason that [openssl tests began failing](https://app.circleci.com/pipelines/github/open-quantum-safe/openssl/1119/workflows/1f7c0a91-f914-4be5-a388-9b6a41a451b5/jobs/5353)

**Comment by baentsch** [comment]
Update: Falcon 1024 reliably fails in oqs-provider, too -- when doing many (>10) repetitions of the same (keygen-sign-verify) cycle --> There's got to be some "randomness" issue that makes signatures "bad"/unverifiable. The same problem cannot be reproduced with falcon512. Based on this, a `liboqs`-based reproducer has been created with #1391.

**Comment by baentsch** [comment]
"One more thing" -- when running the new "full cycle" speed test on OSX, the falcon1024 problem does not appear. It also does not appear on Windows when using MSVC. Using GNU tools, the problem does appear also under Windows, though. Fascinating. My guess is the quality of the randomness generators differs between the platforms and that has an impact on how Falcon-1024 operates (or not).
Long story short: Until someone really understands what's going on here, I'd suggest to revert #1386.
