### ISSUE TITLE
Repeated OQS API calls crash on armhf/32bit

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1393]
As is visible for example [here](https://github.com/open-quantum-safe/liboqs/actions/runs/4194024112/jobs/7271697077) the [speed_kem](https://github.com/open-quantum-safe/liboqs/blob/main/tests/speed_kem.c) and [speed_sig](https://github.com/open-quantum-safe/liboqs/blob/main/tests/speed_sig.c) test programs are failing for all algorithms with "Illegal Instruction" when running on armhf (emulated at least -- real HW not at hand).

**Comment by jamuir** [comment]
@baentsch :  unfortunately, the logs for the test run you linked to have expired and are no longer visible.

I took a look at a few of the recent test runs that failed on armhf but I did not see an "Illegal Instruction" failure.

Can you provide an updated pointer?

**Comment by baentsch** [comment]
Thanks for taking a look!

> Can you provide an updated pointer?

Unfortunately, I can't: The "speed" tests have been disabled on armhf. Changing this, please see the results of #1535 as and when they become available (and/or run such tests repeatedly locally to check whether the problem still exists).

**Comment by jamuir** [comment]
the checks for #1535 all completed successfully.

I looked through the output and `test_speed.py` does not report any problems.  It seems normal, although the tests for BIKE and SPHINCS+ are skipped.

It is looking like this issue has gone away (mabye due to a newer container image??).

**Comment by baentsch** [comment]
> It is looking like this issue has gone away

Indeed. Thanks for reviewing this.

**Comment by baentsch** [comment]
Documented as no longer an issue via #1535
