### ISSUE TITLE
Is there a method to display the public key of signatures?

### ISSUE THREAD

**Issue by JannisFengler** [open-quantum-safe/liboqs#1401]
There are 2 ways to init the signatures. One is to initiate with
 ```signer.Init(sigName, nil)``` 
After that, a keypair can be generated with 
```signer.GenerateKeyPair()``` 
which returns the public key. 

The second way is to initiate with: 
```signer.Init(sigName, secretKeyBytes)```

This function doesn't return a public key. I also didn't find a function like:
```signer.publicKey()```

Is there a best practice for extracting the public key? It would be great if this function would be part of the liboqs-go library.

**Comment by baentsch** [comment]
As this is a general API question, not specific to one language wrapper, reopening it here for wider discussion. 
My personal vote would be to not include an API that cannot be implemented for all PQ algorithms. The discussion thread referenced above also hints at a very special, Falcon-only, use case. Opinions to the contrary welcome.

**Comment by dstebila** [comment]
I agree with Michael, I'm not inclined to add an API that can only be implemented by some algorithms.

**Comment by vsoftco** [comment]
Agree as well
