### ISSUE TITLE
Use python code in python (CBOM again)

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1407]
@Martyrshot @bhess See this code: https://github.com/open-quantum-safe/liboqs/blob/341cf224270535e1a5769263f2dd2641fcf2c301/scripts/copy_from_upstream/copy_from_upstream.py#L619-L622

It is a) weird (as already stated in your own comment) and b) makes (remote/CI) debugging [see e.g. this error log](https://github.com/open-quantum-safe/liboqs/actions/runs/4273832035/jobs/7440002427) hard.

--> Would you be willing to do a PR to call python code the way it should be called from within python? That way it should be possible to get python stack traces/more easily understand the errors in code called (`update_cbom.py` in this case)?

@bhess: This is ultimately triggered by #1337 for which I already had to do a workaround to #1406... All this --also due to very long CI run times-- by now cost me 2 hours and I am unwilling to invest more time to debug & work around these issues. Please let me know whether you'd be willing to fix this issue, #1406, and find the CBOM-generation error in #1405, currently visible in [the error log](https://github.com/open-quantum-safe/liboqs/actions/runs/4273832035/jobs/7440002427).

**Comment by bhess** [comment]
I'll look into the issue next week.

**Comment by bhess** [comment]
Fixed by #1412
