### ISSUE TITLE
Tagging commit for IETF hackathon

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#1424]
Should we tag a commit for convenient use at the IETF hackathon?  Commit d61d81c526da8bb62e363f5a75191689572151cb is passing all tests (except for BIKE constant time).  

It looks like it might be a rush to get SPHINCS+ merged in the next few days and be sure that it won't cause problems.

What would be an appropriate tag?  `ietf-116`?

@baentsch @xvzcf opinions?

**Comment by dstebila** [comment]
Created tag `ietf116` on liboqs.  @baentsch I'll leave it to you to create a corresponding tag on oqs-provider.

**Comment by baentsch** [comment]
@dstebila Thanks. Same tag added to oqs-provider. Also implemented https://github.com/open-quantum-safe/oqs-demos/issues/192, providing ready-to-run docker hub hosted images for the software stack with these tags. Happy hacking, @xvzcf !
