### ISSUE TITLE
Only enable `-Werror` in tests?

### ISSUE THREAD

**Issue by thomwiggers** [open-quantum-safe/liboqs#1432]
Once in a while, compilers add new warnings. That's good, because it helps us find new flaws in existing code, but unfortunately this also has a tendency of breaking things, especially when particular versions of the library are included in other things.

For example, in https://github.com/open-quantum-safe/liboqs-rust/issues/199, the wrapper breaks because Bas was using a newer compiler version than what liboqs 0.7.2 was tested against.

Does it make sense to move the `-Werror` flag to only be set in tests?

**Comment by baentsch** [comment]
> Does it make sense to move the -Werror flag to only be set in tests?

Sounds good to me -- as long as (at least) one of those tests is part of CI.

**Comment by xvzcf** [comment]
New warnings produced by new/different compilers seem like useful information to gather, so it'd be nice to somehow ensure our test suites can keep up with all that's latest/different out there

**Comment by thomwiggers** [comment]
> Sounds good to me -- as long as (at least) one of those tests is part of CI.

Yeah, the way I envision this we put `-Werror` behind some flag that we enable everywhere where we want to see failures.

**Comment by thomwiggers** [comment]
It turns out there is already a CMAKE feature that does this: https://cmake.org/cmake/help/latest/prop_tgt/COMPILE_WARNING_AS_ERROR.html

**Comment by thomwiggers** [comment]
This already partially implemented by #1378
