### ISSUE TITLE
`x86` missing in check for CMAKE_SYSTEM_PROCESSOR

### ISSUE THREAD

**Issue by wucke13** [open-quantum-safe/liboqs#1442]
https://github.com/open-quantum-safe/liboqs/blob/d9f392a74bed7535c0a5a044633a9212aa8635d9/CMakeLists.txt#L51

should also contain `x86`, as it is also used to denote classic x86 32 Bit CPUs.

**Comment by dstebila** [comment]
@wucke13 Can you see if #1443 resolves your problem?
