### ISSUE TITLE
OQS_ENABLE_KEM_BIKE forced to OFF for ARCH_X86

### ISSUE THREAD

**Issue by JoeyLupo** [open-quantum-safe/liboqs#1443]
Hi all, looking at the comments on lines 75 and 77 of [liboqs/.CMake/alg_support.cmake ](https://github.com/open-quantum-safe/liboqs/blob/main/.CMake/alg_support.cmake) leads me to believe that BIKE should be supported on x86 architectures, yet line 76 disables them when ARCH_X86 is detected:
```
# BIKE is not supported on Windows, 32-bit ARM, S390X (big endian) and PPC64 (big endian)
cmake_dependent_option(OQS_ENABLE_KEM_BIKE "Enable BIKE algorithm family" ON "NOT WIN32; NOT ARCH_ARM32v7; NOT ARCH_X86; NOT ARCH_S390X; NOT ARCH_PPC64" OFF)
# BIKE doesn't work on any 32bit platform except x86:
if(CMAKE_SIZEOF_VOID_P MATCHES "4" AND NOT ARCH_X86)
set(OQS_ENABLE_KEM_BIKE OFF)
endif()
```

Removing `NOT ARCH_X86;` from line 76 allowed me to build BIKE without issue, so I'm wondering if this is merely a typo.

**Comment by dstebila** [comment]
This might be an obsolete line; at one point in time the BIKE implementation only worked on x86\_64, but perhaps that no longer holds. @dkostic do you have any insight?

**Comment by thomwiggers** [comment]
Relatedly, does BIKE support Windows 64 bits? Considering it specifically says 'NOT WIN32' right now.

**Comment by baentsch** [comment]
> Relatedly, does BIKE support Windows 64 bits? Considering it specifically says 'NOT WIN32' right now. If so, I need to update this in the Rust wrapper.

Just looking at a [Windows CI run from yesterday](https://ci.appveyor.com/project/dstebila/liboqs/builds/47098366/job/lnqfpoulicek3kvu) the answer seems to be "Yes" for cygwin and "No" for MSVC (head scratching... I always thought cygwin also sets "WIN32"...).

**Comment by baentsch** [comment]
> I [tested enabling BIKE on x86](https://github.com/open-quantum-safe/liboqs/tree/sw-bike-x86), and it triggered multiple CI failures—all at runtime as opposed to build errors. I'm going to assume, then, that we want to keep BIKE switched OFF by default for x86.

Thanks for the test -- but in this case the [liboqs documentation for BIKE](https://github.com/open-quantum-safe/liboqs/blob/main/docs/algorithms/kem/bike.md) seems wrong: It states support for "little endian" architectures --> Change doc (to state BIKE _only_ works for "x64") to really close the issue for good?
