### ISSUE TITLE
OQS_SHA2_sha256_inc_init fails with OpenSSL 3.0

### ISSUE THREAD

**Issue by bhess** [open-quantum-safe/liboqs#1446]
**Describe the bug**
`OQS_SHA2_sha256_inc_init` in sha2_ossl.c fails when compiled with OpenSSL 3.0.2: `oqs_sha256()` returns a null pointer.

**To Reproduce**
See https://github.com/open-quantum-safe/oqs-provider/issues/144

Can also be reproduced by compiling with OpenSSL 3.0.2 and running `test_hash` (exists with code 1).

```
git clone -b openssl-3.0.2 git://git.openssl.org/openssl.git
cd openssl
./config --prefix=$(echo $(pwd)/../.local) && make && make install_sw
cd ..
git clone https://github.com/open-quantum-safe/liboqs.git
cd liboqs
cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/../.local -S . -B _build
cmake --build _build && cmake --install _build
test/test_hash
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - OpenSSL version 3.0.2
 - Compiler version used [e.g., clang 14.0.0]
 - Build variables used, see above
 - liboqs version main branch

**Additional context**
Appeared in context of https://github.com/open-quantum-safe/oqs-provider/issues/144

**Comment by bhess** [comment]
> Alternatively, the changes introduced in #1431 require a call to `OQS_init`, maybe oqs-provider isn't calling this initialization routine?

Thank you for the hint! Indeed, these seem to be missing in oqs-provider. (Changing to `SHA2-256` didn't help there).
I'll double check if this really appears independent of oqs-provider and otherwise close the issue here.

**Comment by baentsch** [comment]
If #1431 landeed, OQS_init must be called by any consumer of liboqs, incl. oqsprovider. Didn't we label it an API breaking change requiring downstream adaptarions?

**Comment by bhess** [comment]
Tested it again, and the issue only occurs when OQS_init is missing (as in the downstream projects, not quite sure why it worked with OpensSSL 3.2).
I opened a PR for oqs-provider: https://github.com/open-quantum-safe/oqs-provider/pull/146.
Still needs to be done in [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh).
