### ISSUE TITLE
OpenSSL3 strict error checking causes downstream problems

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1462]
https://github.com/open-quantum-safe/liboqs/pull/1454 introduced strict error checking e.g., here: https://github.com/open-quantum-safe/liboqs/blob/24c7f4f07896252fe82a042633cf1d9e893153e4/src/common/ossl_helpers.c#L17 

Under specific preconditions (not activating `default` provider before `oqsprovider`) this causes https://github.com/open-quantum-safe/oqs-provider/issues/159.

Completely disregarding errors (as in the original code version https://github.com/open-quantum-safe/liboqs/pull/1431) seems suboptimal, too as it would lead to a "surprising" performance degradation in `liboqs` (depending on which provider is listed first), right @beldmit ?

Any suggestions how to resolve this quagmire _very_ welcome. Without better proposals, I tend to change [oqs_fetch_ossl_objects](https://github.com/open-quantum-safe/liboqs/blob/24c7f4f07896252fe82a042633cf1d9e893153e4/src/common/ossl_helpers.c#LL14C6-L14C28) to collect error messages and just output a warning if any have been encountered -- but not exit.

**Comment by baentsch** [comment]
> Probably it's worth raising this issue to OpenSSL upstream. Provider-interdependency topic is quite weird, and worth discussion.

Why? To me this is logical: `liboqs` (with OpenSSL3 enabled) depends on "default" provider (in initialization). If it's not there (for whichever reason), initialization of `liboqs` fails. `oqsprovider` needs to initialize `liboqs`. If that (would) fail, `oqsprovider` (would) fail.

> BTW, have you seen the announcement of the meeting between OpenSSL and provider authors? It's a relevant topic there, I think.

No, I did not. Where did this get posted? I'd be interested indeed.

**Comment by beldmit** [comment]
> > Probably it's worth raising this issue to OpenSSL upstream. Provider-interdependency topic is quite weird, and worth discussion.
> 
> Why? To me this is logical: `liboqs` (with OpenSSL3 enabled) depends on "default" provider (in initialization). If it's not there (for whichever reason), initialization of `liboqs` fails. `oqsprovider` needs to initialize `liboqs`. If that (would) fail, `oqsprovider` (would) fail.

The default provider is not the only provider the application may use - e.g. FIPS provider provides the same algorithm. So from this moment we are talking about more complex initialization/preference setup.

**Comment by baentsch** [comment]
> The annoucement was sent to openssl-users and openssl-project

Thanks -- now also subscribed to openssl-project (and the meeting).

> So from this moment we are talking about more complex initialization/preference setup.

Completely agree. So let me reformulate: Given [oqs_fetch_ossl_objects](https://github.com/open-quantum-safe/liboqs/blob/24c7f4f07896252fe82a042633cf1d9e893153e4/src/common/ossl_helpers.c#LL14C6-L14C28) failure of `oqsprovider` is logical if no other provider for initializing those algorithms is available prior to `oqsprovider` being activated. This can happen and thus a graceful (and helpful) handling of that condition must be possible.

The only better way would be if `openssl` were "automagically" handling the algorithm initialization (doing away with the need for `liboqs` implementing "oqs_fetch_ossl_objects"). Let me try to formulate that as an issue in the OpenSSL issues tracker...

**Comment by paulidale** [comment]
The fetching could be delayed until first use.  Not ideal in some ways, but prudent in others.

I'm not sure how we can define a provider ordering -- as noted FIPS and default both contain what's needed.  However, 3rd party providers could also be used -- how to specify them?

The obvious solution of having a dependency param somewhere, fails.  Depending on specific algorithms also isn't workable.

It's late, I'm tired & I'll think more on this tomorrow.

**Comment by beldmit** [comment]
the initialization on first attempt has downsides as it's necessary to deal with multithreading etc

**Comment by t8m** [comment]
One solution would be to split the provider initialization into two steps. After the first step the provider would respond to algorithm fetches but it would not be required to operate. Only after the second step those fetched implementations would be operable.

Another option is to do the fetches of subordinate algorithms needed to implement an fetched algorithm during the actual algorithm fetch - in the provider_query_operation function.

**Comment by t8m** [comment]
> Another option is to do the fetches of subordinate algorithms needed to implement an fetched algorithm during the actual algorithm fetch - in the provider_query_operation function.

IMO this is actually the right place where the subordinate fetches should be done. And they always should be done there, otherwise replacing the underlying implementation later (for example by unloading the default provider and loading the fips one) would not be possible.

**Comment by t8m** [comment]
Doing the prefetches during the initialization of liboqs is too early. This way it is basically impossible to reasonably affect the fetch operation.

IMO the API of liboqs is too simplistic to allow for any reasonable prefetching implementation. At best you could do fetches in the OQS_KEM_new() or ОQS_SIG_new() functions. However that would mean the fetched algos would be reused only within lifetime of these KEM or SIG objects. It would be better to add some kind of library context and prefetch the algorithms during the context initialization. Of course you would then have to pass the context into the ..._new() operations.

**Comment by dstebila** [comment]
Can they be fetched on first use and then saved after that?

**Comment by dstebila** [comment]
> Can they be fetched on first use and then saved after that?

Nevermind, I see this was discussed a few comments above.

**Comment by t8m** [comment]
IMO #1463 is not a real fix. Fetch on first use would be a fix, however it would require locking or atomic pointer cmpxchg access.

**Comment by baentsch** [comment]
> IMO #1463 is not a real fix. Fetch on first use would be a fix, however it would require locking or atomic pointer cmpxchg access.

Completely agree. It's a workaround. Based on your feedback, searching for some portable locking solution, I just stumbled across [CRYPTO_THREAD_run_once](https://www.openssl.org/docs/manmaster/man3/CRYPTO_THREAD_run_once.html)... So would https://github.com/open-quantum-safe/liboqs/pull/1469 be a "real" solution, @t8m?

**Comment by paulidale** [comment]
Yes, that's a real solution.
