### ISSUE TITLE
Continuous integration on Windows

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#149]
It would be great if we had continuous integration testing of the Visual Studio project build on Windows, using one of the Azure tools.  Vlad (@vsoftco) said he would look into it.  Christian (@christianpaquin) if you have any comments about this they'd be greatly appreciated too.

**Comment by christianpaquin** [comment]
I took a look a while back, but couldn't find an easy way to make this work with travis (without resorting to a clunky mechanism); I can take another look. @vsoftco, I'd be happy to discuss and share my notes.

**Comment by vsoftco** [comment]
@christianpaquin I was thinking of using AppVeyor https://www.appveyor.com, it seem to be working for some of my projects. I'll play with it and try to integrate liboqs with it.

**Comment by christianpaquin** [comment]
Sounds good. I was looking at spinning up VMs and using the GitHub status API to write my own [CI server](https://developer.github.com/v3/guides/building-a-ci-server/), but an existing solution definitely sounds better and more maintainable. I'll make sure the Windows build is working and up-to-date; it's been a while since I tested it.

**Comment by dstebila** [comment]
Let me know if there's anything I need to do to link AppVeyor to our project.

**Comment by christianpaquin** [comment]
FYI, I'm working on fixing the Windows build that has been broken, and also to enable support for kyber. I hope to push that out soon.

**Comment by christianpaquin** [comment]
PR #151 fixes the Windows build.

**Comment by vsoftco** [comment]
Managed to get the Windows build to run on Appveyor, will add the configuration to master soon after a bit more testing.
