### ISSUE TITLE
weird shared lib naming

### ISSUE THREAD

**Issue by msmeissn** [open-quantum-safe/liboqs#1497]
**Describe the bug**

Currently the build provides liboqs.so.0.8.0 and liboqs.so.3 linking to it.

Better would be liboqs.so.3.8.0 and liboqs.so.3  to share a common prefix.

**To Reproduce**

See above, liboqs.so.0.8.0 vs liboqs.so.3

**Expected behavior**

common suffix

**Screenshots**

**Environment (please complete the following information):**
 - OS: openSUSE Factory
 - OpenSSL version 3.1.0
 - Compiler version used gcc13
 - Build variables used
 -  cmake -S . -B build -DBUILD_SHARED_LIBS:BOOL=ON -DOQS_DIST_BUILD:BOOL=ON

 - liboqs version 0.8.0

**Additional context**

**Comment by baentsch** [comment]
Admittedly this is not totally intuitive. Rationale (my take): We are not confident (or courageous :) enough to move the library version beyond 1.0. [We do have a rationale for changing version minor (when breaking KAT changes occur) and it may be reasonable to also change version major when breaking API changes occur](https://github.com/open-quantum-safe/liboqs/wiki/Release-process#code-change). The latter happens much more rarely, thus supporting the case to move beyond 1.0. Also, our release cycle isn't exactly ultra-fast, so a new major version once a year doesn't sound terrible to consumers of the lib.

The upcoming API changes (XMSS, encryption APIs, ...) should be "add-only", not necessarily requiring a new version major -- or maybe it does? 

Input from "consuming" distribution integrators/maintainers would be very welcome. @vt-alt @beldmit @yurivict : Opinions?

**Comment by msmeissn** [comment]
but then perhaps it should not be liboqs.so.3, but still liboqs.so.0.

**Comment by baentsch** [comment]
> but then perhaps it should not be liboqs.so.3, but still liboqs.so.0.

That then begs the question how to deal with https://github.com/open-quantum-safe/liboqs/issues/1081

**Comment by vt-alt** [comment]
I think current naming is OK.

SONAME is `liboqs.so.3` because ABI was changed several times. Glibc had for years `libc.so.6 -> libc-$GLIBC_VERSION.so`.

```
builder@x86_64:/.in$ ls -la /lib64/libc*
-rwxr-xr-x 1 rooter rooter 1921200 Oct  8  2022 /lib64/libc-2.32.so
lrwxrwxrwx 1 rooter rooter      12 Jun 13 11:44 /lib64/libc.so.6 -> libc-2.32.so
```
Which is [changed just recently to remove symlink](https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=8208be389bce84be0e1c35a3daa0c3467418f921).

**Comment by ldv-alt** [comment]
> Currently the build provides liboqs.so.0.8.0 and liboqs.so.3 linking to it.
> 
> Better would be liboqs.so.3.8.0 and liboqs.so.3 to share a common prefix.

I'm sorry for writing obvious things here, but soname is not a kind of project version, it's an ABI identifier,
so it's perfectly fine for the project version to be `0.8.0` and for the soname to be `liboqs.so.3`.

Anyway, please change soname if and only if the underlying ABI has changed.

**Comment by msmeissn** [comment]
I was only wondering why there was liboqs.so.3 being a symlink to liboqs.so.0.8.0. ... if this is accepted practice I am fine.

**Comment by baentsch** [comment]
> if this is accepted practice I am fine

I think it is. OK to close the issue then?

**Comment by msmeissn** [comment]
yes
