### ISSUE TITLE
Weekly constant time tests failing on McEliece

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#1515]
**Describe the bug**
The weekly constant-time tests (linked to from https://openquantumsafe.org/dashboard.html) are failing on Classic McEliece.

**To Reproduce**
1. Go to https://openquantumsafe.org/dashboard.html
2. Click on liboqs -> GitHub Actions -> "Weekly constant time tests"

**Comment by baentsch** [comment]
FWIW, here's a good write-up how to reproduce/test/fix locally: https://github.com/open-quantum-safe/liboqs/issues/1278
