### ISSUE TITLE
Massive McEliece performance changes

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1518]
As #1470 merged, the performance characteristics of McEliece changed massively and not very coherently:

- KeyGen got massively better for 3xxx, somewhat better for 4xxx and slightly improved for non-reference code of the 8xxx variants (reference code performance fell):

![grafik](https://github.com/open-quantum-safe/liboqs/assets/57787676/36dfbd11-c2de-403a-b91f-5b4b345af5d9)

- Encaps performance fell pretty consistently in all variants -- except for the "reference" (non-optimized) code (double dashed lines below):  

![grafik](https://github.com/open-quantum-safe/liboqs/assets/57787676/23d1f412-fe7d-4405-95da-12bc9bee5a6e)

- Decaps: These are the most drastic changes: Reference code dropped to nearly 0 performance; optimized code got somewhat better:

![grafik](https://github.com/open-quantum-safe/liboqs/assets/57787676/297679e8-b60d-4ee9-9b47-d813ea39f99d)

--> Is this expected from "the literature" or worthwhile investigating?

**Comment by SWilson4** [comment]
@praveksharma You seem to be the go-to guy for McEliece; is this something you could take a look at?

**Comment by praveksharma** [comment]
Going through [this document](https://classic.mceliece.org/nist/[mceliece-mods3-20221023.pdf](https://classic.mceliece.org/nist/mceliece-mods3-20221023.pdf)) which describes the changes between Round 3 and Round 4 McEliece it isn't obvious to me why these changes should affect performance in this way. 

A change in performance is expected given that #1470 changes the compiler optimisation level for McEliece, but these changes are not in line with my expectations. 

While working on #1515 I observed that the constant time behaviour of McEliece has also significantly changed after #1470. I'm uncertain whether the two issues are related but I can investigate this alongside #1515.

**Comment by baentsch** [comment]
@praveksharma It seems #1515 is closed -- so any insights on this issue?

**Comment by dstebila** [comment]
Thanks Pravek for investigating thoroughly. Since the performance here matches the performance in SUPERCOP, I'd consider that an indication that our code is behaving as expected from a performance perspective.

I think then we can close this issue?

**Comment by praveksharma** [comment]
To be clear, from what I can tell the performance changes are introduced at implementation level by SUPERCOP and not at the algorithm level. As mentioned in my first comment, the McEliece authors list changes between round 3 and round 4 in [this document](https://classic.mceliece.org/nist/mceliece-mods3-20221023.pdf) and don't explicitly mention performance changes.
