### ISSUE TITLE
Update OpenSSL integration

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1539]
OpenSSL is adding the feature for [SHAKE to squeeze multiple times with different output sizes](https://github.com/openssl/openssl/pull/21511) which changes the [baseline in liboqs OpenSSL integration for SHA3](https://github.com/open-quantum-safe/liboqs/blob/0dafd4f02c5a8fc000502ae51005a9962b671860/src/common/sha3/ossl_sha3.c#L147-L162).
This issue is to propose using the new OpenSSL API to help validate it.

**Comment by Eddy-M-K** [comment]
Should not have referenced the GitHub issue within the commits themselves; please ignore the commits above.
