### ISSUE TITLE
Tests fail: cannot find test program files on Windows in the build tree with a VS generator

### ISSUE THREAD

**Issue by qnfm** [open-quantum-safe/liboqs#1555]
**Describe the bug**
Additional ctest (all of them) failed on windows

**To Reproduce**

Open x64 Native Tools Command Prompt for VS 2022
```
git clone https://github.com/open-quantum-safe/liboqs.git
cd liboqs
mkdir build && cd build
cmake ..
msbuild ALL_BUILD.vcxproj
msbuild tests\run_tests.vcxproj
```

**Expected behavior**
All test cases pass

**Environment (please complete the following information):**
 - OS: Windows 10 x64 1903
 - OpenSSL version: 3.1.2
 - Compiler version used: MSVC v143/Visual Studio 2022-ver 17.7.4
 - liboqs version: main branch

**Additional context**
VS log for Debug/x64 build

```
......
1>program_name = 'speed_sig'
1>
1>    def path_to_executable(program_name):
1>        path = "."
1>        if sys.platform.startswith("win"):
1>            if 'APPVEYOR_BUILD_FOLDER' not in os.environ: os.environ['APPVEYOR_BUILD_FOLDER'] = "."
1>            path = os.path.join(path, os.environ['APPVEYOR_BUILD_FOLDER'])
1>        path = os.path.join(path, get_current_build_dir_name(), "tests")
1>        for executable in [
1>            os.path.join(path, program_name),
1>            os.path.join(path, program_name + ".EXE"),
1>            os.path.join(path, program_name + ".exe")]:
1>                if os.path.isfile(executable):
1>                    return executable1>>       assert False, "Unable to find executable file {}".format(program_name)
1>E       AssertionError: Unable to find executable file speed_sig
1>
1>tests\helpers.py:150: AssertionError
1>=========================== short test summary info ===========================
1>FAILED tests/test_cmdline.py::test_sig[Dilithium5] - AssertionError: Unable t...
1>FAILED tests/test_alg_info.py::test_alg_info_kem[FrodoKEM-1344-SHAKE] - Asser...
1>FAILED tests/test_cmdline.py::test_kem[Classic-McEliece-348864] - AssertionEr...
1>FAILED tests/test_alg_info.py::test_alg_info_kem[Classic-McEliece-348864] - A...
1>FAILED tests/test_alg_info.py::test_alg_info_sig[Dilithium2] - AssertionError...
......
```

**Comment by qnfm** [comment]
By default, VS generate built test files in liboqs\build\tests\Debug\*(liboqs\build\tests\Release\*). But the helper.path_to_executable() try to find files in liboqs\build\tests\*. 
So the follow code snippet work:
```
    for executable in [
        os.path.join(path, program_name),
        os.path.join(path, program_name + ".EXE"),
        os.path.join(path, program_name + ".exe"),        
        os.path.join(path, "Debug",program_name + ".exe"),
        os.path.join(path, "Release",program_name + ".exe")]:
            if os.path.isfile(executable):
                return executable
```

Should I make a PR for that, or go through the test\*.py to fix all?

**Comment by baentsch** [comment]
Please check the effect of #1554 just merged: Would [this](https://github.com/open-quantum-safe/liboqs/blob/007219c3473dadfd188aed3616fcb2e36a0435fc/tests/helpers.py#L144-L146) resolve your issue? Reading the code I'd assume currently only by setting the environment variable "GITHUB_ACTIONS". If not, then yes, please propose a PR. As the OQS core team is not exactly comprised of "Windows experts" (or has that platform readily available), maybe @res0nance would be able (& willing?) to assist/review?
