### ISSUE TITLE
Docker pull sometimes fails in CI

### ISSUE THREAD

**Issue by SWilson4** [open-quantum-safe/liboqs#1569]
**Describe the bug**
`docker pull` has been flaky in both CircleCI and GitHub Actions, sometimes failing with a 503 status code.

**To Reproduce**
See https://github.com/open-quantum-safe/liboqs/actions/runs/6343943016 and https://app.circleci.com/pipelines/github/open-quantum-safe/liboqs/2854/workflows/18e3969f-ba5e-4aaf-b29b-e6b19634608a.

**Expected behavior**
`docker pull` should complete successfully, as it usually does.

**Additional context**
As of now, this is a very low urgency issue, and workflows usually pass when re-run. (Maybe a one-day problem? We'll see.) That said, if it persists, it will get in the way of our development work, so it's worth tracking.

**Comment by baentsch** [comment]
This indeed looks like a --hopefully very rare-- infrastructure problem -- I do not see what we can do at `liboqs` level to fix this -- short of moving off docker hub with the CI images: Is that the proposal? If so, where to?

**Comment by SWilson4** [comment]
Since `docker pull` hasn't (at least as far as I've seen) been a problem other than that one day last week, I think this issue can safely be closed.
