### ISSUE TITLE
Update to use OpenSSL 3

### ISSUE THREAD

**Issue by chenrui333** [open-quantum-safe/liboqs#1579]
OpenSSL 1.1.1 is already EOL this September, https://www.openssl.org/blog/blog/2023/09/11/eol-111/, needs to update to use OpenSSL 3

**Comment by dstebila** [comment]
Can you explain further what you mean in this issue?  liboqs already works with OpenSSL 3 and we have the oqs-provider project which integrates algorithms from liboqs with OpenSSL 3.

**Comment by baentsch** [comment]
@dstebila already pointed out that `liboqs` has no up- or downstream dependencies on OpenSSL111/works with&for OpenSSL3.

> needs to update to use OpenSSL 3

therefore is not sufficiently clear as a problem statement, so closing this issue in consequence. Please consider opening a [bug report](https://github.com/open-quantum-safe/liboqs/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=) with more details if you disagree, @chenrui333 .
