### ISSUE TITLE
Fix Windows build warnings

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#159]
The Windows build has a bunch of compiler warnings (see for example https://ci.appveyor.com/project/dstebila/liboqs/build/1.0.11/messages).  These should be fixed.  We should also see if we can configure the AppVeyor build so that it fails on warnings to catch these automatically in the future.

**Comment by christianpaquin** [comment]
PR #169 fixes all but one warning that I see (the last one is a linker warning due to duplicated definitions of some newhope constants; I'll look more into fixing it).

**Comment by vsoftco** [comment]
@christianpaquin There are no more warnings now, and added "Treat warnings as errors". Changes are pushed into your branch "Windows-build-august-2017".

**Comment by dstebila** [comment]
Closed by #169
