### ISSUE TITLE
Clarify supported platforms

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#1594]
We should agree on which platforms we support -- architectures, operating systems, compilers. This should be reflected in our documentation and in our continuous integration tests.

**Comment by baentsch** [comment]
Agreed. Should the discussion about this take place in this issue or in the [open discussion on the topic](https://github.com/orgs/open-quantum-safe/discussions/1583)?

**Comment by baentsch** [comment]
Also the [CI environment documentation](https://github.com/open-quantum-safe/liboqs/wiki/Contributing-guide#continuous-integration-ci-testing) needs to be brought in line with actual testing (as per the decision here).

**Comment by dstebila** [comment]
Do we consider this closed by #1605?

**Comment by baentsch** [comment]
> Do we consider this closed by #1605?

I would. But you opened the issue and should decide.
