### ISSUE TITLE
Add NewHopeSimple key exchange method

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#161]

**Comment by tlepoint** [comment]
@dstebila Is there a public implementation of NewHopeSimple?

**Comment by dstebila** [comment]
Not yet, as far as I know.  When I created this I thought there was but now I think there isn't.  So perhaps I should delete this issue for now?

**Comment by dstebila** [comment]
Will be done as part of overall NIST submission incorporation.
