### ISSUE TITLE
version problem

### ISSUE THREAD

**Issue by Majidk409** [open-quantum-safe/liboqs#1616]
/usr/local/lib/python3.10/dist-packages/liboqs_python-0.9.0-py3.10.egg/oqs/oqs.py:75: UserWarning: liboqs version 0.10.0-dev differs from liboqs-python version 0.9.0

**Comment by Majidk409** [comment]
needs urgent help don't know what to de new to PQC

**Comment by Martyrshot** [comment]
As the warning states, you are using the developer version of liboqs (0.10.0-dev), which is too new for the python bindings (0.9.0). This is just a warning though, so it shouldn't cause any issues? Are you experiencing any issues other than the warning?

If you want the warning to go away, then you need to use [liboqs 0.9.0](https://github.com/open-quantum-safe/liboqs/tree/0.9.0).
