### ISSUE TITLE
Eliminate Travis

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1627]
The reported Travis state is extremely misleading: It is shown as passing, while in reality, no test has apparently been running at all for "about a year":

![grafik](https://github.com/open-quantum-safe/liboqs/assets/57787676/302d8293-cd87-446c-880f-939915f9d9c9)

This may be due to a change in Travis policy [for the liboqs project](https://app.travis-ci.com/github/open-quantum-safe/liboqs) (the banner is only visible when logging in): 
![grafik](https://github.com/open-quantum-safe/liboqs/assets/57787676/dc94a3d8-5e9b-468f-8650-ca01163b9b2e)

This issue therefore suggests to completely remove Travis from CI reporting until this is fixed. 

Travis is used exclusively for testing of IBM platforms (PPC and S390), so tagging @bhess and @planetf1 for comments. Also tagging @dstebila as #1605 documenting platform support status still is open...

**Comment by bhess** [comment]
Thanks @baentsch for opening the issue. I've sent an inquiry to TravisCI, hope it can be fixed.

**Comment by bhess** [comment]
The travis build is now re-enabled, see current error state:

![image](https://github.com/open-quantum-safe/liboqs/assets/149199/d4713c43-d20c-4d28-9e87-8031245c152e)

I've created PR #1629 with a small update that makes the builds pass again.
