### ISSUE TITLE
Algorithm datasheet for Picnic and SIDH

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#163]
Christian, I would like to have "algorithm datasheets" providing a bit more information about each algorithm in liboqs (e.g., https://github.com/open-quantum-safe/liboqs/blob/master/docs/Algorithm%20data%20sheets/kex_lwe_frodo.md).  Can I ask you to make up something similar for Picnic?  It doesn't have to match exactly, use your judgement on what information is appropriate for a signature scheme.

**Comment by christianpaquin** [comment]
Yes, certainly. What about SIDH?

**Comment by dstebila** [comment]
Good point!  I've changed the issue title to reflect that.

**Comment by christianpaquin** [comment]
Just submitted PR #166. Thanks for your input Deirdre (@dconnolly); I've pulled some content from your file, and merged it with the feedback from our team.
