### ISSUE TITLE
Improve CI for macOS on Apple Silicon

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#1630]
Due to poor CI support this is currently a Tier 3 system according to our PLATFORMS.md document, but it should be better.

https://github.com/open-quantum-safe/liboqs/pull/1605#discussion_r1414029843

**Comment by SWilson4** [comment]
@dstebila @baentsch It looks it should now be feasible to use an M1 runner through GitHub actions: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source.

**Comment by dstebila** [comment]
> @dstebila @baentsch It looks it should now be feasible to use an M1 runner through GitHub actions: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source.
> 
> Edit to add: The M1 runner outperforms the Intel runner in a (very) limited `oqs-provider` test run: https://github.com/open-quantum-safe/oqs-provider/actions/runs/7846813573

It would be great to start using this and move away from our ad hoc solution involving one of our own machines.

**Comment by baentsch** [comment]
> It would be great to start using this and move away from our ad hoc solution involving one of our own machines.

We presently do that basically for profiling (in the process also testing). Indeed it would be nice to also do that on github (weekly run) if we decide to keep that sub project alive...

**Comment by SWilson4** [comment]
Related to today's meeting: GitHub Actions does seem to have Arm runners, which are currently in private beta: https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions

A GitHub executive recently mentioned in the OQS GitHub that they had helped to get LF projects additional GitHub features in the past—perhaps it's worth following up with them to see if we can get into the private beta?

**Comment by Martyrshot** [comment]
Worth mentioning: Someone from github joined the `pqca` discord and offered to talk to the admins about getting extra features. Ry Jones responded saying that he would contact them once they are back in office, so it might be worth talking to Ry about.

**Comment by SWilson4** [comment]
> Worth mentioning: Someone from github joined the `pqca` discord and offered to talk to the admins about getting extra features. Ry Jones responded saying that he would contact them once they are back in office, so it might be worth talking to Ry about.

This is what I meant to convey, but I typed "GitHub" instead of "Discord" :speak_no_evil:

**Comment by Martyrshot** [comment]
Ah, sorry. I wasn't sure if it was on a github discussion or not so I was trying to link the two. Sorry about that @SWilson4!

**Comment by SWilson4** [comment]
> Ah, sorry. I wasn't sure if it was on a github discussion or not so I was trying to link the two. Sorry about that @SWilson4!

No, all good, I was just clarifying my comment so people wouldn't look for a non-existent GitHub discussion :laughing: Thanks for pointing it out!

**Comment by planetf1** [comment]
Apologies to jump in.  2nd class m1/arm can be a pain (including lack of containers etc). Had it in other projects. You may have this in hand, but if you need any help with this item I'm happy to help out. great news to see additional arm runners in addition to macos on m1.

**Comment by baentsch** [comment]
> I'm happy to help out.

That would be very welcome, Thanks! Please add ARM and M1 github runners! Ideally [switching off the corresponding CCI tests](https://github.com/open-quantum-safe/liboqs/blob/main/.circleci/config.yml) at the same time.
