### ISSUE TITLE
Algorithm datasheet for Kyber

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#164]
Tancrède, I would like to have "algorithm datasheets" providing a bit more information about each algorithm in liboqs (e.g., https://github.com/open-quantum-safe/liboqs/blob/master/docs/Algorithm%20data%20sheets/kex_lwe_frodo.md). Can I ask you to make up something similar for Kyber? It doesn't have to match exactly, use your judgement on what information is appropriate to include.

**Comment by tlepoint** [comment]
Will do.

**Comment by tlepoint** [comment]
Closing, removing Kyber temporarily, cf. #211.
