### ISSUE TITLE
Appveyor builds failing on main

### ISSUE THREAD

**Issue by SWilson4** [open-quantum-safe/liboqs#1681]
The daily AppVeyor builds have been failing for some time. I've manually re-triggered builds on older commits that passed originally, and now they fail too. For example: [build 1](https://ci.appveyor.com/project/dstebila/liboqs/builds/48946257) vs [build 2](https://ci.appveyor.com/project/dstebila/liboqs/builds/49070481). It looks to me like the only difference between the two environments is that the successful build used OpenSSL 3.1.1 and the failed build used OpenSSL 3.2.0.

I don't think it's a great use of our time trying to debug this, especially given that our GitHub Actions Windows tests are passing with no issues (and are set up to run on PRs). The GH CI builds all use MSVC 19, so the only reason I see to keep AppVeyor around is to support cygwin / msys2. Is this something we want to do?

Aside: The most recent AppVeyor tests are failing in a lot more places because I missed disabling the long KAT tests in AppVeyor in #1560... oops. These are expected to fail for Falcon-1024 for the time being.

Tagging @baentsch @christianpaquin for input since this came up in a previous meeting.

**Comment by baentsch** [comment]
> so the only reason I see to keep AppVeyor around is to support cygwin / msys2. Is this something we want to do?

I'd argue the answer is encoded in [PLATFORMS.md](https://github.com/open-quantum-safe/liboqs/blob/main/PLATFORMS.md): No. Neither cygwin nor msys2 are documented there. If someone wants this they should speak up.

In addition, a [certain subproject does (github-based) cygwin builds](https://github.com/open-quantum-safe/oqs-provider/blob/7b21bd3bf35ba5fec53d5e5ab20f071b8afcd8b8/.github/workflows/windows.yml#L9)... So I'd vote for eliminating AppVeyor for good.
