### ISSUE TITLE
The "(maximum) length" words in `OQS_SIG` and `OQS_KEM` are misleading

### ISSUE THREAD

**Issue by wangweij** [open-quantum-safe/liboqs#1744]
All fields for the lengths of secret keys, public keys, signatures, ciphertexts, and shared secrets in the `OQS_SIG` and `OQS_KEM` structs claim they are "The (maximum) length". However, except for the signature length, all of them should be the exact lengths. In fact, only the `OQS_SIG_sign` function has an out parameter to retrieve the length of the signature.

**Comment by cothan** [comment]
Hi @wangweij , I'm not sure that I understand your point. 

The maximum length actually returns the length, designed for current and the future scheme that are variable in length, if it's variable in length, return the maximum length, otherwise return the exact length.

**Comment by SWilson4** [comment]
None of the schemes in liboqs have variable-length keys, in theory or practice. As you note, variable-length keys wouldn't fit with the APIs. You can safely use those as exact lengths.

**Comment by wangweij** [comment]
@SWilson4, thanks for the confirmation. Then, shall we remove the words from the header files?

**Comment by SWilson4** [comment]
> @SWilson4, thanks for the confirmation. Then, shall we remove the words from the header files?

That seems reasonable to me. Please feel free to create a PR and tag me as a reviewer.
