### ISSUE TITLE
Move from CCI to GH CI

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1795]
[...] move them over at your leisure.

_Originally posted by @ryjones in https://github.com/open-quantum-safe/liboqs/issues/1789#issuecomment-2111144389_

**Comment by ryjones** [comment]
@baentsch I set up an ARM64 runner: https://github.com/organizations/open-quantum-safe/settings/actions/runners/557

this is my local Mac. Feel free to start using it (and telling me what doesn't work). This user is not an admin, so colima (docker) may not work.
