### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Sokartecnologi** [open-quantum-safe/liboqs#1800]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20]
 - OpenSSL version [e.g., 3.0.2]
 - Compiler version used [e.g., clang 9.0.0]
 - Build variables used [e.g., "-DOQS_ALGS_ENABLED=STD"]
 - liboqs version [e.g. 0.7.2 or main branch]

**Additional context**

**Comment by dstebila** [comment]
Deleting as issue is empty.
