### ISSUE TITLE
Is there a way to measure performance or is there a benchmark for liboqs 

### ISSUE THREAD

**Issue by gabrofig** [open-quantum-safe/liboqs#1809]
Hi all,
As title says, is it possible to measure the performance in time of execution and memory usage (for example) of liboqs?

Thank you!

**Comment by SWilson4** [comment]
Hi @gabrofig, `liboqs` has a few test programs for measuring algorithm performance. See section 3 of the [quickstart guide](https://github.com/open-quantum-safe/liboqs?tab=readme-ov-file#linux-and-mac) for details.
