### ISSUE TITLE
unknown type OQS_SIG in sig_stfl.h included in oqs.h

### ISSUE THREAD

**Issue by lingxinh-aws** [open-quantum-safe/liboqs#1815]
**Describe the bug**
"#include <oqs/sig_stfl.h>" was added in oqs.h in [971773a](https://github.com/open-quantum-safe/liboqs/commit/971173ad82327ede5027b6d48e81bcaff92f417c#diff-9ba35166c0f1d2190622871ceb7f323735a1e7c7078d93994600bd5d85814bf5). It caused an error of "unknown type name 'OQS_SIG' " when compiling oqs-provider/oqsprov/oqs_sig.c, which includessig.h, which includes oqs.h. Then, OQS_SIG is referred in sig_stfl.h, but it is defined after #include <oqs/oqs.h> in the body of sig.h, so compilation failed.

**To Reproduce**
1. Git clone the oqs-provider
2. Run: cd oqs-provider
3. Run:  scripts/fullbuild.sh

**Expected behavior**
OpenSSL, liboqs and oqs-provider are all successfully built.

**Screenshots**
<img width="522" alt="sig_stfl_h_error" src="https://github.com/open-quantum-safe/liboqs/assets/94720905/26334e8f-3d67-4e03-9583-4563d318a377">

**Environment (please complete the following information):**
 - OS [ Amazon Linux 2 ]
 - OpenSSL version [3.3.0-dev]
 - Compiler version used [gcc 7.3.1]
 - Build variables used ["-DCMAKE_BUILD_TYPE=Debug"]
 - liboqs version [main branch]

**Additional context**

**Comment by baentsch** [comment]
Thanks for this report. Problem permeates through the complete OQS stack, see https://github.com/open-quantum-safe/oqs-provider/issues/427 and https://github.com/open-quantum-safe/oqs-demos/issues/281 . Possible work-around [discussed here](https://github.com/open-quantum-safe/oqs-provider/issues/427#issuecomment-2157249645). A better solution of course is needed, see [comment here](https://github.com/open-quantum-safe/liboqs/pull/1817#pullrequestreview-2106361120): downstream-triggering CI should have caught this; still wonder why it didn't (ideas @SWilson4 ?)

**Comment by SWilson4** [comment]
> Thanks for this report. Problem permeates through the complete OQS stack, see [open-quantum-safe/oqs-provider#427](https://github.com/open-quantum-safe/oqs-provider/issues/427) and [open-quantum-safe/oqs-demos#281](https://github.com/open-quantum-safe/oqs-demos/issues/281) . Possible work-around [discussed here](https://github.com/open-quantum-safe/oqs-provider/issues/427#issuecomment-2157249645). A better solution of course is needed, see [comment here](https://github.com/open-quantum-safe/liboqs/pull/1817#pullrequestreview-2106361120): downstream-triggering CI should have caught this; still wonder why it didn't (ideas @SWilson4 ?)

I believe that it would have, but I think we (I really, as I was the one who merged the PR) simply missed manually triggering the downstream tests before merge. The trigger was broken through the final stages of the review, but I believe it was fixed before merge, so the tests should have been run.

**Comment by SWilson4** [comment]
Resolved by #1820.
