### ISSUE TITLE
Decode FORS indices similarly to WOTS

### ISSUE THREAD

**Issue by GillonB** [open-quantum-safe/liboqs#1838]
Can we add coming changes to SPHINCS+ implementation to liboqs? Could be as a temporary branch as done in  https://github.com/sphincs/sphincsplus/pull/51. 

This change breaks forward/backward compatibility between old/new signatures.

**Comment by SWilson4** [comment]
Closing as this is superseded by https://github.com/open-quantum-safe/liboqs/issues/1894.
