### ISSUE TITLE
Update CODEOWNERS

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1843]
The [CODEOWNERS](https://github.com/open-quantum-safe/liboqs/blob/main/.github/CODEOWNERS) file triggering review(er)s seems to have fallen out of maintenance.

This issue is to suggest 
- bringing it back in line with current contributors/contributions
- documenting the need to keep the file current when doing major merges

**Comment by SWilson4** [comment]
For what it's worth, https://github.com/open-quantum-safe/tsc/pull/77 will make the CODEOWNERS file valid again by providing @crockeea and @alexrow with "write" access. This doesn't remove the need to update the file to reflect current code ownership, but it does improve the state of affairs.
