### ISSUE TITLE
Running `cmake -LA` changes library configuration

### ISSUE THREAD

**Issue by SWilson4** [open-quantum-safe/liboqs#1847]
**Describe the bug**
If `cmake -LA ..` is run between the library configuration (`cmake -GNinja <config options> ..`) and build (`ninja`) commands, the library configuration may be changed.

**To Reproduce**
From the `liboqs` directory:
```sh
rm -rf build && mkdir build && cd build
cmake -GNinja -DOQS_MINIMAL_BUILD="KEM_kyber_512;SIG_dilithium_2" -DCMAKE_BUILD_TYPE=Debug ..
ninja
gdb -ex "b pqcrystals_dilithium2_avx2_keypair" -ex r --args ./tests/test_sig Dilithium2
```

![avx2_enabled](https://github.com/user-attachments/assets/c0d800c7-9ff6-4a60-bda9-13f1ab376f6f)

As expected, the breakpoint is hit: the AVX2 code is enabled in the build.

Here is the exact same command sequence with `cmake -LA ..` added between config and build:
```sh
rm -rf build && mkdir build && cd build
cmake -GNinja -DOQS_MINIMAL_BUILD="KEM_kyber_512;SIG_dilithium_2" -DCMAKE_BUILD_TYPE=Debug ..
cmake -LA ..
ninja
gdb -ex "b pqcrystals_dilithium2_avx2_keypair" -ex r --args ./tests/test_sig Dilithium2
```

![avx2_disabled](https://github.com/user-attachments/assets/0ad3c11e-e6ee-4560-803f-edf72ac9df5a)

The breakpoint cannot be set: the AVX2 code is disabled. Also note that the number of targets built is greater in the first case (127) than in the second (101).

**Expected behavior**
The `cmake -LA ..` call should have no side effects.

**Screenshots**
See above

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - OpenSSL version: 3.0.2
 - Compiler version used: GCC 11.4.0
 - Build variables used: see above
 - liboqs version: `main`, at commit 5670edf59fa7a910654b9171229b7dc1ea7ece4c

**Additional context**
We use this pattern [basically everywhere](https://github.com/open-quantum-safe/liboqs/blob/4cc88845e8bb66dca20cd61ff88c2162f38c3230/.github/workflows/unix.yml#L147) in CI to print config variables, so the bug's impact could have been huge. Thankfully, it looks like there were no failures hidden by the bug. [This branch](https://github.com/open-quantum-safe/liboqs/tree/sw-cmake-la) removes all occurrences of `cmake -LA ..` from CI, and everything passes. Based on some [older](https://github.com/open-quantum-safe/liboqs/pull/1618) [investigation](https://github.com/open-quantum-safe/liboqs/issues/1666), I think we can infer that the weekly tests are unaffected as well.

I believe that the issue lies in our filtering logic when an option like `OQS_MINIMAL_BUILD` or `OQS_ALGS_ENABLED` is set. I'll investigate further.

**Comment by SWilson4** [comment]
This seems to me like something we should fix before the next release. Thoughts @dstebila @praveksharma @bhess?

**Comment by dstebila** [comment]
Seems peculiar, and worth fixing.  I notice from the [cmake documentation](https://cmake.org/cmake/help/latest/manual/cmake.1.html#options) that there's a command-line option `-N` which means "View mode only. Only load the cache. Do not actually run configure and generate steps."  So I wonder if `cmake -LA -N ..` would have the desired effect?  I'm not quite able to reproduce locally because running your gdb command on my Intel Mac seems to be throwing some errors. But I do notice that the number of files that ninja builds for me is as follows in the various scenarios:
- `cmake -GNinja -DOQS_MINIMAL_BUILD="KEM_kyber_512;SIG_dilithium_2" -DCMAKE_BUILD_TYPE=Debug ..; ninja`: 127 files
- `cmake -GNinja -DOQS_MINIMAL_BUILD="KEM_kyber_512;SIG_dilithium_2" -DCMAKE_BUILD_TYPE=Debug ..; cmake -LA ..`: 107 files
- `cmake -GNinja -DOQS_MINIMAL_BUILD="KEM_kyber_512;SIG_dilithium_2" -DCMAKE_BUILD_TYPE=Debug ..; cmake -LA -N ..`: 127 files

So I'm cautiously optimistic about the `-N` option.

**Comment by SWilson4** [comment]
`cmake -LA -N` does indeed produce the desired behaviour. Thanks! I've made a [PR](https://github.com/open-quantum-safe/liboqs/pull/1848) replacing all occurrences of `cmake -LA` with `cmake -LA -N` to get the quick fix out, at least.

As a long-term solution, I feel like we should refactor our CMake files so that this issue doesn't occur, `-N` switch or not. It's unintuitive behaviour (even we, the developers, didn't notice it for years), and I'm not sure we want to count on users remembering to pass `-N`.

**Comment by SWilson4** [comment]
As an aside, I've confirmed that the same issue arises when `-DOQS_ALGS_ENABLED=STD` is passed
> As a long-term solution, I feel like we should refactor our CMake files so that this issue doesn't occur, `-N` switch or not. It's unintuitive behaviour (even we, the developers, didn't notice it for some time), and I'm not sure we want to count on users remembering to pass `-N`.

Following up on this, I've confirmed that the unwanted side effects occur with `-DOQS_ALGS_ENABLED=STD` as well, which I would imagine is a more widely used config option than `OQS_MINIMAL_BUILD`.

**Comment by dstebila** [comment]
Can we close this since #1848 has landed?

**Comment by SWilson4** [comment]
> Can we close this since #1848 has landed?

Seems reasonable to me.
