### ISSUE TITLE
Check that function input lengths match expected values

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#185]
Functions like `OQS_KEX_..._bob` and `OQS_KEX_..._alice1` take public messages as input and include a length field.  Each implementation has its own expectations on what that length field should be.  We are not consistently checking to make sure that the supplied length field is equal to the expected length field for that algorithm.  We should check all our algorithms for this.

See forthcoming pull request from @mvd-ows for an example in kex_code_mcbits.

**Comment by mvd-ows** [comment]
https://github.com/open-quantum-safe/liboqs/pull/186

A proper analysis would have to examine how the public message is being processed by the KEX algorithm on the receiving end. Special focus should be on examining public message blobs to see if they include fields that contain offsets or sizes.

**Comment by truth-quark** [comment]
Should we close this issue as KEX is being removed?
