### ISSUE TITLE
Create a GitHub project board for issue tracking

### ISSUE THREAD

**Issue by ajbozarth** [open-quantum-safe/liboqs#1855]
As discussed in this week's OQS call (July 23rd) we want to set up a GitHub project board for tracking issues status with some basic automation. The board should have 3 buckets, one for all open issues, another for issues currently being worked on and a third for closed issues. New issues would automatically be added to the first bucket, moved to the second bucket when a PR is opened that would close the issue and then move to the final bucket when it is closed.

**Comment by ajbozarth** [comment]
I've created https://github.com/orgs/open-quantum-safe/projects/7/views/1 that has the automates adding issues and moving to done when closed, but the automation around moving to "In Progress" is not supported by default workflows and will have to be handled with GitHub Actions instead. This will require a PR to add a new action config, which I will open once I refresh my memory on writing that config.

As it is now though the project board is ready for any manual editing and prioritization by maintainers. They just have to drag and drop the issue in the order they should be prioritized.

@dstebila or @ryjones as a triage member I was able to create the project, but only org owners can make it public (it defaults to private) for others to see. If one of you could update the visibility for me, it is found in the settings for the project under the "Danger zone"

**Comment by ryjones** [comment]
@ajbozarth done.

**Comment by dstebila** [comment]
I think you mentioned have a column in between "Todo" and "In progress" which was something like "Prioritized" -- meaning someone wants it to be done, but it is not yet assigned / in progress?

**Comment by ajbozarth** [comment]
> I think you mentioned have a column in between "Todo" and "In progress" which was something like "Prioritized" -- meaning someone wants it to be done, but it is not yet assigned / in progress?

The items can be ordered within a column based on priority (anyone with triage rights should be able to reorder iiuc). That was the prioritization @maximilien and I were talking about. If you want we can add a Priority column though, in fact we could rename "To Do" to "Icebox" as @maximilien originally suggested and create a new column (maybe even "To Do" again) that represent issues that need to be work on but are not yet picked up.

**Comment by ajbozarth** [comment]
I opened #1856 as a follow up to discuss adding more automation as I detailed above. As such once we come to a decision on the columns we want we can close this issue

**Comment by ajbozarth** [comment]
Based on discussion in todays call we will leave the board as is for now and let maintainers play with it for a while before we start tinkering with it to improve the process
