### ISSUE TITLE
Add a Wiki page with C examples of using liboqs

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#187]
We should add a page in the Wiki with some examples of using liboqs in C programs.  This would include conventions on how to request parameters, how to do set up the RNG, what arguments to pass in to functions, who is responsible for freeing variables (and which functions to use to free them - OQS_KEX_alice_priv_free, OQS_MEM_secure_free).

**Comment by vsoftco** [comment]
Minimal example is in the wiki now

**Comment by dstebila** [comment]
Thanks Vlad!!  

What is the `#include <../src/common/common.h>` for?  Should it use `#include <oqs/common.h>` instead?

**Comment by dstebila** [comment]
Also, what would you think about putting this example inside the test folder of liboqs and building it alongside everything else in Travis to ensure it stays functional and up-to-date?

**Comment by vsoftco** [comment]
@dstebila Will do. I'll use `<oqs/common.h>`, the previous one was used in `test_kex.c` which was the initial code I stripped down.

**Comment by vsoftco** [comment]
I will also add soon a signature example.

**Comment by vsoftco** [comment]
@smashra Hi Shravan, can you please give me a hand with adding those 2 minimal examples (`minimal_kex_oqs` and `minimal_sig_oqs`) in the test suite? I'm not entirely familiar with how the whole "autoconf" stuff works...

**Comment by smashra** [comment]
I'll take a look.
