### ISSUE TITLE
Mayo breaks weekly CTCI

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1870]
[Failure](https://github.com/open-quantum-safe/liboqs/actions/workflows/weekly.yml) should be fixed before next release. Tagging @bhess in case you're not aware.

**Comment by SWilson4** [comment]
Closing as completed by #1852 as the most recent test run [passed](https://github.com/open-quantum-safe/liboqs/actions/runs/10127508684).
