### ISSUE TITLE
overflow in tests/example_sig_stfl.c

### ISSUE THREAD

**Issue by wangweij** [open-quantum-safe/liboqs#1886]
**Describe the bug**

    70		sk_fname = malloc(strlen(method_name) + strlen(".sk"));
    ....
    78		strcpy(sk_fname, method_name);
    79		strcat(sk_fname, ".sk");

Here, the size of `sk_fname` is only enough to contain `method_name` and ".sk" but not the zero at the end of ".sk".

**To Reproduce**
This is a coding error.

**Suggested Fix**

    -	sk_fname = malloc(strlen(method_name) + strlen(".sk"));
    +	sk_fname = malloc(strlen(method_name) + strlen(".sk") + 1);

**Comment by SWilson4** [comment]
Thanks for the report! Created #1887 to fix.
