### ISSUE TITLE
Re-activate Travis CI for Tier-3 IBM platforms

### ISSUE THREAD

**Issue by SWilson4** [open-quantum-safe/liboqs#1888]
Travis CI builds have been failing with no output for some time now. Pinging @bhess, who I believe maintains the Travis setup.

**Comment by bhess** [comment]
Thanks for reporting @SWilson4 . I've created a ticket with TravisCI about the issue.

**Comment by bhess** [comment]
Opened #1901 to disable TravisCI. I'd suggest to keep this issue open to allow to revert the change if the ticket at TravisCI is fixed.

**Comment by SWilson4** [comment]
In https://github.com/open-quantum-safe/liboqs/pull/1909 I propose that we remove s390x and powerpc from PLATFORMS.md, since we presumably won't be able to run release tests on those platforms for 0.11.0. We will want to add them back whenever Travis is up and running again.

**Comment by dstebila** [comment]
Has this been resolved by #1988?

**Comment by SWilson4** [comment]
Indeed it has.
