### ISSUE TITLE
ML-DSA: integrate final standard

### ISSUE THREAD

**Issue by bhess** [open-quantum-safe/liboqs#1891]
The final standards were published today: [FIPS203](https://csrc.nist.gov/pubs/fips/203/final) and [FIPS204](https://csrc.nist.gov/pubs/fips/204/final).

This is to track the integration of the updated algorithms.

I'd suggest the following steps:

- Pull update from pq-crystals upstream once available
- The current ML-DSA-ipd/ML-KEM-ipd implementations would be dropped
- Integrate test vectors from NIST [ACVP repository](https://github.com/usnistgov/ACVP-Server/tree/master/gen-val/json-files)

update (Aug 22):
- pq-crystals/kyber [upstream](https://github.com/pq-crystals/kyber) has been updated
- ML-KEM / ML-DSA OIDs have been [published](https://csrc.nist.gov/projects/computer-security-objects-register/algorithm-registration)
- [ACVP repository](https://github.com/usnistgov/ACVP-Server/tree/master/gen-val/json-files) has been updated
- #1899 integrates ML-KEM and ACVP vectors

Update (Aug 27):
ML-KEM landed in main, remaining is ML-DSA integration

Update (Sep 5):
ML-DSA is available upstream: https://github.com/pq-crystals/dilithium

**Comment by baentsch** [comment]
On item1, any timeline as to when upstream will make them available? Would it make sense to do 0.11.0 (or maybe finally a 1.0.0!) after they landed?

**Comment by bhess** [comment]
> The NIST ACVP repository hasn't been updated with new vectors. Do you know when will that happen?

According to [this message](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/s_Wez9FanHw/m/2VcIE5skBgAJ?utm_medium=email&utm_source=footer) on the pqc-forum, a fixed version should be released today.

**Comment by dstebila** [comment]
Tying into [Roadmap discussion](https://github.com/orgs/open-quantum-safe/discussions/1892)

**Comment by obronchain** [comment]
Hi all, 

Also according to [this message](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/vybKwrXx53k/m/jS2j3xCxBgAJ) on the pqc-forum, the CAVP will also integrate all the external API (around october 2024 ?). 

I would be very useful if LibOqs could support also all these APIs and are compatible will all the KATs.

**Comment by bhenning10** [comment]
It looks like pq-crystals merged changes to support the final spec. 
https://github.com/pq-crystals/dilithium/commit/cf998be4ade0014565305d3635a7b8317f2d4bd0

**Comment by yogappu** [comment]
> It looks like pq-crystals merged changes to support the final spec. [pq-crystals/dilithium@cf998be](https://github.com/pq-crystals/dilithium/commit/cf998be4ade0014565305d3635a7b8317f2d4bd0)

IMO these changes are not compatible with the ACVP vectors. The vectors are based on 'internal' API's as per FIPS204 and not the high level API's.

**Comment by abhinav-thales** [comment]
> It looks like pq-crystals merged changes to support the final spec. [pq-crystals/dilithium@cf998be](https://github.com/pq-crystals/dilithium/commit/cf998be4ade0014565305d3635a7b8317f2d4bd0)

IMO these changes are not compatible with the ACVP vectors. The vectors are based on 'internal' API's as per FIPS204 and not the high level API's.

Also refer comment from author here : https://github.com/pq-crystals/dilithium/issues/88#issuecomment-2333831981

**Comment by bhess** [comment]
Planning a draft PR later today.
There will still be some open points for a full integration: access to the 'internal' API to be able to run the ACVP vectors (planned upstream: https://github.com/pq-crystals/dilithium/issues/88#issuecomment-2333831981), and adding ACVP vectors for the 'external' API (planned by NIST as outlined by @obronchain above).

**Comment by baentsch** [comment]
Why did you close this @planetf1 ? #1919 didn't land afaik.

**Comment by planetf1** [comment]
@baentsch Sincere apologies. My error when scrolling through the project on a touch screen. Unintentional, should reopen. Thanks for spotting.

**Comment by johngray-dev** [comment]
I was wondering if you are planning to support the context string for ML-DSA when you release version 12.0 officially?   I took a look at your code, and it looks like the context String is supported internally, but not in your external API.  In our latest composite signatures draft https://datatracker.ietf.org/doc/draft-ietf-lamps-pq-composite-sigs/03/ we actually need to make use of the ML-DSA context String to give the draft stronger security properties.   If it will not be in the upcoming version 12.0, is there a timeline for ML-DSA context String support to be added?

**Comment by bhess** [comment]
Hi @johngray-dev, yes I'll update PR #1919 soon with a proposed API that supports providing the context string.
