### ISSUE TITLE
To begin w//

### ISSUE THREAD

**Issue by Zcero222** [open-quantum-safe/liboqs#1893]
https://github.com/open-quantum-safe/liboqs/blob/fc2264d150d0d94412c6ddb2f955c7077765556d/docs/algorithms/sig/sphincs.yml#L241

**Comment by Zcero222** [comment]
---+'''1
        2 DenominaToRR
          d
             2
                3
                   A.GOD.n.,,J.....64th st.pnp.bui bB. Range of flat motion in linear line contents.ndot. upland complete.  Note: with JN item would not be complete. A line of N controls 
A line of d now ______. An arrow up ^ with no attachment does not fold well.

**Comment by SWilson4** [comment]
Closed as spam; user blocked and reported.
