### ISSUE TITLE
Test files and test function's return value

### ISSUE THREAD

**Issue by smashra** [open-quantum-safe/liboqs#19]
I was thinking of creating a test sub folder to put all the test files there.
For now we have:

src/kex/test_kex.c
src/rand/test_rand.c

Test functions are returning 1 for success and 0 for failure.
When for e.g.
make test
is run it shows failure because it expects 0 for success.

**Comment by tlepoint** [comment]
The tests should answer 0 for success and 1 for failure - it works for me at least.

e.g. in `src/rand/test_rand.c`, we have
```return (success == 1) ? EXIT_SUCCESS : EXIT_FAILURE;```

**Comment by smashra** [comment]
Right.
I have to merge latest changes to my branch from master.
