### ISSUE TITLE
Weekly tests failing

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1906]
See e.g., re-run at https://github.com/open-quantum-safe/liboqs/actions/runs/10542663074

To avoid things like this right before a release, can I suggest we agree for someone (or better team) to check these (and other release-relevant) tests in the days leading up to a release such as not to have to scramble _at_ the release?

Tagging @praveksharma as this seems to be related to the libjade integration.

**Comment by SWilson4** [comment]
Based on the error message, I think CMake is complaining because there is no space between the config variables and the working directory (`..`):
```bash
cmake -GNinja -DOQS_DIST_BUILD=OFF -DOQS_OPT_TARGET=auto -DOQS_LIBJADE_BUILD=OFF..
```
