### ISSUE TITLE
Support FIPS 205

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#1917]
Anyone interested to add [SLH-DSA](https://csrc.nist.gov/pubs/fips/205/final) to the list of supported algorithms both in `liboqs` and `oqsprovider`? Also see https://github.com/IETF-Hackathon/pqc-certificates/pull/137 (in case OQS wants to provide a comparable level of functionality as BouncyCastle).

**Comment by SWilson4** [comment]
@baentsch, OK if I close this as a duplicate of https://github.com/open-quantum-safe/liboqs/issues/1894? (Or merge the two if there's a way to do that.)

**Comment by baentsch** [comment]
My mistake. Duplicate indeed.
