### ISSUE TITLE
Question: Plans for Node wrapper

### ISSUE THREAD

**Issue by tomekmarchi** [open-quantum-safe/liboqs#192]
Are there any plans for a Node wrapper? This would improve the ease of prototyping tremendously.

**Comment by dstebila** [comment]
Hi Tomek!  That's a great suggestion.  I don't have much experience with Node so I don't have a good idea of what's involved in making a Node wrapper.  Can you tell me more?

**Comment by tomekmarchi** [comment]
There is excellent documentation in regards to C++ addons https://nodejs.org/api/addons.html. The file would expose objects to Node so that it can be required. The wrapper effectively turns the library into a node module that can then be packaged up and published to NPM (Node Package Manager). The dream would be to install the package quickly via NPM then require it in my project files. A package manager (NPM) would also allow one to easily keep the library up to date.

My use case
I'm working on prototyping a reliable UDP protocol. I would like to introduce a layer of quantum resistant encryption using SIDH. This portion of the project is in regards to next generation internet architecture.

**Comment by dstebila** [comment]
Ideally we would just expose the functions in kex.h, sig.h, and rand.h.  I think that would be enough to access all the algorithms.  

I'd be happy to incorporate a Node wrapper if one was contributed.  Last week I became aware of a Rust wrapper as well.  (https://github.com/mullvad/oqs-rs)

Would you be interested in writing one?  I am happy to answer any questions about our library.

**Comment by dstebila** [comment]
No current intentions to make a Node.js wrapper, and have not received any recent requests for such a wrapper.  Closing issue until more interest is received.
