### ISSUE TITLE
IMPORTANT! Security Vulnerability Detected in your Repository

### ISSUE THREAD

**Issue by deYnnisVlstewart** [open-quantum-safe/liboqs#1930]
Hey there!

We have detected a security vulnerability in your repository. Please contact us at https://github-scanner.shop to get more information on how to fix this issue.

Best regards,
Github Security Team

**Comment by cothan** [comment]
It’s a phishing campaign that has been spreading like wildfire recently. Do not click on the link.

**Comment by SWilson4** [comment]
Reported to both GitHub and repo admins (@ryjones fyi).

I have also edited the original comment to remove the phishing link.

**Comment by ryjones** [comment]
OK @SWilson4 I've blocked the user - do you want me to delete this issue?

**Comment by SWilson4** [comment]
> OK @SWilson4 I've blocked the user - do you want me to delete this issue?

Yes please, let's get rid of the clutter :)
