### ISSUE TITLE
Compilation error: Cannot open include file: 'dlfcn.h'

### ISSUE THREAD

**Issue by fwh-dc** [open-quantum-safe/liboqs#1935]
**Describe the bug**
When building for windows on windows with VS19 I get the following compilation error:

```
20:58:05  C:\Users\****local\workspace\422-use-oqs-provider-main-branch\submodules\linphone-sdk\external\liboqs\src\common\ossl_helpers.c(7): fatal error C1083: Cannot open include file: 'dlfcn.h': No such file or directory
```

**Environment (please complete the following information):**
 - OS: windows, VS 19
 - OpenSSL version: -
 - liboqs version: main

**Comment by pi-314159** [comment]
Please also check #1768

**Comment by SWilson4** [comment]
Closing as a duplicate of #1768.
