### ISSUE TITLE
scan-build errors

### ISSUE THREAD

**Issue by ETeissonniere** [open-quantum-safe/liboqs#194]
Hey,
I have just runned `scan-build` from `clang` via `scan-build -analyze-headers --use-cc /usr/bin/clang --use-c++ /usr/bin/clang++ make -j4`, it found a few errors and I thought it may interests you.
This includes:
 -  2 double free
 -  1 memory leak
 -  2 dead assignments

![capture du 2017-11-23 15-27-32](https://user-images.githubusercontent.com/10683430/33177435-df5f98ac-d062-11e7-9af9-fce09bf49b67.png)

**Comment by xvzcf** [comment]
Having re-run this at [this commit](https://github.com/open-quantum-safe/liboqs/commit/25c9f8cf745c833fdac7536fa0765d4911435526) on master, there are 14 reported bugs. I'll investigate their validity as I move the build system to CMake.

**Comment by dstebila** [comment]
Noting that an old PR, #195, contained some code related to doing this in our old build system.  May want to replicate that work when working on this issue.

**Comment by baentsch** [comment]
Also closed by #1240
