### ISSUE TITLE
'ninja run_tests' fails due to memory leak

### ISSUE THREAD

**Issue by ashman-p** [open-quantum-safe/liboqs#1941]
**Describe the bug**
'ninja run_tests' fails due to memory leak

**To Reproduce**
1. build liboqs with OQS_USE_OPENSSL and OQS_USE_PTHREADS set to ON.
2. run 'ninja run_tests'
3.  See error
Snapshot:-
[ 80%] FAILED  tests/test_leaks.py::test_kem_leak[ML-KEM-512
[ 88%] FAILED  tests/test_leaks.py::test_sig_leak[ML-DSA-87] 

**Expected behavior**
Tests normally pass.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 20] 
 - OpenSSL version [e.g., 3.0.2] 3.3.3
 - Compiler version used [e.g., clang 9.0.0] GCC 9.4.0
 - Build variables used [e.g., "-DOQS_ALGS_ENABLED=STD"] OQS_ALGS_ENABLED=STD
 - liboqs version [e.g. 0.7.2 or main branch] 0.10.2-dev

**Additional context**
This test runs fine with OQS_USE_OPENSSL ON and OQS_USE_PTHREADS OFF

**Comment by baentsch** [comment]
@ashman-p FYI/linking to https://github.com/openssl/openssl/issues/21023#issuecomment-2390855564 that may also have a reading on this problem...

**Comment by aidenfoxivey** [comment]
Was this about 120 bytes?

**Comment by aidenfoxivey** [comment]
I've been using OpenSSL 3.3.2 3 Sep 2024 (Library: OpenSSL 3.3.2 3 Sep 2024) and had that experience.
