### ISSUE TITLE
CROSS KAT failures / potential endianness issue

### ISSUE THREAD

**Issue by bhess** [open-quantum-safe/liboqs#1961]
**Describe the bug**
KATs for CROSS fail on s390x after reenabling the Travis build for this platform in #1960.

S390x is the only big-endian platform in the CI pipeline, so I suspect an endianness issue in CROSS.

Tagging @rtjk 

**To Reproduce**
See https://app.travis-ci.com/github/open-quantum-safe/liboqs/jobs/627436707

**Comment by rtjk** [comment]
Thank yo for the catch @bhess! I'll look into this as soon as I'm done with #1958.
