### ISSUE TITLE
signed format used

### ISSUE THREAD

**Issue by maddin200** [open-quantum-safe/liboqs#1962]
File:
/src/kem/bike/additional_r4/decode.c line 265

Code:
for(uint32_t iter = 0; iter < MAX_IT; iter++) {
    const uint8_t threshold = get_threshold(&s);
    DMSG("    Iteration: %d\n", iter); // <-- signed format

**Comment by SWilson4** [comment]
This shouldn't be an issue: `int` is guaranteed to be large enough to represent every element of the range `[0, 256)`. Additionally, the `DMSG` macro only has an effect when the [`VERBOSE` variable is defined](https://github.com/open-quantum-safe/liboqs/blob/71324732640cf4451cab425ac5d80ed9fd41a3af/src/kem/bike/additional_r4/defs.h#L98), which we don't do to my knowledge.
