### ISSUE TITLE
Update patch documentation

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#197]
Shravan, I've pulled out the documentation on integration external implementations into liboqs into a Wiki page (https://github.com/open-quantum-safe/liboqs/wiki/Integrating-external-implementations-into-liboqs).  But I noticed there are some things in there which are probably out of date.  For example, it talks about patch0.patch being for the Makefile.am, but in #176 it looks like Makefile.am is always present.  Can you please take a look and update?

**Comment by smashra** [comment]
Updated the wiki.
