### ISSUE TITLE
"Can't find OpenSSL"

### ISSUE THREAD

**Issue by richsalz** [open-quantum-safe/liboqs#2014]
I am working on a fork of OpenSSL, QuicTLS (https://github.com/quictls/quictls). We are currently cleaning up a bunch of things to make the transition to `cmake` easier. One of the tests links against OQS and gets an error:
```
CMake Error at /usr/local/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR: (Required is at least version "1.1.1")
  (found /home/runner/work/quictls/quictls/libcrypto.so, )
Call Stack (most recent call first):
  /usr/local/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:601 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.31/Modules/FindOpenSSL.cmake:691 (find_package_handle_standard_args)
  CMakeLists.txt:133 (find_package)
```

Do have you any clues as to what I did wrong to break things?  Notably, `include/openssl/opensslv.h` is now subsumed into `include/openssl/configuration.h{.in}`. And tips or clues greatly appreciated!

**Comment by richsalz** [comment]
[submodule "oqs-provider"]
	path = oqs-provider
	url = https://github.com/open-quantum-safe/oqs-provider.git

Looking at our github repo we have https://github.com/open-quantum-safe/oqs-provider/tree/8c746d7e294d6948c2f361a8f2fa376a63a2db30

**Comment by SWilson4** [comment]
I suspect this is due to the fact that we used to [hardcode](https://github.com/open-quantum-safe/liboqs/pull/1873) `OPENSSL_ROOT_DIR` to `/usr` on Linux. Why, I don't know, but this has been fixed since liboqs version 0.11.0. Based on the version of oqs-provider, I'd assume it's building against liboqs 0.8.0.

Did you recently upgrade to a newer version of CMake? (Possibly via a distro upgrade.) CMake changed the way it searches for OpenSSL in a way that exposed our bug (the hardcoding) somewhere between versions 3.25 and 3.28. That would explain why you are only seeing this bug now.

**Comment by SWilson4** [comment]
Also, are you setting the `OPENSSL_ROOT_DIR` variable?

**Comment by richsalz** [comment]
I haven't even written a `cmakelist` file yet :). I'm just cleaning up our branch (removing old things; see the dozen PRs) to make it easier to write the cmake files.  Most PRs with the external test pass, like https://github.com/quictls/quictls/actions/runs/12185718584/job/33992602166?pr=139. Just this one branch which modified `opensslv.h` and other stuff, https://github.com/quictls/quictls/pull/142 and the OQS eternal test fails, https://github.com/quictls/quictls/actions/runs/12201564498/job/34040276358?pr=142#step:9:60

So I figured I broke something.  If you have any ideas or clues, let me know. Else you can just close this as "question answered" :)

**Comment by SWilson4** [comment]
> So I figured I broke something. If you have any ideas or clues, let me know.

If the test is passing on other branches in the same environment, then I wonder if something in the OpenSSL config changes caused CMake to not recognize the library as OpenSSL.

> Else you can just close this as "question answered" :)

Will do as it seems unlikely to be an OQS-specific issue. But I do hope you find the bug!

**Comment by richsalz** [comment]
FYI, it turns out that cmake looks for strings in `include/opensslv.h`which I merged into `configuration.h`. So for now I'll hack something in.
