### ISSUE TITLE
New release broke (again) tests when not using default build directory

### ISSUE THREAD

**Issue by iyanmv** [open-quantum-safe/liboqs#2018]
**Describe the bug**
Exactly the same issue as described in https://github.com/open-quantum-safe/liboqs/issues/1937, that was fixed with https://github.com/open-quantum-safe/liboqs/pull/1938

This time the new issue affects all the new tests added to `test_acvp_vectors.py` by https://github.com/open-quantum-safe/liboqs/pull/1919

I will provide a new patch to fix this issue on the new tests soon.

Would it be possible to modify the CI pipeline to build on a custom path to detect this kind of error before merging? What do you think?

**Comment by iyanmv** [comment]
> I think it would be nice to have—would you be willing to take a stab at adding it in #2019?

Alright, let me have a look.

**Comment by baentsch** [comment]
Thanks for bringing this (again) up @iyanmv -- and of course for fixing it! Reminds me of https://github.com/open-quantum-safe/oqs-provider/issues/545: CI along the whole chain (software and releases) could benefit from some further attention/improvement... Tagging @praveksharma as a heads-up for the next `oqsprovider` release.
