### ISSUE TITLE
Qustion what of presented algos for signtature can generate deteministic public key from presented exported Private key ?

### ISSUE THREAD

**Issue by mraksoll4** [open-quantum-safe/liboqs#2025]
what of presented algos for signtature can generate deteministic public key from presented exported Private key ?

and what call need use for it ?

**Comment by SWilson4** [comment]
The `liboqs` API does not support deriving a public key from a private key. Please see https://github.com/open-quantum-safe/liboqs/issues/1802 for more information.

**Comment by mraksoll4** [comment]
i try find any way to do that , as example for aplications  where we need deterministic privat and pubkeys - example blockchain projects where is deterministic privat key's and address it self - hash of pubkey or pubkey it self.

so there not usable "keypair" , but  i was think  if use "fixed seed"

**Comment by mraksoll4** [comment]
ok i customize it over seed. Now i get correct deteministic keys and unique signatures.

( work with falcon )
