### ISSUE TITLE
Travis failing on autotools branch

### ISSUE THREAD

**Issue by smashra** [open-quantum-safe/liboqs#21]
Which config file is meant to be updated for Travis to succeed.
I see .travis.yml on my local disk.

**Comment by tlepoint** [comment]
Modifying `.travis.yml` should be enough: you have to add the missing dependencies in the matrix (see `addons`).

**Comment by tlepoint** [comment]
Also, make sure that travis builds with the different GCC's. In **master**, the env variable `CC_OQS` allows this, but this could obviously be replaced by other options.

**Comment by smashra** [comment]
Can someone point me in the right direction to install autotools and autoconf packages on Travis.

For e.g.

I did something like this in .travis.yml, seems like it didn't work and sudo doesn't work either.

    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-5
        - autotools-dev
        - autoconf

**Comment by dstebila** [comment]
Closing issue: Travis now working on PR #20.
