### ISSUE TITLE
Question: How to make it can be use in Node.js

### ISSUE THREAD

**Issue by Elvenisboy** [open-quantum-safe/liboqs#218]
Well, this lib is very nice. But I am so confused that how to make it work. For many node developers, it seems too hard :cry:  . I can write some c code, so I wanna write it to be a module for Node.js. But, I really don't konw how to compile this lib. When I am testing minimal_sig_oqs.c, I try to use gcc to compile it like this:
```
gcc ./src/sig/minimal_sig_oqs.c  ./src/common/common.c ./src/crypto/aec ./src/crypto/aes/aes_c.c ./src/crypto/aes/aes_ni.c ./src/crypto/rand/rand.c ./src/crypto/rand_urandom_aesctr/rand_urandom_aesctr.c ./src/crypto/rand_urandom_chacha20/rand_urandom_chacha20.c ./src/crypto/sha3/sha3.c ./src/sig/sig.c ./src/sig_picnic/sig_picnic.c  -I ./include -o awesome.o  -lm

```

When I run `./awesome.o`

I will get a error:

```
ERROR: OQS_SIG_new failed!
Segmentation fault

```

I am so sad now :cry:

**Comment by vsoftco** [comment]
Please see the [Wiki](https://github.com/open-quantum-safe/liboqs/wiki/Minimal-example-of-a-post-quantum-signature-in-liboqs) on how to compile and run. First make sure that you properly configured the library: you need to run `autoreconf -i && ./configure && make clean && make` in `./liboqs`.

**Comment by Elvenisboy** [comment]
@vsoftco wow, it is so awasome :+1:  Thanks a lot. And so sorry that I only remember to see readme but forget wiki :smiley:
