### ISSUE TITLE
Extra memory allocated to Picnic private keys

### ISSUE THREAD

**Issue by tedeaton** [open-quantum-safe/liboqs#227]
Hi there,

When running tests (./test_sig, ./minimal_sig_oqs) for Picnic, (on macOS 10.13.3 & Ubuntu 16.04) the returned private keys for Picnic appear to be too long and contain uninitilized memory. e.g. for Picnic_L1_FS
``Private key (  82 bytes):  01E732656B417056D4C950E7E758A8BAEF3D37A7721413929B32E02BA75F5F79737871F293E8066AA97AE9126671AD9192000000000000000000000000000000000000000000000000000000000000000000``
or for Picnic_L5_FS,
``Private key ( 162 bytes):  051E551D66DCFF204891747174770ABFECA6EDEAB7208B7C3A9AF77D8259A6D272A18C94627B4D22A9FF2C505B1817D0CE92D4D6CBD583F1C9B2DCD3477E9C42C128898C54D2BCC5404D48C892FBF3AFAD4E8445D87A1830826B1C3E46570B166F4320B3FFE3F71D0000000000000000B216A63757AEACA52BD932115B03334079584BCE3593D162000000000000000001000000C000000003000000040000002E29``

It appears that this may be happening because extra space for the public key is being added to the private key _twice,_ once at line 102 of  [liboqs/src/sig_picnic/sig_picnic.c](https://github.com/open-quantum-safe/liboqs/blob/master/src/sig_picnic/sig_picnic.c):
``s->priv_key_len = (uint16_t)(PRIV_KEY_LEN[pctx->params] + PUB_KEY_LEN[pctx->params]); // priv key also contains pub key``
and also once at line 41 of  [liboqs/src/sig_picnic/external/picnic.h](https://github.com/open-quantum-safe/liboqs/blob/master/src/sig_picnic/external/picnic.h):
``#define PICNIC_PRIVATE_KEY_SIZE(p) (1 + 3 * LOWMC_BLOCK_SIZE(p))``

Changing line 102 of [liboqs/src/sig_picnic/sig_picnic.c](https://github.com/open-quantum-safe/liboqs/blob/master/src/sig_picnic/sig_picnic.c)  to simply
``s->priv_key_len = (uint16_t)(PRIV_KEY_LEN[pctx->params]);``
appears to fix the issue.

**Comment by christianpaquin** [comment]
Thanks Ted, we'll take a look.
