### ISSUE TITLE
We need some common cryptographic routines

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#24]
Some things in liboqs use standard cryptographic algorithms.  We should eventually have a common mechanism for these, either (a) our own API and collected implementations, or (b) linking against an existing library, e.g. OpenSSL or libnacl.

Algorithms needed:
- ChaCha20: in `rand_urandom_chacha20`
- AES-128 or AES-256: in `kex_lwe_frodo` branch
- SHAKE/SHA-3: in `kex_rlwe_newhope`

**Comment by sebastianv89** [comment]
I agree.

For the code-based solution I'm working on, I need a hash-function, but I'm agnostic as to which one. So SHA-3 would probably work fine.

**Comment by aparent** [comment]
I will work on adding SHAKE/SHA-3 next since it can also be used in NewHope.

**Comment by dstebila** [comment]
Right now we have a src/aes for AES, and then ChaCha20 and SHAKE are inside the directories where they're needed.  Maybe we can have a src/crypt and test_crypt to consolidate all these together?

**Comment by aparent** [comment]
If we can pull #47 which includes the factored out SHA code I can get these all consolidated.  

If there is an issue with pulling the Niederreiter  code I can probably try to make a new pull request which only includes the SHA part.

**Comment by dstebila** [comment]
We have decided to hold off on merging the Niederreiter code since its security has dropped due to a recent attack paper.  So doing a new PR that consolidates the other crypto code would be greatly appreciated.
