### ISSUE TITLE
[nist-branch] Make all algorithms use OQS_randombytes

### ISSUE THREAD

**Issue by tlepoint** [open-quantum-safe/liboqs#258]
I wanted to check the contributing.md file by adding a new submission, but the submission does not include `rng.c`. We need to provide a way to deal with that.

**Comment by dstebila** [comment]
We've got the global `OQS_randombytes` function in `src/common/rand.h` so I would use that.  I think we would use symbol renaming on the submission's binary to map its call to randombytes on to OQS_randombytes?

**Comment by tlepoint** [comment]
Ok good. We probably should, including for the existing implementations which are using an apparently uninitialized randombytes right now?

**Comment by dstebila** [comment]
Yes, we should make all algorithms in NIST branch use our OQS_randombytes function.

**Comment by dstebila** [comment]
Depends on #260

**Comment by dstebila** [comment]
Fixed by #260. I had a hard time renaming calls to randombytes in compiles libraries, so I added a global randombytes function which immediately calls OQS_randombytes.
