### ISSUE TITLE
Multithreaded build on ds-nist-branch

### ISSUE THREAD

**Issue by crockeea** [open-quantum-safe/liboqs#264]
I'm unable to build the ds-nist-branch on Ubuntu with `make -j4`. Build log is attached.
[buildlog.txt](https://github.com/open-quantum-safe/liboqs/files/1873281/buildlog.txt)

Private correspondence with Douglas resulted in the following diagnosis:

> I see the problem with multithreaded build on NIST branch.  For each Frodo target, we use the underlying Makefile rather than trying to build it directly.  That Makefile builds in place.  But there are 4 Frodo targets, so make -j4 tries to do each of those in parallel, and they end up messing each other up.  So we'll have to find some way to force those 4 targets to go sequentially. 

This ticket is to formally track progress on the issue.

**Comment by dstebila** [comment]
Eric, can you try if PR #275 now works for you with `make -j4`?

**Comment by dstebila** [comment]
Resolved by #275
