### ISSUE TITLE
Add Titanium algorithm to nist-branch

### ISSUE THREAD

**Issue by truth-quark** [open-quantum-safe/liboqs#299]
Original submission:
http://users.monash.edu.au/~rste/Titanium.html
https://github.com/raykzhao/Titanium

Titanium-CCA should be incorporated in the following strengths:
Std128
Med160
Hi192
Super256

**Comment by truth-quark** [comment]
For reference, the Titanium team has done some work for libOQS integration:
https://github.com/raykzhao/liboqs

**Comment by dstebila** [comment]
Okay, thanks. Maybe we can pull this in directly or maybe we will have to do some work to before pulling it in.  Worth checking into if it will save us some effort.

**Comment by dstebila** [comment]
Resolved by #344
