### ISSUE TITLE
Renaming C++ symbols appears to cause signing failure (nist-branch)

### ISSUE THREAD

**Issue by manvari** [open-quantum-safe/liboqs#307]
I've been working on integrating [GeMSS](https://csrc.nist.gov/CSRC/media/Projects/Post-Quantum-Cryptography/documents/round-1/submissions/GeMSS.zip) to `nist-branch`. GeMSS' implementations contain a C++ source file `chooseRootHFE.cpp`, within which NTL is called; all other source files are written in C. The Makefile provided by the submission authors compiles all implementations with `g++`.

This requires globally renaming the following symbols:
  - a C symbol to its C++ counterpart, `chooseRootHFE`, in `frobeniusMap.o`;
  - a C++ symbol to its C counterpart, `frobeniusMap`, in `chooseRootHFE.o`;
  - the C++ symbols for `crypto_sign(.*)` to `OQS_SIG_GeMSS_parametrization_\1`, the latter being C symbols defined in `src/sig/gemss/sig_gemss.c`.

After spending quite some time getting everything to compile, the KAT responses generated by `scripts/check_kats.sh` differ from those I generated with GeMSS' `PQCgenKAT_sign`. I suspect renaming symbols plays a role here. All libraries in use are being linked properly, so this is not the underlying issue.

Unless #298 is merged quickly, I will submit a PR to @christianpaquin's `cp-nist-branch-add-sig` as soon as I finish writing a gf2x build script (which GeMSS uses). This will be more useful than the description above.

Anyhow, submissions using C++ for NTL is something we need to deal with -- hence me opening this issue --. @dstebila @christianpaquin, I would like to have your input on this, please.

**Comment by manvari** [comment]
Oops -- you are spot on, @dstebila.

GeMSS indeed includes NIST's `rng.c` file which implements the deterministic RNG. After removing it from the compilation process and renaming the mangled C++ symbol for `randombytes` to the C symbol `randombytes`, KAT checks pass as expected.

**Comment by dstebila** [comment]
You're not the first person to have this problem.  I've added a "Troubleshooting" section at the end of `CONTRIBUTING.md` to highlight this information.
