### ISSUE TITLE
Copy .travis/free_check.sh from nist-branch to master-new-api

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#311]

**Comment by dstebila** [comment]
In nist-branch, free\_check only checked non-upstream files, but for master-new-api, it should check all files. It may be quite some work to change all free's to either OQS_MEM_secure_free or OQS_MEM_insecure_free, so we might have to chip away at this gradually and ignore some subdirectories at first.  

Perhaps we should also update free\_check (on both nist-branch and the copy to be made on master-new-api) to check for bzero or memset, as we would want to use OQS_MEM_cleanse for zero'ing out secret data.  (But there might be legitimate uses of memset for other purposes, so any memset checks would somehow have to be warnings not errors, or alternatively use some extra comment like I did with `// IGNORE free-check`.

**Comment by smashra** [comment]
Copied the script.

**Comment by dstebila** [comment]
That's not enough. The master-new-api build is broken because of all the free's that this script found, so you would have to make all the fixes to clear the build.  Please do that on another branch and request a code review when it's building cleanly and ready to merge.  I have to revert this now so I can merge master-new-api to master in a working state.

**Comment by dstebila** [comment]
Resolved by #334
