### ISSUE TITLE
(master branch) position dependent code

### ISSUE THREAD

**Issue by himsen** [open-quantum-safe/liboqs#315]
When trying to link with liboqs on OQS/OpenSSH I run into a configuration error. In config.log I see:

```
configure:14398: gcc -o conftest -g -O2 -pipe -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -ftrapv -fno-builtin-memset -fstack-protector-all -fPIE -I/home/himsen/Projects/oqs/liboqs/include  -D_XOPEN_SOURCE=600 -D_BSD_SOURCE -D_DEFAULT_SOURCE -L/home/himsen/Projects/oqs/liboqs/lib  -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack -fstack-protector-all -pie conftest.c -loqs -lcrypto -ldl -lutil -lz  -lcrypt >&5
/usr/bin/ld: /home/himsen/Projects/oqs/liboqs/lib/liboqs.a(librand_la-rand.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/home/himsen/Projects/oqs/liboqs/lib/liboqs.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
```

This indicates that either liboqs is not compited with ```-fPIC``` or there is some assembly code that is not position indpendent. I believe the former is not the case. I recall having this problem with some assembly code in a version of BIKE.

This was done on an Ubuntu machine:
$ uname -a
Linux himsen-VirtualBox 4.4.0-78-generic #99~14.04.2-Ubuntu [time information] x86_64 x86_64 x86_64 GNU/Linux

When I tried this on a OSX (10.10.5) I instead saw undefined symbols: [log.txt](https://github.com/open-quantum-safe/liboqs/files/2214012/log.txt)

Disabling ```picnic``` resolves the undefined symbols and OQS/OpenSSH also compiles. However, disabling ```picnic``` does not resolve the Ubuntu issue.

**Comment by dstebila** [comment]
Hi Torben, I ran into that problem yesterday myself and was able to fix it by building liboqs with

~~~bash
./configure --prefix=/path/to/install/liboqs/install --with-pic=yes
~~~

I forgot to push the update to the README.md for openssh-portable, but did just now.  Can you try and see if that fixes it for you?  Even if it does, it still suggests something is not quite right in our build of liboqs that we have to fix, but I am not sure exactly how.

**Comment by himsen** [comment]
Thanks Douglas, it solves the problem.
