### ISSUE TITLE
Add Lotus

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#316]
The Lotus implementation was MIT licensed as of mid Oct 2018, but the code needs some work before it can be added to nist-branch:
* A security patch needs to be applied for the Reference Implementation
* TODO: is the security patch required for the Optimised Implementation? If so, will the authors be providing this? (need to contact them)

Other:
* Add changes after the work to put the algorithms in alphabetic order is merged...

**Comment by truth-quark** [comment]
TODO: check if the security patch has been applied:
https://www2.nict.go.jp/security/lotus/impl.html

**Comment by truth-quark** [comment]
Mostly done, it requires feedback from the authors about the S/W licence.

**Comment by truth-quark** [comment]
The LOTUS team said they are going to release under an MIT licence. I've written back to find out the timeline on this.

**Comment by truth-quark** [comment]
LOTUS is now MIT licensed, see the news section here:
https://www2.nict.go.jp/security/lotus/index.html

**Comment by truth-quark** [comment]
The security patch is here: https://www2.nict.go.jp/security/lotus/LOTUS_fix.zip

I haven't checked if this patches the optimised version.

**Comment by dstebila** [comment]
Won't do since Lotus didn't make it to Round 2.
