### ISSUE TITLE
build-keccak-code-package.sh fails as GitHub repo has changed

### ISSUE THREAD

**Issue by truth-quark** [open-quantum-safe/liboqs#336]
Fresh liboqs builds now break due to a failed Keccak/GitHub dependency.

scripts/build-keccak-code-package.sh tries to download a now non-existent file:
https://github.com/gvanas/KeccakCodePackage/archive/master.zip

GitHub provides this instead: https://github.com/XKCP/XKCP

The build script fails @ line 21 as it's expecting different directory names than the one XKCP provides.

**Comment by dstebila** [comment]
Resolved by #337.
