### ISSUE TITLE
Cleanup duplicate rng.c

### ISSUE THREAD

**Issue by truth-quark** [open-quantum-safe/liboqs#345]
There's numerous duplicate copies of rng.c still in nist-branch.

In libOQS root:
$ find src/kem/ -iname "*rng.c"
src/kem/lima/upstream/optimized-implementation-master/NIST/EncapCCA/rng.c
src/kem/lima/upstream/optimized-implementation-master/NIST/EncCCA/rng.c
src/kem/lima/upstream/optimized-implementation-master/NIST/EncapCPA/rng.c
src/kem/lima/upstream/optimized-implementation-master/NIST/EncCPA/rng.c
src/kem/BIG_QUAKE/upstream/Reference_Implementation/BIG_QUAKE_5/rng.c
src/kem/BIG_QUAKE/upstream/Reference_Implementation/BIG_QUAKE_3/rng.c
src/kem/BIG_QUAKE/upstream/Reference_Implementation/BIG_QUAKE_1/rng.c
src/kem/sike/upstream/Additional_Implementations/SIKE-Weierstrass/symmetric/rng.c
src/kem/sike/upstream/Additional_Implementations/ARM64/SIKEp503/tests/rng/rng.c
src/kem/sike/upstream/Additional_Implementations/ARM64/SIKEp751/tests/rng/rng.c
src/kem/sike/upstream/Additional_Implementations/x64/SIKEp503/tests/rng/rng.c
src/kem/sike/upstream/Additional_Implementations/x64/SIKEp751/tests/rng/rng.c
src/kem/sike/upstream/Reference_Implementation/symmetric/rng.c
src/kem/sike/upstream/Optimized_Implementation/portable/SIKEp503/tests/rng/rng.c
src/kem/sike/upstream/Optimized_Implementation/portable/SIKEp751/tests/rng/rng.c
src/kem/newhopenist/upstream/Additional_Implementations/avx2/crypto_kem/newhope1024cpa/rng.c
src/kem/newhopenist/upstream/Additional_Implementations/avx2/crypto_kem/newhope512cpa/rng.c
src/kem/newhopenist/upstream/Additional_Implementations/avx2/crypto_kem/newhope1024cca/rng.c
src/kem/newhopenist/upstream/Additional_Implementations/avx2/crypto_kem/newhope512cca/rng.c
src/kem/newhopenist/upstream/Reference_Implementation/crypto_kem/newhope1024cpa/rng.c
src/kem/newhopenist/upstream/Reference_Implementation/crypto_kem/newhope512cpa/rng.c
src/kem/newhopenist/upstream/Reference_Implementation/crypto_kem/newhope1024cca/rng.c
src/kem/newhopenist/upstream/Reference_Implementation/crypto_kem/newhope512cca/rng.c
src/kem/newhopenist/upstream/Optimized_Implementation/crypto_kem/newhope1024cpa/rng.c
src/kem/newhopenist/upstream/Optimized_Implementation/crypto_kem/newhope512cpa/rng.c
src/kem/newhopenist/upstream/Optimized_Implementation/crypto_kem/newhope1024cca/rng.c
src/kem/newhopenist/upstream/Optimized_Implementation/crypto_kem/newhope512cca/rng.c
src/kem/frodokem/upstream/tests/rng.c
src/kem/saber/upstream/Optimized_Implementation_KEM/light_saber/rng.c
src/kem/saber/upstream/Optimized_Implementation_KEM/saber/rng.c
src/kem/saber/upstream/Optimized_Implementation_KEM/fire_saber/rng.c
src/kem/saber/upstream/Reference_Implementation_KEM/light_saber/rng.c
src/kem/saber/upstream/Reference_Implementation_KEM/saber/rng.c
src/kem/saber/upstream/Reference_Implementation_KEM/fire_saber/rng.c
src/kem/crystals-kyber/upstream/Optimized_Implementation/crypto_kem/kyber768/rng.c
src/kem/crystals-kyber/upstream/Optimized_Implementation/crypto_kem/kyber512/rng.c
src/kem/crystals-kyber/upstream/Optimized_Implementation/crypto_kem/kyber1024/rng.c

**Comment by dstebila** [comment]
nist-branch to be deprecated
