### ISSUE TITLE
Remove 'extern' keyword in OQS wrapper header files

### ISSUE THREAD

**Issue by truth-quark** [open-quantum-safe/liboqs#357]
Using 'extern' in the OQS algorithm wrapper header files isn't necessary for the keypair, encaps & decaps funcs.

```extern OQS_STATUS OQS_KEM_[alg]_cca_std_keypair(uint8_t *public_key, uint8_t *secret_key);```
can be:
```OQS_STATUS OQS_KEM_[alg]_cca_std_keypair(uint8_t *public_key, uint8_t *secret_key);```

**Comment by dstebila** [comment]
Resolved by #387
