### ISSUE TITLE
New rand_urandom_aes

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#36]
Hi Alex, I was thinking that it might be good to have a PRNG that is based on the new AES-NI code that you've added, since that might be faster for large amounts of PRNG expansion than the existing ChaCha20 code when AES-NI is available.  Would you have a chance to try that out?

**Comment by aparent** [comment]
Sure I can do that.  Want me to just implement AES-CTR?

**Comment by dstebila** [comment]
That would be great!
