### ISSUE TITLE
Add kat_kem on Windows and run KAT checks on AppVeyor

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#388]

**Comment by dstebila** [comment]
@christianpaquin does AppVeyor also run the KAT checks on Windows to see if it generates the right values?

**Comment by christianpaquin** [comment]
Ah, no it doesn't. That's a bit more work and I'm not sure how to easily enable that on Windows/AppVeyor. I'll take a look, but we should perhaps move that as a stretch goal for V1, in order not to block the release.

**Comment by dstebila** [comment]
Okay, I've created a separate issue to track this after we're done V1.
