### ISSUE TITLE
Algorithm datasheets for signature algorithms on master missing/wrong

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#399]
The Picnic datasheets on master refer to parameter sets named like `Picnic_1_316_FS`, whereas the code refers to parameter sets named like `picnic_L1_FS`, so they are causing `.travis/algorithm-datasheets-check.sh` to fail.

I've temporarily disabled signature checks in `.travis/algorithm-datasheets-check.sh`, so as part of this issue, please re-enable that.

**Comment by christianpaquin** [comment]
Fixed in PR #405.
