### ISSUE TITLE
Frodo in liboqs is slower than original Frodo code.

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#41]

**Comment by dstebila** [comment]
Some improvement comes from using OpenSSL for AES, but still not enough.  Maybe memory allocations are problematic?  Will do some microbenchmarks to try to isolate the problem.

**Comment by mofojed** [comment]
Found one source of performance gains:
https://github.com/open-quantum-safe/liboqs/pull/43

The old implementation used defined constants, while the new implementation uses parameters passed in. By caching some of the parameters there are significant performance gains.

**Comment by dstebila** [comment]
Resolved by #45.
