### ISSUE TITLE
Ensure wiki documentation is up to date

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#416]

**Comment by dstebila** [comment]
- [ ] https://github.com/open-quantum-safe/liboqs/wiki/Coding-conventions @smashra Please change/remove references to old APIs (`KEX`, `RAND`) and old algorithms (ntru, bcns14, mceliece, ...)
- [ ] https://github.com/open-quantum-safe/liboqs/wiki/Integrating-external-implementations-into-liboqs @smashra I think we would delete this now?  nist-branch has its own CONTRIBUTING.md, and I mean to write something similar for master I guess.
- [ ] https://github.com/open-quantum-safe/liboqs/wiki/Minimal-example-of-a-post-quantum-key-encapsulation-mechanism @truth-quark Check to make sure the code in this is up-to-date with the code in the master and nist branch example\_kem.c, and that it compiles against both master and nist branch, and that the text sensibly refers to both branches.
- [ ] https://github.com/open-quantum-safe/liboqs/wiki/Minimal-example-of-a-post-quantum-signature-in-liboqs @truth-quark Need to duplicate this in to two pages, one for master and one for nist, since they use slightly different signature APIs.  After duplicating, make sure the code in each is up-to-date with the code in the master and nist branch example\_sig.c, and that each compiles against master or nist branch respectively, and that the text sensibly refers to the respective branch.

**Comment by truth-quark** [comment]
The minimal KEM example code the same for NIST and master. The wiki page has almost the same code bar whitespace changes and a macro expansion. For simplicity, I'd like to link to the C example files directly (2 vs 3 things to maintain). Before doing so, is there a need to retain the wiki code block?

**Comment by truth-quark** [comment]
The PQ KEM example wiki has been updated & the tests worked on a Lunbuntu 18.04 VM. Does anyone feel like proof-reading the wiki content?

**Comment by truth-quark** [comment]
I've fixed the leftover references to 'minimal_kem_oqs' with the newer 'example_kem'. The CMake block has been removed following the discussion in the 2018-10-31 weekly meeting.

**Comment by truth-quark** [comment]
The SIG wiki pages have been updated & the code/cmds run cleanly on a Lubuntu 18.04 VM:
* https://github.com/open-quantum-safe/liboqs/wiki/Minimal-example-of-a-post-quantum-signature-in-liboqs
* https://github.com/open-quantum-safe/liboqs/wiki/Minimal-example-of-a-post-quantum-signature-in-liboqs-master-branch

Does anyone want to volunteer for a proof read? :-)

**Comment by truth-quark** [comment]
I've removed the old references to RAND/KEX etc in the coding conventions wiki:
https://github.com/open-quantum-safe/liboqs/wiki/Coding-conventions

One TODO exists. on the master branch there is something I don't recognise with the sigs. There's src/sig/sig_[algorithm] dirs and and src/sig/[algorithm] dirs. I'm not sure what the difference is between them.
