### ISSUE TITLE
libOQS returns struct with misaligned members

### ISSUE THREAD

**Issue by himsen** [open-quantum-safe/liboqs#420]
OpenSSH regression tests currently fail, cf. issue open-quantum-safe/openssh-portable#13. I have tracked the reason down to  the function `OQS_KEM_new` returning a struct with "misaligned" members (in lack of a better way to describe it).

This occurs independently of OpenSSH, as shown below. This could instead be a platform/compiler specific issue.

Running the small program below on my Ubuntu machine outputs the following:

```
Length pb: 434
Length sk: 402
Length ct: 16
Length ss: 4265680
```
Obviously, wrong.

```C
#include <stdio.h>

#include "oqs/oqs.h"

int main(int argc, char *argv[]) {
	
	OQS_KEM *oqs_kem = NULL;

	oqs_kem = OQS_KEM_new(OQS_KEM_alg_default);

	fprintf(stderr, "Length pb: %zu\n", oqs_kem->length_public_key);
	fprintf(stderr, "Length sk: %zu\n", oqs_kem->length_secret_key);
	fprintf(stderr, "Length ct: %zu\n", oqs_kem->length_ciphertext);
	fprintf(stderr, "Length ss: %zu\n", oqs_kem->length_shared_secret); 	

	OQS_KEM_free(oqs_kem);

	return 0;
}
```
Compile and run like this:
```
$gcc -I<path/to/liboqs/folder>/include -c oqs_test.c
$gcc -o oqs_test oqs_test.o -L<path/to/liboqs/folder>/lib -loqs
$./oqs_test
```
Any clues?

**Comment by dstebila** [comment]
I'm not able to reproduce on my Mac or Ubuntu 18.04 or 14.04 VMs.  What configuration are you using?

**Comment by himsen** [comment]
Sorry. I just found the cause of this. It was due to a contaminated repository. I pulled the new repository version of master-branch yesterday, ran `make clean` and re-build. Apparently, this did not remove the old library which I was still linking against when building the small program above and OpenSSH. Wicked...

You can close :).

**Comment by dstebila** [comment]
We recently added a new field in the OQS\_KEM (`OQS_KEM->alg_version`) which would might be why you were seeing misalignment between versions.
