### ISSUE TITLE
Cleanup nist-branch binary files

### ISSUE THREAD

**Issue by truth-quark** [open-quantum-safe/liboqs#424]
Using ```find . -exec file {} \; | grep -i elf``` finds ELF binaries.

Several binary files are included in nist-branch and could be removed:
* https://github.com/open-quantum-safe/liboqs/blob/nist-branch/src/kem/ledakem/upstream/Reference_Implementation/KEM/library/a.out
* https://github.com/open-quantum-safe/liboqs/blob/nist-branch/src/sig/qtesla/upstream/Reference_implementation/qTesla_III_size/test_qtesla
* https://github.com/open-quantum-safe/liboqs/blob/nist-branch/src/sig/qtesla/upstream/Reference_implementation/qTesla_p_I/test_qtesla
* https://github.com/open-quantum-safe/liboqs/blob/nist-branch/src/sig/qtesla/upstream/Reference_implementation/qTesla_III_speed/test_qtesla
* https://github.com/open-quantum-safe/liboqs/blob/nist-branch/src/sig/qtesla/upstream/Reference_implementation/qTesla_p_III/test_qtesla
*  https://github.com/open-quantum-safe/liboqs/blob/nist-branch/src/sig/qtesla/upstream/Reference_implementation/qTesla_I/test_qtesla

In ```src/sig/qtesla/upstream/Reference_implementation/``` there is:
* qTesla_III_size/PQCgenKAT_sign
* qTesla_p_I/PQCtestKAT_sign
* qTesla_p_I/PQCgenKAT_sign
* qTesla_III_speed/PQCtestKAT_sign
* qTesla_III_speed/PQCgenKAT_sign
* qTesla_p_III/PQCtestKAT_sign
* qTesla_p_III/PQCgenKAT_sign
* qTesla_I/PQCtestKAT_sign
* qTesla_I/PQCgenKAT_sig

**Comment by truth-quark** [comment]
PR raised here https://github.com/open-quantum-safe/liboqs/pull/428 :-)

**Comment by dstebila** [comment]
Resolved by #428
