### ISSUE TITLE
issue on .gitignore entry

### ISSUE THREAD

**Issue by geovandro** [open-quantum-safe/liboqs#432]
The entry "include/" in .gitignore by definition excludes all "include" directories over the whole project. In this case, the directory libOQS/src/kem/ledakem/upstream/Reference_Implementation/KEM/include
gets excluded if I want to start a new repo from libOQS.

The .gitignore file should use "/include" instead. This way it only refers to the folder "include" that is under the root of the project.

**Comment by dstebila** [comment]
Thanks Geo. Resolved in 8ffe700.
