### ISSUE TITLE
Continuous integration for ARM

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#444]
#443 added instructions for building liboqs on ARM.  But it would be good to have continuous integration tests that exercise building on ARM.  Christian wrote a few suggestions in #408.

**Comment by thomwiggers** [comment]
FYI, the strategy we used for [PQClean](https://github.com/PQClean/PQClean) to test big-endian systems could probably also be applied for ARM. There are [some limitations](https://github.com/PQClean/PQClean/issues/15/) though.
