### ISSUE TITLE
Picnic compilation fails for ARM

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#461]
When building on ARM (#460), if `--disable-sig-picnic` is removed from `scripts/arm-cross-compile.sh`, the build fails.

Compilation of `src/sig/picnic/external/picnic_iml.c` fails on lines 427 and 539 with "undefined reference to `rpl_malloc`"

**Comment by christianpaquin** [comment]
Delaying fixing this until the integrating of upcomming round 2 code.

**Comment by dstebila** [comment]
Have you had a chance to try the new Picnic code on ARM?

**Comment by christianpaquin** [comment]
I just tried the master build on a raspberry pi (armv7l) and all picnic tests passed.

**Comment by christianpaquin** [comment]
As discussed on the call yesterday, let's postpone the investigation of this after v0.2.

**Comment by dstebila** [comment]
What's the status of this?

**Comment by christianpaquin** [comment]
I need to look into this. There are new updates on Picnic that might solve this (I opened issue #588).

**Comment by dstebila** [comment]
Cross compilation to Raspberry Pi using the CMake toolchain in #618 works fine, and the resulting binaries run fine on a Raspberry Pi. Closing issue.
