### ISSUE TITLE
qTESLA segmentation fault on ARM

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#463]
When building on ARM (#460) and running with QEMU, qTESLA causes a segfault.

In particular, the commands

    qemu-arm -L /usr/arm-linux/gnueabi tests/example_sig
    qemu-arm -L /usr/arm-linux/gnueabi tests/test_sig

lead to segmentation faults.

(Interestingly, so does `tests/kat_kem` -- maybe it's related?)

**Comment by christianpaquin** [comment]
Delaying fixing this until the integrating of upcomming round 2 code.

**Comment by varmaricha** [comment]
When is this issue expected to be resolved? Are there any known workarounds yet?

**Comment by dstebila** [comment]
We're still waiting on integration of updates to qTESLA from Round 2 and the more recent August 2019 updates announced by the qTESLA team. @christianpaquin may have more info on timeline.

**Comment by christianpaquin** [comment]
Sorry, no specific date, but release is imminent.

**Comment by christianpaquin** [comment]
PR #548 passes on ARM.
