### ISSUE TITLE
Coverity scans

### ISSUE THREAD

**Issue by henrydcase** [open-quantum-safe/liboqs#464]
https://scan.coverity.com/ offers free service for open-source projects. For improved security, it may makes sense to enable coverity for libOQS

**Comment by dstebila** [comment]
Hi Henry,

We did have Coverity set up over a year ago on the `coverity_scan` branch, but haven't maintained it.  I've synced our current master branch with the `coverity_scan` branch.

But apparently Coverity is not working right now: https://community.synopsys.com/s/article/Coverity-Scan-Update
So we'll not get results until they're back up, which looks like it could be weeks.

**Comment by henrydcase** [comment]
thanks, I wasn't aware.
In such case I'll close this ticket as it is already done.
