### ISSUE TITLE
qTesla question - import and export  keys

### ISSUE THREAD

**Issue by liesware** [open-quantum-safe/liboqs#467]
I have these questions:
1-What is the right way to export keys and signatures to hex string?
2-What is the right way to import keys and signatures from hex string?

**Comment by dstebila** [comment]
liboqs' interface represents keys and signatures as byte arrays.  You would have to write your own functions, or rely on some other library's functions, to convert between byte arrays and hex strings.

**Comment by liesware** [comment]
Thank you so much,
