### ISSUE TITLE
SIKE implementation bug

### ISSUE THREAD

**Issue by kylon94** [open-quantum-safe/liboqs#469]
In file `kem_sike.c` in functions `OQS_KEM_sidh_p503_encaps` and `OQS_KEM_sidh_p751_encaps`

The private key is allocated in lines 123/201 but not set before being used in lines 124/202.

It contains whatever value is in the memory location (many times it is zero from testing).

Suggested fix: as space for the private key is allocated but not set, add a line to generate the private key before passing to compute the public key.

**Comment by christianpaquin** [comment]
Thanks @kylon94 for spotting this! Fixed in PR #472.
