### ISSUE TITLE
Key sizes and ciphertext sizes

### ISSUE THREAD

**Issue by vsoftco** [open-quantum-safe/liboqs#473]
Can we confirm that ALL public-key/secret-key sizes and ciphertext sizes are fixed for a given scheme? (unlike signature sizes, which can vary when signing twice with the same scheme)

**Comment by dstebila** [comment]
Now that I think about it, the actual keypair/encaps/decaps functions don't dynamically allocate memory, don't take lengths as inputs, and the don't return lengths as output; they assume that they are passed at least as much memory as the length\_* members indicate.  They may or may not use all of that memory, but we always treat that memory as opaque.  So I would say that yes, we can assume these sizes are fixed for a given KEM.

**Comment by dstebila** [comment]
Closing issue, reopen if you want to discuss more, @vsoftco .
