### ISSUE TITLE
Problems with zlib.h

### ISSUE THREAD

**Issue by jaimesaez97** [open-quantum-safe/liboqs#498]
Hi there!

I am trying to incorporate some QKD algorithms onto your library and I am installing liboqs on Debian 9.
At installing openssh-portable and run:
./configure --enable-pq-kex --enable-hybrid-kex      \
            --enable-pq-auth --enable-hybrid-auth    \
            --with-ssl-dir=< path-to-openssl >/include \
            --with-ldflags=-L< path-to-openssl >/lib   \
            --prefix=$OPENSSH_INSTALL                \
            --sysconfdir=$OPENSSH_INSTALL            \
            --with-liboqs-dir=$LIBOQS_INSTALL

it returns an error and I do not know how to approach it:
     checking zlib.h usability...no
     checking zlib.h presence..no
     checking for zlib.h...no
     configure: error: *** zlib.h missing - please install first or check config.log ***

¿Could anyone tell me how to fix it?

Thank you very much!!

**Comment by dstebila** [comment]
I'm guessing since you closed this, you resolved it, but if not, try: `apt-get install zlib1g-dev`
