### ISSUE TITLE
Key Format

### ISSUE THREAD

**Issue by JonathanWilbur** [open-quantum-safe/liboqs#507]
Based on what I see in the code, it looks like the key format is just a simple record-formatted concatenation of the public key and the seed for the NewHope algorithm. **Is there a standard key format for the NewHope public and private keys, and is this library implementing it if there is?** I know with RSA, keys are stored in a specific ASN.1 structure, and encoded in X.690 Distinguished Encoding Rules. I fear that using fixed-length fields as a key format could be detrimental later on.

**Comment by dstebila** [comment]
Hi Jonathan, the NIST PQC call for proposals specified an API where keys are byte strings, and the internal structure of that byte string is specified by the designers of the algorithm in their NIST submission.  So at this point we are treating them opaque byte strings exactly as specified in the original NIST submission.  It may be the case after the end of the NIST competition that some higher level standards bodies may come up with different substructures and encodings, but for now the byte strings from the original NIST submissions are definitive.

**Comment by JonathanWilbur** [comment]
Ah. Okay. I didn't know NIST specified the format. Thank you! Closing.
