### ISSUE TITLE
Integrate Falcon from PQClean

### ISSUE THREAD

**Issue by dimisik** [open-quantum-safe/liboqs#529]
Currently working on adding Falcon

**Comment by dstebila** [comment]
Great!  Hopefully it's just a case of adding to `scripts/copy_from_pqclean/copy_from_pqclean.yml` and then running `python3 scripts/copy_from_pqclean/copy_from_pqclean.py`.

**Comment by dimisik** [comment]
I tried it, it did not work, should I add also to the python3 script (paths etc.)? In any case I will try to do it manually also.

**Comment by dstebila** [comment]
Looks like you did everything correctly, the tests are failing due to alignment issues in the underlying Falcon C code.  It's also being discussed in PQClean/PQClean#221.

**Comment by saholmes** [comment]
> Currently working on adding Falcon

Hi, Is there an update on this?  Using Library and Falcon is only signature scheme currently missing.

**Comment by dstebila** [comment]
Still on my list of things to do, hopefully this week!

**Comment by saholmes** [comment]
> Still on my list of things to do, hopefully this week!

Great!  Happy to help where I can and test implementation.  Have been working with Falcon for a while now.  

All the best Stephen
