### ISSUE TITLE
Integrating Round5 from PQClean

### ISSUE THREAD

**Issue by lrubens** [open-quantum-safe/liboqs#534]
Hi,

I am working on implementing Round5 into liboqs using the script in scripts/copy_from_pqclean/copy_from_pqclean.py. I am having trouble with what PQCLEAN_DIR should be. That is causing errors on my end.

**Comment by dstebila** [comment]
Hi @lrubens, you should checkout a copy of PQClean on to your local computer, then set PQCLEAN_DIR to that directory, so the `copy_from_pqclean.py` script knows where to find the PQClean source files you've downloaded.

**Comment by dstebila** [comment]
Closing for now since PQClean does not currently have Round5.
