### ISSUE TITLE
Investigate circleci nightly build time out

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/liboqs#551]
The [circleci nigthly build ](https://circleci.com/gh/open-quantum-safe/workflows/liboqs/tree/master) has been failing since the merge of PR #547. The build times out after 10min. I suspect the 8 new algs (compressed SIDH/SIKE param sets) tip the compile time above the limit.

We should see if pushing the limit solves the issue; this [circleci support article](https://support.circleci.com/hc/en-us/articles/360007188574-Build-has-hit-timeout-limit) explains how.

**Comment by christianpaquin** [comment]
@dstebila, is that something you can change on the circleci test?

**Comment by dstebila** [comment]
Let's see if 0fd55565c4b60627d77aa2ab0c862858e4071f78 fixes it.

**Comment by dstebila** [comment]
0fd5556 does fix it.  Closing for now.
