### ISSUE TITLE
astyle -> clang-format?

### ISSUE THREAD

**Issue by tlepoint** [open-quantum-safe/liboqs#56]
In light of #53, I think it would be interesting to switch from astyle to clang-format. [Clang-format](http://clang.llvm.org/docs/ClangFormat.html) is both a library and a stand-alone tool aiming at automatically reformatting C sources files, and continus to be developed while astyle has not been updated since December 2014.

**Comment by aparent** [comment]
I agree. As a side benefit it is likely included by default on the build images so there would be no need to compile it foe each build.

**Comment by dstebila** [comment]
Okay, seems like a good idea.  Can you come up with some command line options?  Not a big deal if they don't reproduce the exact format, but I'd like to keep the main formatting principles.

**Comment by tlepoint** [comment]
I'll do it this week! Is there a PR I should wait to be merged for before doing it (bitroting)? I'll also refactor slightly the travis files by creating a `.travis` directory.

**Comment by dstebila** [comment]
I'd like to wait until #58 lands, which should be this Tuesday or Wednesday.  The other big one is #47, but I'm not sure what the status of it is from a cryptographic perspective, so you can go ahead without it.

**Comment by dstebila** [comment]
#58 has landed, so reformatting can go ahead.

**Comment by dstebila** [comment]
I've tried to do this on a branch, but discovered that the version of Ubuntu in Travis (12.04 "precise") has a very old version of clang-format (3.4), which is missing a bunch of options to produce the desired format.  Anyone know how to install a newer version of clang-format on an old Ubuntu?  Otherwise we might have to stay with astyle.

**Comment by tlepoint** [comment]
Sorry very hectic weeks recently, I didn't have time to look into that. I did it for fplll [here](https://github.com/fplll/fplll/blob/master/.travis.yml).
