### ISSUE TITLE
Address all warnings in the CMake build.

### ISSUE THREAD

**Issue by xvzcf** [open-quantum-safe/liboqs#564]
Compiling SIKE with the CMake build and the `-Wall -Wextra -Werror` flags set results in several errors, and different ones at that for Clang on macOS and gcc on Ubuntu.  

[Here](https://github.com/open-quantum-safe/liboqs/files/3764244/errors.txt) are the GCC-Ubuntu errors. Their validity has to be investigated.

**Comment by christianpaquin** [comment]
@xvzcf, I looked at the build errors for sike. It looks like more files are included in the build. The first error I'm seeing, for example, is in `sidh_compressed.c`. This file shouldn't be compiled directly however, as it is included in the `P*_compressed.c` variants. First step would be to make sure the cmake files match the ones in `src/kem/sike/Makefile.am`.

**Comment by christianpaquin** [comment]
Got it, I'll work on resolving these.

**Comment by christianpaquin** [comment]
Pushed fixes on PR #556.

**Comment by xvzcf** [comment]
[ubuntu_gcc_8_3_0_log.txt](https://github.com/open-quantum-safe/liboqs/files/4032689/ubuntu_gcc_8_3_0_log.txt) contains some more warnings with the latest code, with the compiler being GCC 8.3.0. The flags used were: `-Wall -Wextra -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings`

**Comment by xvzcf** [comment]
[ubuntu_clang_8_log.txt](https://github.com/open-quantum-safe/liboqs/files/4032704/ubuntu_clang_8_log.txt) has warnings reported by `clang-8`. The flags used were the same as in the previous comment.
