### ISSUE TITLE
memory leaks in OpenSSL based SPHINCS+-SHA256 versions

### ISSUE THREAD

**Issue by 0xa5a5** [open-quantum-safe/liboqs#566]
For SPHINCS+-SHA256-* using the OpenSSL hash there are memory leaks because the hash context created by `PREFIX_initialize_hash_function` callee `sha256_inc_init` is not cleaned up.

Ideally there'd be some hook that allows proper destruction of `hash_state_seeded` at the end of sign.c functions

- `PREFIX_crypto_sign_seed_keypair`
- `PREFIX_crypto_sign_signature`
- `PREFIX_crypto_sign_verify`

**Comment by dstebila** [comment]
I saw there's been some work over at PQClean related to this -- once that's finished on the PQClean side, do we need to do anything extra here, other than re-sync the code with PQClean?

**Comment by 0xa5a5** [comment]
In case we solve it as described above, it's only the OQS specific shims `src/common/pqclean_shims` that need to be extended, can take care of that.
