### ISSUE TITLE
Question: Cannot compile standard OpenSSL code using OpenSSL configured and installed

### ISSUE THREAD

**Issue by syrtap** [open-quantum-safe/liboqs#568]
I have compiled all software on CentOS 7.7 using gcc 7.3.1.  Everything seems to work.

I do get OpenSSL fork to compile with liboqs and a local installation (/usr/local) of OpenSSL.  The issue I get is when I try to compile code using standard OpenSSL with OpenSSL fork it complains that "oqs/oqs.h" couldn't be found.  Indeed "oqs/oqs.h" is not installed when I issue a "make install" inside the OpenSSL fork directory.

Here's my build process:
================
cd /root/build/openssl/openssl-OpenSSL_1_1_1d && make clean ; ./Configure shared linux-x86_64 -lm --prefix="/usr/local/openssl-1.1.1d" && make -j 4 && make install
cd /root/build/liboqs/liboqs-0.2.0/ && autoreconf -i
cd /root/build/liboqs/liboqs-0.2.0/ && make clean ; ./configure --enable-shared --prefix="/root/build/openssloqs/openssl-OQS-OpenSSL_1_1_1-stable-snapshot-2019-10//oqs" --with-openssl="/usr/local/openssl-1.1.1d" "--disable-kem-bike" && make -j 4 && make install
cd /root/build/openssloqs/openssl-OQS-OpenSSL_1_1_1-stable-snapshot-2019-10/ && make clean ; ./Configure --prefix="/usr/local/1.1.1d-OQS-OpenSSL_1_1_1-stable_snapshot_2019-10-0.2.0" shared linux-x86_64 -lm && make -j 4 && make install

Now, when I make code that uses standard OpenSSL I get this error (evp.h)

Error:
=====
/tmp/openssldir/include/openssl/evp.h:18:11: fatal error: oqs/oqs.h: No such file or directory
 # include <oqs/oqs.h>
           ^~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: OutboundTransferMgr.o] Error 1
[ CHROOT ] bash-4.2$>

==> How should I use the OpenSSL fork when building software that uses OpenSSL?

I have added "-I/root/build/openssloqs/openssl-OQS-OpenSSL_1_1_1-stable-snapshot-2019-10/oqs/include" to the Makefile so that "oqs/oqs.h" could resolve but I get other strange errors following this.

Thanks for your work here.  Let me know how I should build OpenSSL enabled software with OpenSSL/OQS

(Note:  I'm trying to link first with OpenSSL fork without doing any significant modifications to the source base.  Once I get to compile I'll see if I can add new OQS features in the code later)

Sylvain!

**Comment by syrtap** [comment]
I just realized i’ve posted accidentally in liboqs...  should have been in OpenSSL fork.  Let me know if I should move it there.

Sylvain

**Comment by xvzcf** [comment]
Could you move the issue to [here](https://github.com/open-quantum-safe/openssl/issues)?

**Comment by syrtap** [comment]
I've looked and I can't move it since I don't have the permissions.  I'll try to close this issue right now.  I've created the same issue here: [https://github.com/open-quantum-safe/openssl/issues/128](https://github.com/open-quantum-safe/openssl/issues/128)

Many thanks!

Sylvain
