### ISSUE TITLE
speed_kem & speed_sig halts with Illegal instruction.

### ISSUE THREAD

**Issue by donbirno** [open-quantum-safe/liboqs#574]
speed_kem & speed_sig halts with Illegal instruction.

Debugging stops at

Program received signal SIGILL, Illegal instruction.
0x0001112c in _bench_init_perfcounters (enable_divider=0, do_reset=1) at ds_benchmark.h:155
155             asm volatile("mcr p15, 0, %0, c9, c12, 0\t\n" ::"r"(value));

**Environment:**
Raspberry pi 4
Cortex-A72 (ARM v8) 64-bit 
Linux donpi 4.19.85-v8+ #1279 SMP PREEMPT Fri Nov 22 16:04:03 GMT 2019 aarch64 GNU/Linux

**Comment by donbirno** [comment]
Issue seems to be cycle count register access disabled to user space by default in RPI, that's why process dies with illegal instruction.

**Comment by dstebila** [comment]
Sorry for the delay in responding. @donbirno, could you see if pull request #583 fixes the problem? Seems to work on my Raspberry Pi 3 with Raspbian.
