### ISSUE TITLE
Investigate qtesla failure on arm

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/liboqs#578]
There is a failure in example_sig on travis when qtesla-p-i is used; this needs to be investigated.

**Comment by christianpaquin** [comment]
Is this still an issue since the latest qtesla update?

**Comment by dstebila** [comment]
qTesla works on my Raspberry Pi.  I've submitted PR #716 to re-enable qTesla on ARM CI, and if the CI tests pass for it then we'll merge it and close this issue.
