### ISSUE TITLE
Question: Regarding AES and SHA

### ISSUE THREAD

**Issue by camer314** [open-quantum-safe/liboqs#599]
Forgive me if this is a stupid question, but I see there is code in the crypto src  for AES and SHA but these are not mentioned at all on the main page under Supported Algorithms and nor is any love given to them in the C# wrapper.

So my question is, are these simply implementations of those techniques or are they also quantum safe? Am i to use those directly or is there another way? For example, if i currently use SHA256 then what is the equivalent in this library, and what about AES256?

Thanks!

**Comment by dstebila** [comment]
Hello @camer314. liboqs is not trying to be a general purpose crypto library, and among other things that means that we do not provide a SHA-256 or AES implementation to applications.  While we have our own implementation that we use internally, you would be expected to use existing libraries for AES, SHA, etc. in your applications.

**Comment by dstebila** [comment]
As for whether SHA and AES are quantum-safe, the first order answer is yes.  But there are some subtleties around key size and modes of operation which might require some attention before fully deciding to use them unchanged in an application scenario.
