### ISSUE TITLE
Add continuous integration test for memory leaks

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#604]
Possibly using valgrind?

Would have caught #601, #600, #603.

**Comment by franziskuskiefer** [comment]
I'd recommend adding sanitizer builds. But for enabling them all the issues need to get fixed first.
I opened PR #605 as one possible way to detect these issues.

**Comment by dstebila** [comment]
#617 adds the option for building with address sanitizer, but currently there are memory leaks, so I haven't enabled the test in CI yet.

**Comment by dstebila** [comment]
Watching for https://github.com/PQClean/PQClean/pull/272 to land

**Comment by dstebila** [comment]
Ideally would be running both AddressSanitizer and UndefinedBehaviourSanitizer.

**Comment by dstebila** [comment]
After #701 lands, still need to apply following changes:

- [ ] Picnic leak (0311595344f0ef1a00140fc51d4c2d5fb21c0463)
- [ ] Falcon overrun (f2cd9b5aeeb855eb9d32486293eb2f02574133fe)
- [ ] Enable asan in nightly builds
