### ISSUE TITLE
LedaKemLT52 cannot be run in a worker thread on macOS

### ISSUE THREAD

**Issue by vsoftco** [open-quantum-safe/liboqs#608]
Due to small stack size of worker threads under macOS (512kb), LEDAKEM52LT emits a BUS ERROR (access violations -Exception: EXC_BAD_ACCESS (code=1, address=0x70000292c4c8) ) when attempted to be run in a non-main (worker) thread under macOS. The first culprit is

https://github.com/open-quantum-safe/liboqs/blob/fb458165698c5850dcf08d7268a2b6c90e47e378/src/kem/ledacrypt/pqclean_ledakemlt52_leaktime/dfr_test.c#L13

where the array `gamma` seems to have 609068 bytes, more than can be stored on the stack of a single non-main thread in macOS (512kb). Allocating `gamma` on the heap still doesn't solve the problem, other violations of the same sort keep appearing (I didn't have time to go over the rest). So we should think whether we want to keep the code as is, or document that it shouldn't be run on a thread under macOS, or change it.

**Comment by dstebila** [comment]
Do you have a sense of how many places we'd have to change to make this work?  A few or dozens and dozens?

**Comment by vsoftco** [comment]
@dstebila Definitely more than 1 place. I tried changing the first stack allocation, and got into another issue of the same flavour down the line. I'll look into it when I get some time. Hopefully not dozens and dozens and places we'd need to change.

**Comment by dstebila** [comment]
https://github.com/open-quantum-safe/liboqs/commit/795c1b7932d8e3d44277c7bb1c6c45d091cde1c7#diff-9d282cb2abf60a78fb263d773e0dabe2R84 fixed a memory leak in LEDAkem, there could be a small chance this fixed it?

**Comment by dstebila** [comment]
WONTFIX for now.
