### ISSUE TITLE
Graceful runtime CPU feature handling

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#624]
Ensure all code is designed such that it can not only be configured at compile time to deal with different CPU feature sets (e.g., presence/absence of AVX2) but also handle those gracefully at runtime, e.g, by automatically falling back to a non-optimised version of the same functionality.

In other words, all code compiled with, e.g., `-mavx2` should also run without error on CPUs that do *not* have support for all features (AVX2 in this example).

To help with this, we will integrate the [CPU features](https://github.com/google/cpu_features) library and for starters will add warnings if the library is running on a CPU with a feature set different from the one encountered during build (reducing the surprise when one encounters an `illegal instruction exception` during execution until this issue is fully addressed :-)

Edited by @dstebila to add:

- [X] Use cpu\_features instead of \_\_builtin\_cpu
- [X] Update copy-from-pqclean schemes to do runtime detection
- [x] Runtime detection for SHA-3 ~using  [XKCP](https://github.com/XKCP/XKCP)~
- [X] Runtime detection for Frodo (#878)
- [ ] Runtime detection for SIKE
- [x] Runtime detection for BIKE (see https://github.com/open-quantum-safe/liboqs/pull/1030#issuecomment-877292940)
~- [ ] Runtime detection for qTesla~
- [x] Runtime detection for Picnic
- [x] Runtime detection for AES

**Comment by dstebila** [comment]
Do we consider this done? @xvzcf @baentsch

**Comment by xvzcf** [comment]
Not yet, but almost there.

**Comment by baentsch** [comment]
After yesterday's discussion on checking all algorithms to use common code, and evaluating the (runtime) cost to suitably "XKCP-guard" all common code entry points, I'd need to ask (surely @xvzcf , everyone else invited to chime in, too) for revisiting the suggested use of XKCP for selecting the properly optimized common code: The runtime feature-availability check for each "common code" invocation, e.g. of SHA3, would add a noticeable, quite probably prohibitive, performance penalty to each algorithm using such shared code as typically, such invocations occur very often during each algorithm execution. This check also is not necessary as such algorithms already did the runtime feature check at invocation: Wouldn't it be a correct assessment that those algorithms need common code (symbols) that are (compiled) as optimized as the baseline algorithms _as well as_ common code (symbols) that are/have been compiled not using specific CPU features and call/link to either variant based on the actual CPU features encountered when executing? In essence, #724 looks like a better solution for the problem from a performance perspective than XKCP, even though it requires introducing additional symbols and code (say, "_avx2") for the same functionality (but different compile-time options).

**Comment by dstebila** [comment]
We could rely on global variables that are set with the correct CPU-dependent wirings on the first call to any CPU-dependent function, and then not have to generate that data structure again on future calls.  I acknowledge that global variables are bad(TM), but I think this would be an okay usage?  I don't think it's possible that different threads within the same process would be running on different CPU architectures.  And it should be possible to implement this in a way that is thread-safe.

**Comment by baentsch** [comment]
We already do something similar to this caching [here](https://github.com/open-quantum-safe/liboqs/blob/993c1d757b8d6a875eb9916170c4ff37dd1abd63/src/common/common.c#L134) but this still necessitates function calls & checks, i.e., indirections in the "hot" code path. We'll surely do our best to minimize the performance degradation, but it will be there; so the question is: Are we all OK taking this hit for the "cleanliness" of this solution?

**Comment by dstebila** [comment]
Won't know until we try it and see.  After first run, the overhead should just be an if and some function redirection.

Some crypto libraries require a global "initalize_library" function be called before any use, so if we were willing to demand that then we could reduce the overhead even more.

**Comment by baentsch** [comment]
As agreed in last week's discussion with @xvzcf and @dstebila, I reviewed whether it'd be straightforward to do runtime CPU feature "guarding" as done for the PQClean algorithms for the remaining algorithms listed above. The answer is: "Not really": In some cases I do not see a single place where such switch could easily be introduced (picnic: various places exist that are #ifdef'd to CPU features; BIKE: It seems the method there is to simply use different functions with the same symbol for optimized/"hot" functions (activating the right one for the given feature set). In both cases, I'd consider it hard-to-impossible to create a variant containing both types of code, optimized and ref, to enable the feature this issue calls for). In some cases performance improvement by CPU-feature activation doesn't really yield significant improvements (SIKE, SIDH, Frodo), further making this effort pretty much futile.
In sum, I'd argue we leave things as they are right now, communicate to the teams whose algorithms could benefit from such "portability enhancement" a link to this issue as well as a link to the [Wiki article](https://github.com/open-quantum-safe/liboqs/wiki/Customizing-liboqs#oqs_portable_build) asking for their interest to provide this feature also for their algorithms and either close or put this issue into "future work" state.

**Comment by baentsch** [comment]
Would suggest to check off SHA3 when #957 lands. OK, @jschanck?

**Comment by dstebila** [comment]
All that remains here is SIKE and Picnic. @christianpaquin Is this something you want to pursue or shall we close?

**Comment by baentsch** [comment]
If we close this without moving SIKE and Picnic to the same level, I'd suggest to explicitly document that limitation in the (runtime-) support of those algorithms: They'll always run slower than they could when `OQS_DIST_BUILD` is set (e.g., in profiling and docker images). We could add a sentence [here](https://github.com/open-quantum-safe/liboqs/wiki/Customizing-liboqs#OQS_DIST_BUILD): Something like 

> Note that Picnic and SIKE do not support this flag and this will always run with non-optimized code if setting OQS_DIST_BUILD.

**Comment by sebastinas** [comment]
Picnic now performs runtime selection if OQS is built with SSE2/AVX2/NEON support.

**Comment by baentsch** [comment]
Closing issue as the only algorithm not supporting this feature has been removed.
