### ISSUE TITLE
Invalid read in sidh code

### ISSUE THREAD

**Issue by aparent** [open-quantum-safe/liboqs#63]
Running valgrind over `text_kex` currently returns this error (among other similar errors):

```
==21169== Invalid read of size 8
==21169==    at 0x41442E: oqs_sidh_cln16_fpcopy751 (fpx.c:38)
==21169==    by 0x41387D: oqs_sidh_cln16_ladder_3_pt (ec_isogeny.c:345)
==21169==    by 0x40C196: oqs_sidh_cln16_SecretAgreement_B (sidh_kex.c:352)
==21169==    by 0x40A20D: OQS_KEX_sidh_cln16_bob (kex_sidh_cln16.c:116)
==21169==    by 0x401E42: kex_test_correctness (test_kex.c:81)
==21169==    by 0x400E48: kex_test_correctness_wrapper (test_kex.c:152)
==21169==    by 0x400E48: main (test_kex.c:289)
==21169==  Address 0x5bff880 is 0 bytes after a block of size 48 alloc'd
==21169==    at 0x4C2BC0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==21169==    by 0x40A1AA: OQS_KEX_sidh_cln16_bob (kex_sidh_cln16.c:100)
==21169==    by 0x401E42: kex_test_correctness (test_kex.c:81)
==21169==    by 0x400E48: kex_test_correctness_wrapper (test_kex.c:152)
==21169==    by 0x400E48: main (test_kex.c:289)
```

I investigated the problem and noticed the following:

A block of 48 bytes is malloc'd [here](https://github.com/open-quantum-safe/liboqs/blob/d23f8d3eddf3e72a5971983562721ba9b9c63df5/src/kex_sidh_cln16/kex_sidh_cln16.c#L100
), then passed [here](https://github.com/open-quantum-safe/liboqs/blob/d23f8d3eddf3e72a5971983562721ba9b9c63df5/src/kex_sidh_cln16/kex_sidh_cln16.c#L116), then passed [here](https://github.com/open-quantum-safe/liboqs/blob/d23f8d3eddf3e72a5971983562721ba9b9c63df5/src/kex_sidh_cln16/sidh_kex.c#L352) (as the forth parameter), finally it is passed [here](https://github.com/open-quantum-safe/liboqs/blob/d23f8d3eddf3e72a5971983562721ba9b9c63df5/src/kex_sidh_cln16/ec_isogeny.c#L345).

In the [function](https://github.com/open-quantum-safe/liboqs/blob/d23f8d3eddf3e72a5971983562721ba9b9c63df5/src/kex_sidh_cln16/fpx.c#L33-L40):

`oqs_sidh_cln16_fpcopy751(oqs_sidh_cln16_felm_t a, oqs_sidh_cln16_felm_t c)` 

It is treated as if it has type `oqs_sidh_cln16_felm_t` which is defined: 

`typedef digit_t oqs_sidh_cln16_felm_t[NWORDS_FIELD];`.

Looking at [this](https://github.com/open-quantum-safe/liboqs/blob/d23f8d3eddf3e72a5971983562721ba9b9c63df5/src/kex_sidh_cln16/SIDH.h#L29-L44) section it seems that the type should be of size 96 bytes (4 * 24 or 8 * 12).

Is the original memory allocation [here](https://github.com/open-quantum-safe/liboqs/blob/d23f8d3eddf3e72a5971983562721ba9b9c63df5/src/kex_sidh_cln16/kex_sidh_cln16.c#L100) incorrect?

**Comment by dstebila** [comment]
@christianpaquin: Any suggestions?

**Comment by christianpaquin** [comment]
Just committed a fix [(pull 70)](https://github.com/open-quantum-safe/liboqs/pull/70). Could you run the tool again to see if it works?

**Comment by dstebila** [comment]
@aparent When you run the tool again, can you also briefly document your process on the wiki (https://github.com/open-quantum-safe/liboqs/wiki/Code-analysis) so I know how to do this too?

**Comment by aparent** [comment]
It looks like the issue is fixed with that pr. Thanks!
