### ISSUE TITLE
Wrapper around existing NTRU open source code

### ISSUE THREAD

**Issue by aparent** [open-quantum-safe/liboqs#64]
Need to clarify the licencing issues here.  Linking against GPL code might not be ok:

https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#LinkingWithGPL

**Comment by aparent** [comment]
On further inspection we are GPL compatible: 

https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean

So I think as long as we don't distribute the NTRU code we are ok.

**Comment by dstebila** [comment]
Yes, that's the plan.

**Comment by dstebila** [comment]
Closed by #85.
