### ISSUE TITLE
Refactor Wiki

### ISSUE THREAD

**Issue by xvzcf** [open-quantum-safe/liboqs#643]
The Wiki needs to be updated to reflect the latest in liboqs, such as the CMake build system.  We should also expand on the build options (such as disabling select algorithms) there.

**Comment by dstebila** [comment]
This includes the instructions for building the [example KEM](https://github.com/open-quantum-safe/liboqs/wiki/Minimal-example-of-a-post-quantum-key-encapsulation-mechanism) and example signature programs.

**Comment by gadoofou87** [comment]
@xvzcf Could you please add MinGW build instructions to the wiki?  https://paste.ubuntu.com/p/m9Nc5TMJgk/

**Comment by xvzcf** [comment]
Done [here](https://github.com/open-quantum-safe/liboqs/wiki/Platform-specific-notes-for-building-liboqs). Could you give it a once-over?
