### ISSUE TITLE
Allow shared secret to be supplied to methods

### ISSUE THREAD

**Issue by nicholasfulton** [open-quantum-safe/liboqs#645]
I'm not sure how difficult this would be. After looking through the code it seems that the shared secret generation is happening at a somewhat high level, so the ability to pass a shared secret into the methods would be helpful.

**Comment by dstebila** [comment]
I don't really understand what you're requesting here.  The structure of KEMs is that they *generate* a shared secret, not that they receive a shared secret.

**Comment by nicholasfulton** [comment]
I see. I misunderstood exactly how they worked. With RSA, there seems to be more flexibility as to the key length, data format, etc., but also RSA is completely different in many respects. Thanks!
