### ISSUE TITLE
Wrapper around existing McBits and QcBits code

### ISSUE THREAD

**Issue by aparent** [open-quantum-safe/liboqs#65]
I looked around for this code but can't seem to find it.  Is it available online somewhere or do we need to get it from the authors?

**Comment by dstebila** [comment]
https://www.win.tue.nl/~tchou/

**Comment by aparent** [comment]
Mcbits (and I suspect QCBits as well) seem to have a lot of dependencies on NaCL.  We could grab NaCL at compile time and build it or try to include the common parts of it that we need.

**Comment by aparent** [comment]
I think that requiring it as a dependency when compiling with McBit and QcBit is probably reasonable?

**Comment by dstebila** [comment]
Yeah, that seems fine, we don't need to put everything into our repository.

**Comment by aparent** [comment]
See #67 for mcbits.

**Comment by dstebila** [comment]
McBits added via #67.  Not adding QcBits at present due to security concerns.
