### ISSUE TITLE
linker issue

### ISSUE THREAD

**Issue by rohan2546** [open-quantum-safe/liboqs#658]
'''
#include <stdio.h>
#include <oqs/oqs.h>
#include <oqs/kem_ntru.h>

int main()
{   
    unsigned int var=2456;
    uint8_t *public_key;
    public_key=(uint8_t *)  &var;
    uint8_t * shared_secret_key;
    shared_secret_key=(uint8_t *) &var;
    printf("%d",OQS_KEM_ntru_hps2048509_length_public_key);
    uint8_t * cipher_text;
    cipher_text=(uint8_t *) &var;
    OQS_STATUS p=OQS_KEM_ntru_hps2048509_encaps(cipher_text,public_key,shared_secret_key);
    return 0;
}
'''
This is my code but it gives a linker issue. I installed it as per the  instruction.

**Comment by dstebila** [comment]
What is your compilation and linking command?

Also, the code above is not at all correct.  You have not properly allocated memory, you have multiple pointers pointing to the same piece of improperly allocated memory, you haven't called keygen.  Please see the example code in the project for an idea of how to properly use the API.

**Comment by rohan2546** [comment]
gcc -02 -Wall -Wextra -I$HOME/liboqs/include -L$HOME/liboqs     -L$HOME/liboqs/.libs tests/example_kem.c -o example_kem -loqs
error: unknown argument: '-02'
gcc -o2 -Wall -Wextra -I$HOME/liboqs/include -L$HOME/liboqs     -L$HOME/liboqs/.libs tests/example_kem.c -o example_kem -loqs
error: linker command failed with exit code 1 (use -v to see invocation)



This is when I am running the example file

**Comment by dstebila** [comment]
Ah, the instructions you've copied and pasted from [our wiki](https://github.com/open-quantum-safe/liboqs/wiki/Minimal-example-of-a-post-quantum-key-encapsulation-mechanism) have not been updated after some changes to our build system.

First clone and build liboqs:
```
git clone https://github.com/open-quantum-safe/liboqs
cd liboqs
mkdir build && cd build
cmake -GNinja ..
ninja
```

Then compile your file:
```
gcc -O2 -I/PATH-TO-LIBOQS/build/include -L/PATH-TO-LIBOQS/build/lib -loqs -lcrypto example_kem.c -o example_kem
```

If you encounter problems related to linking against OpenSSL, you can try this:
```
cmake -GNinja -DOQS_USE_OPENSSL=OFF ..
ninja

gcc -O2 -I/PATH-TO-LIBOQS/build/include -L/PATH-TO-LIBOQS/build/lib -loqs example_kem.c -o example_kem
```

Note that in `-O2` it is a capital letter "oh", not the number "zero" (your comment above has `-02` not `-O2`).

**Comment by rohan2546** [comment]
Thank you very much sir. It helped.

**Comment by rohan2546** [comment]
Thanks Its working now
