### ISSUE TITLE
liboqs Compilation Error

### ISSUE THREAD

**Issue by xvzcf** [open-quantum-safe/liboqs#659]
Hello, I tried to compile it on Ubuntu 18.04.04, and I get the following errors:
`[9/661] Building C object src/common/CMakeFiles/common.dir/rand_nist.c.o
FAILED: src/common/CMakeFiles/common.dir/rand_nist.c.o 
/usr/bin/cc  -Iinclude -fvisibility=hidden   -Wall -Wextra -Wpedantic -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings -O3 -fomit-frame-pointer -march=native   -std=gnu11 -MD -MT src/common/CMakeFiles/common.dir/rand_nist.c.o -MF src/common/CMakeFiles/common.dir/rand_nist.c.o.d -o src/common/CMakeFiles/common.dir/rand_nist.c.o   -c ../src/common/rand_nist.c
../src/common/rand_nist.c:71:14: error: conflicting types for ‘OQS_randombytes_nist_kat_init’
 OQS_API void OQS_randombytes_nist_kat_init(unsigned char *entropy_input, unsigned char *personalization_string, int security_strength) {
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from include/oqs/oqs.h:18:0,
                 from /usr/local/include/openssl/evp.h:18,
                 from ../src/common/rand_nist.c:16:
include/oqs/rand.h:66:14: note: previous declaration of ‘OQS_randombytes_nist_kat_init’ was here
 OQS_API void OQS_randombytes_nist_kat_init(const uint8_t *entropy_input, const uint8_t *personalization_string, int security_strength);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[14/661] Building C object src/kem/bike/CMakeFiles/bike1_l1_cpa.dir/additional/decode.c.o
ninja: build stopped: subcommand failed.`
I tried to compile it a few moments ago.

_Originally posted by @Septien in https://github.com/open-quantum-safe/liboqs/issues/653#issuecomment-597757006_

**Comment by xvzcf** [comment]
@Septien, could you try re-compiling with liboqs at [this commit](https://github.com/open-quantum-safe/liboqs/commit/7c083329f39d322aab9755e0b3eb80f4c4f1ac6e)? 

If that doesn't work, could you walk me through your build process in more detail? Are you building liboqs using our fork of OpenSSL or using the OpenSSL distributed by Ubuntu 18.04? Have you tried the instructions [here](https://github.com/open-quantum-safe/openssl#linux-and-macOS)?

**Comment by dstebila** [comment]
Closing issue.  If you're still encountering the problem, please re-open the issue or start a new issue.
