### ISSUE TITLE
Ensure Keccak in picnic has separate namespace

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#666]
Goal: PQClean algorithms referencing `KeccakP1600times4_PermuteAll_24rounds` should not accidentally "wind up" calling Picnic's implementation thereof

**Comment by christianpaquin** [comment]
Done in PR #676; @baentsch, does that fix your issue?

**Comment by baentsch** [comment]
@christianpaquin Yes, it does: Thanks! Sorry for not closing the issue earlier.

**Comment by baentsch** [comment]
Unfortunately, I didn't test well enough: When now "opening up" (removing the `static` declaration) the `common` symbol `KeccakP1600times4_PermuteAll_24rounds` (in `src/common/sha3`) linking creates a collision again. I'll need to investigate some more. Do we agree that it should be the goal that the `common/sha3`-originating code should be the one made available to `liboqs` algorithms?

**Comment by christianpaquin** [comment]
Yes, all non-namespaced Keccak calls should refer to the code in `common/sha3`. What platform and optimizations (e.g., avx2, etc.) are you using? The Keccak code uses a lot of macros (functions and variants are defined by macros, sometimes implemented in C, sometimes in assembly), and I tried to namespace all of the picnic ones but maybe I missed a few (quite possible if I didn't test on the same platform w/ same opt as you). I'll investigate.

**Comment by christianpaquin** [comment]
PR #705 should fix the picnic namespacing.

**Comment by baentsch** [comment]
Confirmed. Will follow up with a change to open up symbol for (avx2) `src/common/sha3` Keccak
