### ISSUE TITLE
liboqs installation problem

### ISSUE THREAD

**Issue by spoodermoon** [open-quantum-safe/liboqs#667]
Hi, I tried to install the liboqs but on `ninja run_tests` it fails on tests/test_style.py::test_style at 97%, after that i tried the command `ninja install` but it returns the following error: 
```

[0/1] Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/liboqs.a
CMake Error at src/cmake_install.cmake:41 (file):
  file INSTALL cannot copy file "/home/pg41101/liboqs/build/lib/liboqs.a" to
  "/usr/local/lib/liboqs.a".
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)


FAILED: CMakeFiles/install.util
cd /home/pg41101/liboqs/build && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

But running the same command with root it works: 

```
[0/1] Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/liboqs.a
-- Up-to-date: /usr/local/include/oqs/oqs.h
-- Up-to-date: /usr/local/include/oqs/common.h
-- Up-to-date: /usr/local/include/oqs/rand.h
-- Up-to-date: /usr/local/include/oqs/aes.h
-- Up-to-date: /usr/local/include/oqs/sha2.h
-- Up-to-date: /usr/local/include/oqs/sha3.h
-- Up-to-date: /usr/local/include/oqs/kem.h
-- Up-to-date: /usr/local/include/oqs/sig.h
-- Up-to-date: /usr/local/include/oqs/kem_bike.h
-- Up-to-date: /usr/local/include/oqs/kem_frodokem.h
-- Up-to-date: /usr/local/include/oqs/kem_sike.h
-- Up-to-date: /usr/local/include/oqs/sig_picnic.h
-- Up-to-date: /usr/local/include/oqs/sig_qtesla.h
-- Up-to-date: /usr/local/include/oqs/kem_classic_mceliece.h
-- Up-to-date: /usr/local/include/oqs/kem_kyber.h
-- Up-to-date: /usr/local/include/oqs/kem_ledacrypt.h
-- Up-to-date: /usr/local/include/oqs/kem_newhope.h
-- Up-to-date: /usr/local/include/oqs/kem_ntru.h
-- Up-to-date: /usr/local/include/oqs/kem_saber.h
-- Up-to-date: /usr/local/include/oqs/kem_threebears.h
-- Up-to-date: /usr/local/include/oqs/sig_dilithium.h
-- Up-to-date: /usr/local/include/oqs/sig_falcon.h
-- Up-to-date: /usr/local/include/oqs/sig_mqdss.h
-- Up-to-date: /usr/local/include/oqs/sig_rainbow.h
-- Up-to-date: /usr/local/include/oqs/sig_sphincs.h
-- Up-to-date: /usr/local/include/oqs/oqsconfig.h

```
Honestly I don't even know if is correctly installed but my main reason to install this library is to use it with the python3 wrappers **liboqs-python**, so after I clone the the project I ran the command `oqs/oqs.py` and it returns the following message `No liboqs shared libraries found`.

I have very poor experience on installing/compiling libraries, would appreciate if anyone could help me or guide me to install liboqs successfully so i can use **liboqs-python**.

Thank you.

**Comment by xvzcf** [comment]
With respect to `test_style` failing, what does the output say? Do you have `astyle` installed? 

With respect to the rest, if an installation prefix is not specified, it defaults to `/usr/local` on UNIX-like systems. That's why when you run `ninja install` it attempts to copy `liboqs.a` to `/usr/local/lib`. It probably fails without root because you lack the permissions to copy files there.

If you'd like to install the headers and libraries to a directory of your choosing, which, say, is `<DIR>`, you have to pass the `-DCMAKE_INSTALL_PREFIX=<DIR>` option. For more information, see the [CMake documentation for CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html). 

To use liboqs-python, you have to build liboqs as a shared library. This is controlled by the `-DBUILD_SHARED_LIBS=[ON|OFF]` option. The build steps would therefore be: 

```bash
cmake .. -G"Ninja" -DCMAKE_INSTALL_PREFIX=<DIR> -DBUILD_SHARED_LIBS=ON`
ninja
ninja install
```

Once `liboqs` is installed in `<DIR>`, follow the instructions [here](https://github.com/open-quantum-safe/liboqs-python), and make sure to correctly specify the `LIBOQS_INSTALL_PATH` and `PYTHONPATH` environment variables.

**Comment by spoodermoon** [comment]
Thank you for your response! the problem of test_style failing was indeed the `astyle`, but after installing it another test fails `tests/test_namespace.py::test_namespace`. 

The `<DIR>` in `-DCMAKE_INSTALL_PREFIX=<DIR>`, what should the location be to successfully install, I currently have the project under my user folder... 

Once I installed the `liboqs`, the `liboqs-python` should be in any specific path, and to specify the `LIBOQS_INSTALL_PATH` i only need to run this command `LIBOQS_INSTALL_PATH="/usr/local/bin/liboqs.so"` with the correct path to the `liboqs.so` correct?

**Comment by xvzcf** [comment]
> Thank you for your response! the problem of test_style failing was indeed the `astyle`, but after installing it another test fails `tests/test_namespace.py::test_namespace`.

What does the output say?

> The `<DIR>` in `-DCMAKE_INSTALL_PREFIX=<DIR>`, what should the location be to successfully install, I currently have the project under my user folder...

`<DIR>` can be any directory of your choosing. For example, to avoid permission issues, you can specify it to be `~/oqs`. The correct path to `liboqs.so` would then be `~/oqs/lib/liboqs.so`

> Once I installed the `liboqs`, the `liboqs-python` should be in any specific path, and to specify the `LIBOQS_INSTALL_PATH` i only need to run this command `LIBOQS_INSTALL_PATH="/usr/local/bin/liboqs.so"` with the correct path to the `liboqs.so` correct?

Once you have the correct path (say `<path>`) to `liboqs.so`, to set this environment variable, you can run `export LIBOQS_INSTALL_PATH=<path>`. Also note that you have to set `PYTHONPATH`; see the "Running" section [here](https://github.com/open-quantum-safe/liboqs-python) for the full list of instructions.

**Comment by dstebila** [comment]
Closing for now. Please re-open or file a new issue if the problem persists.
