### ISSUE TITLE
Use of cpu_features from #654 breaks cross-compilation

### ISSUE THREAD

**Issue by kevinmkane** [open-quantum-safe/liboqs#679]
cpu_features's build doesn't work with the Windows or Raspberry Pi cross-compiling toolchains. CMake fails to run successfully in each case but for different reasons. Build host is running Ubuntu 18.04 and current tip of master is 9897b49.

The Raspberry Pi build complains that it's being built for a non-x86 platform, which it is. The Windows build complains that it doesn't understand the `-rdynamic` command line option to the C compiler.

Outputs of each run of CMake are attached.

[raspbuild.log](https://github.com/open-quantum-safe/liboqs/files/4381743/raspbuild.log)
[winbuild.log](https://github.com/open-quantum-safe/liboqs/files/4381744/winbuild.log)

**Comment by gadoofou87** [comment]
Looks like `cpu_features` doesn't support cross-compilation. I can try to make a patch for their library.

**Comment by gadoofou87** [comment]
@kevinmkane Can you try to recompile with this [patch](https://github.com/open-quantum-safe/liboqs/files/4382028/patch.txt)?

**Comment by kevinmkane** [comment]
Got further this time with the patch.

Raspberry Pi build: Weirdly complains that it couldn't find OpenSSL, saying: found suitable version "1.1.1", minimum required is "1.1.1"
Windows build: Complains that there's no setting for the resource compiler (CMake Error: CMAKE_RC_COMPILER not set, after EnableLanguage).

New full logs attached.
[winbuild.log](https://github.com/open-quantum-safe/liboqs/files/4382471/winbuild.log)
[raspbuild.log](https://github.com/open-quantum-safe/liboqs/files/4382473/raspbuild.log)

**Comment by gadoofou87** [comment]
You need to fix the CMake call
`$ cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../.CMake/toolchain_rasppi.cmake -DUSE_OPENSSL=OFF ..`
Replace `-DUSE_OPENSSL=OFF` with `-DOQS_USE_OPENSSL=OFF`.

As for Windows, I'm not sure, but try to apply this [patch](https://github.com/open-quantum-safe/liboqs/files/4382566/patch.txt)

**Comment by kevinmkane** [comment]
Using `-DOQS_USE_OPENSSL=OFF` now lets the Raspberry Pi cross-build complete successfully. Can you update the [cross-compiling wiki](https://github.com/open-quantum-safe/liboqs/wiki/Platform-specific-notes-for-building-liboqs) and the comment in the toolchain file?

Both patches together now allow the Windows build to succeed as well.

Thanks!
