### ISSUE TITLE
Update to copy_from_pqclean

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#691]
This is to capture all improvements required for `copy_from_pqclean`:
- Auto-generate source code lists for CMakefiles
- Automate generation of multi-feature CMake-structures from PQClean `META.yml` incl. suitable #defines ("clean" implementation always being the "code of last resort")
- Ensure OS dependencies are heeded (no optimised code build enabled on unsupported platforms)
- Auto-prettyprint copied source code after import to satisfy style-checks
- Integrate run-time feature detection to generated `kem` and `sig` "entry point functions"

This supports issue #689 

@dstebila If you have other items to add, please do so via Comment. Thanks in advance.

**Comment by dstebila** [comment]
> * Auto-prettyprint copied source code after import to satisfy style-checks

There's no need for the code copied from PQClean to be pretty-printed using our style.  But files we generate using the copy\_from\_pqclean scripts should be pretty-printed using our style.

**Comment by baentsch** [comment]
Enable "implicit OQS_init" (assert-style feature-check initialisation in all liboqs calls) along the lines suggested by [@dstebila](https://github.com/open-quantum-safe/liboqs/pull/689#issuecomment-606710154)

**Comment by dstebila** [comment]
Fixed by #703.
