### ISSUE TITLE
Windows Issues

### ISSUE THREAD

**Issue by xvzcf** [open-quantum-safe/liboqs#697]
On my Windows 10 Enterprise VM, with with Ninja build tool and MSVC compiler. Target platform as reported by `speed_sig`: AMD64-Windows-10.0.18363.

1) Using 32-bit `cl.exe`, the build fails with the following messages:

![sike_fail](https://user-images.githubusercontent.com/21228961/78150570-77b17b00-7405-11ea-944b-869260ec974c.png)

For 64-bit builds:

2) `Rainbow-Vc-Cyclic` keypair generation takes 71.156 seconds, as measured by `speed_sig`. Signing takes 35.61 seconds. It once increased the runtime of `ninja run_tests` by 10 minutes, but this seems to be non-deterministic.

3) The SPHINCS and Rainbow variants seem in general to impose a big slow down on `ninja run_tests`.

4) `kat_sig` with `Falcon-512` and `Falcon-1024` results in heap corruption errors.

**Comment by christianpaquin** [comment]
I don't think we officially support win32. If that's in scope, we should at a minimum add CI tests for it (appveyor currently only target x64). Do we support/test 32-bit on linux/mac?

**Comment by dstebila** [comment]
No, we don't support/test 32-bit on Linux or Mac.  Do any of our use cases have a need for 32-bit?

**Comment by christianpaquin** [comment]
I don't think we need to support 32-bit. First error case above is therefore a non-issue. We should investigate the slowdown on x64 bit. Is there optimized code in there that only runs on Linux? That could explain the speed difference.

**Comment by christianpaquin** [comment]
On what platform did you experience errors on Falcon-512/1024, @xvzcf ? `kat_sig` completes successfully with these algs on my Windows machine.

**Comment by xvzcf** [comment]
It was a VM image with 4G of RAM assigned to it. 

I tried running `kat_sig Falcon-512` and `kat_sig Falcon-1024` again, and both worked fine. It is likely [this change](https://github.com/open-quantum-safe/liboqs/commit/854f0748083b29bc9f180c8794fa112bcd7ec76d#diff-f80917420951d6ebd4388e26ee05302dR133) that fixed the problem.

**Comment by dstebila** [comment]
Shall we close this issue then?

**Comment by xvzcf** [comment]
I think there's still the outstanding issue of the speed of the Rainbow and SPHINCS variants.
