### ISSUE TITLE
Reduce check-in testing on AppVeyor

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#698]
As it might be so 
- that we cannot use CircleCI for Windows testing (see [PR #690](https://github.com/open-quantum-safe/liboqs/pull/690)), and 
- the AppVeyor account is rather slow regarding Windows testing (@vsoftco and @baentsch at least were waiting for hours to see whether some trivial changes were OK), and
- we decided yesterday to curtail support for "problematic" algorithms on Windows
can I suggest we reduce Windows/AppVeyor-based checkin testing considerably, e.g., with a blacklist of algorithms we don't want to run --at least on Windows--at every check-in?

Can I ask for your comments on this proposal, @dstebila @xvzcf @christianpaquin ? Anyone else?

**Comment by christianpaquin** [comment]
I support reducing the number of tested algs at check it, test all of them on a nightly basis.

**Comment by dstebila** [comment]
Makes sense.  

In PQClean, all of the tests are parameterized by a [`filtered_test` command](https://github.com/PQClean/PQClean/blob/master/test/helpers.py) which then pulls various environment variables to decide what to skip.  These environment variables can then be set in the various CI test configurations.

**Comment by christianpaquin** [comment]
I'll remove the slow-running algs from the per-commit appveyor run; I'm waiting for @xvzcf to finish work to properly disable the algorithm.

**Comment by xvzcf** [comment]
Just noting that it seems to be the SPHINCS and Rainbow variants that impose a big slow down on the Appveyor tests.

**Comment by xvzcf** [comment]
Closed by https://github.com/open-quantum-safe/liboqs/pull/726
