### ISSUE TITLE
Should we add XMSS?

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#699]
Seeing as how XMSS has been published as an [RFC](https://www.rfc-editor.org/rfc/rfc8391.html) and that NIST is planning to endorse it, it seems like something that should be in the post-quantum toolkit provided by liboqs.

We'd need a new API for stateless signatures.

**Comment by christianpaquin** [comment]
That'd be indeed interesting to see. The new API would also impact significantly the downstream TLS, SSH, VPN projects. OpenSSH already has integrated XMSS, so we would need to be compatible with their approach. I've seen early work on integrating XMSS in OpenSSL; I'm not sure if that work has been updated.

**Comment by dstebila** [comment]
Closing this for now while we focus on Round 3 schemes.
