### ISSUE TITLE
implicit declaration of function ‘aes256_ecb_keyexp’

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#700]
@dstebila Please see https://github.com/PQClean/PQClean/issues/283#issuecomment-608371242 and the comment made there (regarding "pqclean_shim.c": I did not find that in `liboqs`, so am at a loss what to make of this).

As you seem to have been involved on the PQClean PR that introduced this change as well as the original `liboqs` copy scripts, can you suggest how to resolve this within `liboqs`? 

When using the latest `PQClean` code PQClean algs don't compile any more with this error:
```
/home/parallels/liboqs/src/sig/rainbow/pqclean_rainbowIIIc_cyclic_clean/utils_prng.c:17:5: error: implicit declaration of function ‘aes256_ecb_keyexp’; did you mean ‘aes256_keyexp’? [-Werror=implicit-function-declaration]
     aes256_ecb_keyexp(&ctx, Key);
     ^~~~~~~~~~~~~~~~~
     aes256_keyexp

```

Thanks in advance for any suggestion/fix if that's straightforward for you. Otherwise I try to find a solution myself (although I prefer to close out issue #691 first).

**Comment by dstebila** [comment]
Yup, I'll take care of it.

**Comment by thomwiggers** [comment]
Sorry, I meant https://github.com/open-quantum-safe/liboqs/tree/master/src/common/pqclean_shims
