### ISSUE TITLE
Compiling .so file on linux (WSL)

### ISSUE THREAD

**Issue by ChristianOConnor** [open-quantum-safe/liboqs#714]
Hi guys! Love the project thanks for everything! I have been trying to build the Linux binary on Windows Linux (WSL Ubuntu Bionic Beaver), but for some reason it only creates 1 lib file "liboqs.a"

Where is the ".so" file?

Here is my build commands:
1. (I have all these installed) - cmake gcc ninja-build libssl-dev python3-pytest python3-pytest-xdist unzip xsltproc doxygen graphviz
2. git clone -b master https://github.com/open-quantum-safe/liboqs.git
3. cd liboqs
4. mkdir build && cd build
5. cmake -GNinja ..
6. ninja

this creates a folder "lib" containing the file "liboqs.a" but no file called "liboqs.so"

**EDIT**

Nevermind I re-read the instructions for "liboqs-python" and saw that you have to use the `-DBUILD_SHARED_LIBS=ON` flag on the pre-build command `cmake -GNinja ..` to make the output not just the static library so the new command is `cmake -GNinja -DBUILD_SHARED_LIBS=ON ..`

You guys can close this issue if you want.

**Comment by xvzcf** [comment]
For future reference, all CMake build options for customizing liboqs are listed in [the wiki](https://github.com/open-quantum-safe/liboqs/wiki/Customizing-liboqs).
