### ISSUE TITLE
Cross-compiling for Windows on Linux broken by search for pthreads

### ISSUE THREAD

**Issue by kevinmkane** [open-quantum-safe/liboqs#727]
The CMake configuration process now appears to look for pthreads, and cross-compiling a test application for Windows that attempts to call `pthread_create` fails, and rightly so, since pthreads isn't native on Windows. Here's the output of running CMake:

```
kkane@kkane-linux:/tmp/PQCrypto-VPN/openvpn/build/repos/liboqs/build-win$ cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../.CMake/toolchain_windows-amd64.cmake -DCMAKE_INSTALL_PREFIX=/tmp/openssl/oqs ..
-- The C compiler identification is GNU 7.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/x86_64-w64-mingw32-gcc
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   RUN_RESULT (advanced)
   RUN_RESULT__TRYRUN_OUTPUT (advanced)
For details see /tmp/PQCrypto-VPN/openvpn/build/repos/liboqs/build-win/TryRunResults.cmake
CMake Error at .CMake/gcc_clang_intrinsics.cmake:6 (message):
  .CMake/detect_gcc_clang_intrinsics.c returned exit code:
  PLEASE_FILL_OUT-FAILED_TO_RUN
Call Stack (most recent call first):
  .CMake/compiler_opts.cmake:65 (include)
  CMakeLists.txt:40 (include)


-- Configuring incomplete, errors occurred!
See also "/tmp/PQCrypto-VPN/openvpn/build/repos/liboqs/build-win/CMakeFiles/CMakeOutput.log".
See also "/tmp/PQCrypto-VPN/openvpn/build/repos/liboqs/build-win/CMakeFiles/CMakeError.log".
```

Tip of master branch is 8950275409f163f50af46b882c2f950674f2d0ac.

And here are the two output logs:
[CMakeOutput.log](https://github.com/open-quantum-safe/liboqs/files/4494233/CMakeOutput.log)
[CMakeError.log](https://github.com/open-quantum-safe/liboqs/files/4494234/CMakeError.log)

**Comment by gadoofou87** [comment]
I'm not sure, but can you try again with this [patch](https://github.com/open-quantum-safe/liboqs/files/4495156/patch.txt)?

**Comment by kevinmkane** [comment]
@gadoofou87 That didn't help. Error is unchanged. It's still failing to build the test binary looking for `pthread_create`.

**Comment by gadoofou87** [comment]
@kevinmkane I'm apologize for this patch, I didn't have the opportunity to test it. First of all, I want to say that `pthread` is not a problem. The problem is that `try_run` can't find any way to run executable files. I have found two ways to fix it.
1. Install `wine` and apply this [patch](https://github.com/open-quantum-safe/liboqs/files/4496211/patch.txt).
2. Set `OQS_USE_CPU_EXTENSIONS` to `OFF`.

**Comment by kevinmkane** [comment]
In cross-compilation scenarios, there's no expectation the build host would be able to run any executables built for the target. Going down this path implies no longer supporting any cross-compilation scenarios. Is that acceptable?

Turning off `OQS_USE_CPU_EXTENSIONS` might be acceptable, depending on what if any performance penalty is incurred by doing so.

**Comment by gadoofou87** [comment]
> Going down this path implies no longer supporting any cross-compilation scenarios.
What makes you think that? See point 1 in my previous message, it solves the problem completely.

**Comment by kevinmkane** [comment]
I think installing wine is a heavyweight requirement to introduce to do a build, but regardless, that only solves the problem for Windows. If I try to run cmake with the Raspberry Pi toolchain, I get a similar error with it failing to build an executable looking for `pthread_create`. If the problem is that cmake isn't able to run executables, isn't this potentially a problem for cross-compiling to ARM as well?

**Comment by gadoofou87** [comment]
> If the problem is that cmake isn't able to run executables, isn't this potentially a problem for cross-compiling to ARM as well?

Cross-compiling an optimized version of a library for a non-host architecture is not possible. Detecting CPU features in runtime should solve this problem, but it has not yet been implemented (https://github.com/open-quantum-safe/liboqs/issues/624). At this moment, I recommend disabling the optimized build when using cross-compiling.

**Comment by kevinmkane** [comment]
Alright, that's fair. I'll disable the CPU_FEATURES in the cross-compile build. Thanks!
