### ISSUE TITLE
Error in kat_sig Picnic in ubuntu-bionic-x86_64-clang9 CI workflow

### ISSUE THREAD

**Issue by xvzcf** [open-quantum-safe/liboqs#732]
As noted [here](https://github.com/open-quantum-safe/liboqs/blob/master/.circleci/config.yml#L150), when the build is configured with the command:

```bash
env CC=clang-9 cmake .. -G"Ninja" -DOQS_PORTABLE_BUILD=OFF
```

upon building, the following tests fail:

- `test_sig picnic_L1_UR` and `kat_sig picnic_L1_UR`
- `test_sig picnic_L1_FS` and `kat_sig picnic_L1_FS`
- `test_sig picnic2_L1_FS` and `kat_sig picnic2_L1_FS`

with either `ERROR: OQS_SIG_verify failed` or `ERROR: OQS_SIG_sign failed`

**Comment by christianpaquin** [comment]
I can't repro on my Ubuntu 18.04.4 LTS.

**Comment by xvzcf** [comment]
Interesting, I'm able to reproduce on my Ubuntu 19.10, with clang version 10.0.0. Will try to investigate this.

**Comment by christianpaquin** [comment]
I'm running Ubuntu in the Windows Linux Subsystem, so there are perhaps side-effects wrt the compiler flags used.

**Comment by christianpaquin** [comment]
I created a VM with avx2 and bmi2 support, and I was able to repro the issue. I'll investigate next week.

**Comment by christianpaquin** [comment]
I can't easily find the source of the problem. The Picnic team pushed a [v2.2](https://github.com/IAIK/Picnic/tree/v2.2) version last month to fix a few things, just before releasing [v3](https://github.com/IAIK/Picnic/tree/v3.0). I'll plan on integrating the v2.2 update in this OQS release, and integrate v3.0 (introducing new parameters) after our snapshot.

**Comment by dstebila** [comment]
Fixed by #743.

**Comment by christianpaquin** [comment]
After discussing with the Picnic team, I learned that the clang-9 issue should be fixed with a [commit](https://github.com/IAIK/Picnic/commit/c70a0b0c38f6da1d5fdc80fdb1fbc796152170ea) from on their v3 code. I'll try to pull that in our  v.2.2 PR #746 and see if that fixes the issue.
