### ISSUE TITLE
I am just curious is 32-bit dll still supported or dropped in favour of x64?

### ISSUE THREAD

**Issue by jianmingyong** [open-quantum-safe/liboqs#733]
I am curious if 32 bit version of the oqs.dll still supported as it seems that the newest code here won't build if I set the correct cmake settings?

**Comment by xvzcf** [comment]
For future reference, all supported architectures are listed [here](https://github.com/open-quantum-safe/liboqs/blob/master/CMakeLists.txt#L23).
