### ISSUE TITLE
Possible bug with numbers in Gaussian Sampler Table

### ISSUE THREAD

**Issue by amir734jj** [open-quantum-safe/liboqs#75]
Hi Dr. Stebila,

I asked [my question/possible bug in the code here](http://crypto.stackexchange.com/questions/42372/trying-to-see-if-in-fact-there-is-a-bug-in-the-code-associated-with-the-paper) initially to see maybe if I am wrong or not. There at crypto.stackexchange they suggested the [new repository might have the issue fixed but it is not](https://github.com/open-quantum-safe/liboqs/blob/master/src/kex_rlwe_bcns15/rlwe_table.h). It would be great if you could look at my question and see if I am missing a point or not. In the question, there is a link to SageMath code to verify my claim.

Thank you,
Amir

**Comment by dstebila** [comment]
Entries in that table are little endian in terms uint64_t words.  Notice how the last word in each row increases until it reaches 0xFF...FF, and then the middle word increases until it reaches 0xFF...FF, and then the first word.
