### ISSUE TITLE
saving returning bytes to .key or .pem file (Liboqs_python)

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/liboqs#764]
Hello, this is a question not an issue. How do I save the returning bytes from generate_keypair() and export_secret_key() into a .key or a .pem file?

Thank you

**Comment by dstebila** [comment]
I'm not aware of any standard encoding of keys for current post-quantum candidates into PKCS 12 or PEM format.

**Comment by prchander** [comment]
Is there any way to make them in OQS-OpenSSL? Like generate keys in liboqs but then generate the certs in OpenSSL.

**Comment by baentsch** [comment]
@prchander Well, openssl "wraps" liboqs. So if you want to utilize PEM structures, I'd say you should (only) utilize openssl tooling which has this embedded (side note: this is also the only way to get support for hybrid keys/algorithms); see for example https://github.com/open-quantum-safe/openssl#cms-demo . Some algorithms are "standardizing" key formats and (implicitly) encode these formats (for long-term maintenance) in the OIDs. In general, though, @dstebila's comment is correct: No standard exists for that yet... No algorithm has formally been declared a standard either.
