### ISSUE TITLE
liboqs.dll isn't installed by ninja install when cross-compiling for Windows

### ISSUE THREAD

**Issue by kevinmkane** [open-quantum-safe/liboqs#773]
If `-DBUILD_SHARED_LIBS=ON` is used when cross-compiling for Windows, `liboqs.dll` gets built in the `bin` subdirectory in the build tree, and `liboqs.dll.a` gets created in `lib` for development purposes. `ninja install` installs the latter, but does not install the former. It should similarly create a `$(CMAKE_INSTALL_PREFIX)/bin` in this case, and install `liboqs.dll` there.

If this gets done, the OpenSSL Makefile template should be similarly updated to place `oqs/bin/liboqs.dll` in `$(DESTDIR)$(INSTALLTOP)/bin` alongside `libcrypto-1_1-x64.dll` and `libssl-1_1-x64.dll` when OpenSSL is configured to build shared library outputs. See open-quantum-safe/openssl#217.

**Comment by christianpaquin** [comment]
@kevinmkane, I think PR #792 does the trick on the OQS side; right? If that works for you, I can modify the OpenSSL project accordingly.

**Comment by kevinmkane** [comment]
@christianpaquin, I can't test this right away, but it _looks_ like the right idea. I'll take your word for it if you say that's what it does. :)

**Comment by dstebila** [comment]
Believed to be fixed by #792.  If not, please reopen.
