### ISSUE TITLE
liboqs fails to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by kaiduanx** [open-quantum-safe/liboqs#774]
Hi all,

I tried to build liboqs on Ubuntu 16.04 with openssl 1.1.1c (I built openssl from source and installed it in /usr/local/ssl) as below,

cd build
cmake -GNinja .. -DOPENSSL_ROOT_DIR=/usr/local/ssl/
ninja
[5/1393] Building C object src/sig/picnic/CMakeFiles/picnic.dir/external/mzd_additional.c.o
FAILED: src/sig/picnic/CMakeFiles/picnic.dir/external/mzd_additional.c.o 
/usr/bin/cc  -DOPTIMIZED_LINEAR_LAYER_EVALUATION -DPICNIC_STATIC -DREDUCED_ROUND_KEY_COMPUTATION -DWITH_AVX2 -DWITH_KECCAK_X4 -DWITH_KKW -DWITH_LOWMC_128_128_20 -DWITH_LOWMC_192_192_30 -DWITH_LOWMC_256_256_38 -DWITH_OPT -DWITH_SSE2 -DWITH_ZKBPP -Iinclude -I../src/sig/picnic/external -I../src/sig/picnic/external/sha3 -I../src/sig/picnic/external/sha3/avx2 -fPIC -fvisibility=hidden   -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -Wno-missing-braces -std=gnu11 -MMD -MT src/sig/picnic/CMakeFiles/picnic.dir/external/mzd_additional.c.o -MF src/sig/picnic/CMakeFiles/picnic.dir/external/mzd_additional.c.o.d -o src/sig/picnic/CMakeFiles/picnic.dir/external/mzd_additional.c.o   -c ../src/sig/picnic/external/mzd_additional.c
../src/sig/picnic/external/mzd_additional.c: In function ‘oqs_sig_picnic_mzd_copy_s256_256’:
../src/sig/picnic/external/mzd_additional.c:157:44: internal compiler error: in convert_move, at expr.c:315
   BLOCK(dst, 0)->w256 = CONST_BLOCK(src, 0)->w256;
                                            ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[9/1393] Building C object src/sig/picnic/CMakeFiles/picnic.dir/external/picnic2_simulate_mul.c.o
FAILED: src/sig/picnic/CMakeFiles/picnic.dir/external/picnic2_simulate_mul.c.o 
/usr/bin/cc  -DOPTIMIZED_LINEAR_LAYER_EVALUATION -DPICNIC_STATIC -DREDUCED_ROUND_KEY_COMPUTATION -DWITH_AVX2 -DWITH_KECCAK_X4 -DWITH_KKW -DWITH_LOWMC_128_128_20 -DWITH_LOWMC_192_192_30 -DWITH_LOWMC_256_256_38 -DWITH_OPT -DWITH_SSE2 -DWITH_ZKBPP -Iinclude -I../src/sig/picnic/external -I../src/sig/picnic/external/sha3 -I../src/sig/picnic/external/sha3/avx2 -fPIC -fvisibility=hidden   -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -Wno-missing-braces -std=gnu11 -MMD -MT src/sig/picnic/CMakeFiles/picnic.dir/external/picnic2_simulate_mul.c.o -MF src/sig/picnic/CMakeFiles/picnic.dir/external/picnic2_simulate_mul.c.o.d -o src/sig/picnic/CMakeFiles/picnic.dir/external/picnic2_simulate_mul.c.o   -c ../src/sig/picnic/external/picnic2_simulate_mul.c
../src/sig/picnic/external/picnic2_simulate_mul.c: In function ‘oqs_sig_picnic_mpc_matrix_mul_s256_128’:
../src/sig/picnic/external/picnic2_simulate_mul.c:1305:27: internal compiler error: in convert_move, at expr.c:315
       mask2               = block_masks[(matrix_byte >> 0) & 0xf].w256;
                           ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
[10/1393] Building C object src/sig/picnic/CMakeFiles/picnic.dir/external/sha3/avx2/KeccakP-1600-times4-SIMD256.c.o
ninja: build stopped: subcommand failed.

What is the supported Ubuntu version for liboqs?

Thanks,

/Kaiduan

**Comment by baentsch** [comment]
@kaiduanx Thanks for the complete report. To answer your question: We presently actively support/test Ubuntu 18.04. I think the issue you report is with the compiler version, though: Which gcc version do you have?

**Comment by kaiduanx** [comment]
~/open-quantum-safe/liboqs/build$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)

**Comment by dstebila** [comment]
We haven't tested on gcc-5 for a while now, and if memory serves it indeed has compilation errors that we decided not to resolve.  Kaiduan, can you try a more recent version of gcc?  We test with gcc-7 and gcc-8.

**Comment by kaiduanx** [comment]
I upgraded my Ubuntu to 18.04, the problem is gone. Thanks @dstebila and @baentsch
