### ISSUE TITLE
When CPU_EXTENSIONS becomes supported in cross-compilation, update cross-compilation instructions to use it

### ISSUE THREAD

**Issue by kevinmkane** [open-quantum-safe/liboqs#775]
CPU_EXTENSIONS currently causes a CMake error when configuring for cross-compilation. If and when it becomes capable of being used in cross-compilation, two sets of instructions need to be updated to remove the `-DOQS_USE_CPU_EXTENSIONS=OFF` directive currently present:

1. In liboqs's README.md, undoing where it was added in #772.
2. In OQS-OpenSSL's [cross-compilation wiki](https://github.com/open-quantum-safe/openssl/wiki/Cross-compiling-for-Windows-on-Linux).

**Comment by dstebila** [comment]
@jschanck Do you think #942 brings us any closer to this one?

**Comment by jschanck** [comment]
@dstebila Not quite. But Michael and I discussed some changes (https://github.com/open-quantum-safe/liboqs/discussions/943, specifically OQS_TARGET_ARCH) that would allow one to target a particular microarchitecture during cross-compilation. I'll do a mock-up of that idea soon.
