### ISSUE TITLE
Generating private key, public key and signature 

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/liboqs#778]
Hello, This is a question, not an issue. I want to use liboqs to just print/return private key, public key and signature. I have been trying to print the keys but I am pretty sure I am doing it wrong. I have very little experience with c. 

Thank you.

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <oqs/oqs.h>

#define MESSAGE_LEN 50

	OQS_SIG *sig = NULL;
	uint8_t *public_key = NULL;
	uint8_t *secret_key = NULL;
	uint8_t *message = NULL;
	uint8_t *signature = NULL;

int main() {
  /* code */
  public_key = malloc(sig->length_public_key);
  secret_key = malloc(sig->length_secret_key);
  message = malloc(message_len);
  signature = malloc(sig->length_signature);

  
  sig = OQS_SIG_new(OQS_SIG_alg_dilithium_2);

  public_key(sig->public_key);
  secret_key(sig->secret_key);

  return 0;
}

**Comment by baentsch** [comment]
@prchander Please have a look [at this](https://github.com/open-quantum-safe/liboqs/blob/master/tests/example_sig.c) for a full example how to use the APIs.

**Comment by baentsch** [comment]
@prchander Without further feedback I suppose we can close this issue for now.
