### ISSUE TITLE
OSX build warnings

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#779]
When I just built on OSX for the first time in a long time, these warnings appeared - and they're also in CCI...
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_portable.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_mul.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_portable.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_mul.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_portable.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_mul.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_portable.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_mul.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(cpu.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_portable.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_mul.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_portable.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_mul.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_portable.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_mul.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_portable.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(gf2x_mul.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/liboqs.a(cpu.c.o) has no symbols
```
--> Possibly some `cmake` magic required?

**Comment by drucker-nir** [comment]
Hi,

1) The file `liboqs/src/kem/bike/CMakeLists.txt` tells cmake to always compile the files `gf2x_mul.c` and `gf2x_portable.c`
2) On [CMakeLists.txt#L21](https://github.com/open-quantum-safe/liboqs/blob/master/src/kem/bike/CMakeLists.txt#L21) the compilation sets the `PORTABLE` flag for `Darwin` systems
3) The gf2x_mul.c is considered empty when `USE_OPENSSL_GF2M` is defined
4) The gf2x_portable.c is considered empty when `USE_OPENSSL_GF2M` is defined or when the `PORTABLE` macro is unset. From (2) we get that `PORTABLE` is set and thus `USE_OPENSSL_GF2M` must also be set. 
5) The `USE_OPENSSL_GF2M` flag is set in the default build of OpenSSL.

- To solve the issue, the compilation should not compile the `gf2x_mul.c` and `gf2x_portable.c` files when OpenSSL is used and the `USE_OPENSSL_GF2M` is enabled in the OpenSSL headers.

**Comment by baentsch** [comment]
@drucker-nir Thanks for the assessment and suggestion.

Do I get you right that these 2 files _should_ be compiled not only if OpenSSL is _not_ used but also if OpenSSL is used _and_ `USE_OPENSSL_GF2M`is *not* set (i.e., the OpenSSL define `OPENSSL_NO_EC2M` *is set* as per [this](https://github.com/open-quantum-safe/liboqs/blob/7f7bbaf59e9bc1847c7ffc9efe298409a0b71ea2/src/kem/bike/additional/openssl_utils.h#L15))? That'd be a bit more tricky and I'd suggest waiting with this for the return of our "CMake guru" @xvzcf -- as that would necessitate making an OpenSSL define visible as a CMake variable (to make compilation conditional on that)... 
But then again, having looked through the OpenSSL source code I did not find any location which sets `OPENSSL_NO_EC2M` (which would be a prerequisite for any OpenSSL distribution/include to show it as set, if I'm not mistaken).... 

Based on this, would you agree there's no real problem simply disabling compilation of these two files if OpenSSL is used?

**Comment by drucker-nir** [comment]
Yes, you are right.

The reason we added this code in the first place is that BoringSSL sets the `OPENSSL_NO_EC2M` flag. The reason is that it does not support binary curves. Thus, in your suggestion the compilation should check whether they use OpenSSL, BoringSSL, LibreSSL etc.  I am not familiar with other libraries that may be used by LibOQS and if they set this flag or not.

**Comment by baentsch** [comment]
OK - that then solved this part. Unfortunately, our CI system just taught me that there _is_ (at least) one distro setting the define `OPENSSL_NO_EC2M` also for OpenSSL (Centos8). Also, there's a similar "compile-to-empty" file (`cpu.c`) in picnic. So I'll do a draft PR asking for input from @xvzcf (regarding define-dependent build in cmake) and @christianpaquin (regarding picnic).

**Comment by xvzcf** [comment]
Closed by https://github.com/open-quantum-safe/liboqs/pull/782
