### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/liboqs#795]
Following github's move to change the default branch name to `main`, I propose we rename our `master` branch to `main`.

Should be seamless: https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

We could keep the `master` branch around for one release to allow dependent projects to switch over.

**Comment by dstebila** [comment]
Fine with me. Let's do it after the 0.4.0 release. Actually doing it for liboqs won't be a PR, it'll just be me running the magic git commands. But downstream consumers will need PRs, and there will also be wiki documentation update.
