### ISSUE TITLE
Add optimizations enabled to test_kem and test_sig

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#802]
The test harnesses test\_kem and test\_sig should output which version of an algorithm's implementation is running.  This may require adding an "optimizations" field to the OQS\_KEM and OQS\_SIG objects.

**Comment by baentsch** [comment]
The same would make sense for `speed_kem` and `speed_sig`. How would you want to identify/label the algorithm version/optimizations? Would it truly be necessary to add an "optimizations" field to OQS_KEM/SIG? Wouldn't a global cmake build options + /proc/cpuinfo output be sufficient (in combination with already available `Git commit` info)? Would also come handy for ´speed´ JSON output...
