### ISSUE TITLE
Add tests for invalid ciphertexts to liboqs

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#813]
Rather than leaving them to fail in wrappers

**Comment by christianpaquin** [comment]
Isn't [this](https://github.com/open-quantum-safe/liboqs/blob/master/tests/test_kem.c#L116) already doing this?

**Comment by dstebila** [comment]
I missed that, I guess so, yes.  But we are still getting a 'wrong ciphertext' related failure in liboqs-go. https://travis-ci.com/github/open-quantum-safe/liboqs-go/jobs/375154216#L6234

**Comment by christianpaquin** [comment]
> I missed that, I guess so, yes. But we are still getting a 'wrong ciphertext' related failure in liboqs-go. https://travis-ci.com/github/open-quantum-safe/liboqs-go/jobs/375154216#L6234

Maybe our approach isn't complete. Once we figure out what is wrong with the go error we can improve our test.

**Comment by dstebila** [comment]
@vsoftco From your recent look at liboqs-go, do you have any ideas on what additional type of test beyond what we have now would be appropriate here in liboqs to detect that previous wrong ciphertext bug?

**Comment by vsoftco** [comment]
@dstebila will take a look and get back to you

**Comment by dstebila** [comment]
Discussed in today's status meeting.  Conclusion is that it's something to do with how Go manages the stack, and that the tests in liboqs are sufficient.
