### ISSUE TITLE
How CVE against liboqs will be managed ?

### ISSUE THREAD

**Issue by jhfeng** [open-quantum-safe/liboqs#824]
I know this CVE question is little bit early. But since we plan to use this liboqs, I'd like learn any thoughts from OQS develop team on what procedure or mechanism will be used to track and manage CVE if there is any CVE be found later.

**Comment by jhfeng** [comment]
@dstebila   ^^ Any thoughts ?

**Comment by dstebila** [comment]
Having some internal discussions about it.  Can you email me so we can discuss as well?
