### ISSUE TITLE
Take stock of common code

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#849]
Determine which common code is actually being used by (which) QSC algorithms and which common code may be missing (incremental SHA? Additional OpenSSL wrappers to be added?)

Goal: Have a "fall-back" code base for environments where OpenSSL is not available. In general, though, rely on OpenSSL for performance and reliability of implementation as default "common crypto" provider (possibly make such statement in README somewhere?)

**Comment by baentsch** [comment]
Looks like this issue is the last hold-up for releasing 0.5.0. Merging #873 will not close this as that PR's script is only giving an indication as to which algorithms use which common code. If I recollect our conversations right we discussed also the "inverse" (to also check which additional common code would be good to add to liboqs). For that we'd need to review each algorithm implementation for "common code additions" -- or alternatively ask algorithm providers what they're missing in terms of common code (analogous to [this discussion](https://github.com/open-quantum-safe/liboqs/pull/883#issuecomment-770879536)): Is my recollection and options to close correct? Additional thoughts?

**Comment by christianpaquin** [comment]
Do we want to wait for this for 0.5? I'm fine to deal with this in the next release?

**Comment by baentsch** [comment]
Considering resolved as per discussion in #873
