### ISSUE TITLE
Unintended cmake build logic resulting from misspellings of OQS_PORTABLE_BUILD

### ISSUE THREAD

**Issue by ljoy913** [open-quantum-safe/liboqs#859]
In:
liboqs/src/common/CMakeLists.txt
liboqs/src/kem/bike/CMakeLists.txt

There are three total instances of **OQS_PORTABLE_BUILD** being spelled as **OQS_BUILD_PORTABLE**

**OQS_PORTABLE_BUILD** is defined and is ON, by default.
**OQS_BUILD_PORTABLE** is not defined anywhere and is, by default, OFF

The build logic that mistakenly uses **OQS_BUILD_PORTABLE** is building as a non-portable build in all cases.

Fixing these instances, results in the tests failing to link as the sha3/sha3x4.c sha-3 implementation would no longer be the default on portable builds.

**Comment by dstebila** [comment]
Fixed by #864.
