### ISSUE TITLE
Weird Kyber behaviour when -DOQS_USE_CPU_EXTENSIONS=ON

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#860]
This as a heads-up for the following behaviour I can reproduce in curl/nginx but not in liboqs testing:
Using curl&nginx "main" built-docker images, executing any Kyber KEM OpenSSL app interaction between curl and nginx results in a TLS decryption error, if the underlying liboqs for the apps was built with `-DOQS_USE_CPU_EXTENSIONS=ON`. This does not happen with this option set `OFF` during build. It also does not happen with other algorithms. I don't understand/can't reproduce this as in liboqs (KEM KAT) tests pass with either option set.
In case this "rings a bell" to anyone, please let me know. I'll otherwise keep digging along the software & build stack....

**Comment by jschanck** [comment]
Does this affect all Kyber parameter sets?

**Comment by baentsch** [comment]
It does, rather did: I found the problem: A combination of missing build parameters in the OQS-curl docker image and a pull from "master" instead of the new "main" branch. This triggered use of Kyber round2 vs round3 code in different images. Sorry, my mistake. Fixes will come in an upcoming PR in `oqs-demos`.
