### ISSUE TITLE
Integrate latest frodokem commits (up to 6a82d4)

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/liboqs#862]
Integrate latest frodokem commits, up to [6a82d4,](https://github.com/Microsoft/PQCrypto-LWEKE/commit/6a82d4d2b6bc32eeac3ad4f9c178c48072b506b3) [(diff)](https://github.com/microsoft/PQCrypto-LWEKE/compare/d5bbd0...6a82d4).

**Comment by dstebila** [comment]
FrodoKEM is up to date; the referenced commit didn't change the actual FrodoKEM code, just changed the test harness within the Microsoft repository.  I checked that the previous commits had been included.

I pushed https://github.com/open-quantum-safe/liboqs/commit/689f789d51815a7a98e270549ad455eca148a925 to update the algorithm datasheet to refer to the most recent commit in the MS repo.
