### ISSUE TITLE
not compiling with visual studio

### ISSUE THREAD

**Issue by Dan-J-D** [open-quantum-safe/liboqs#876]
2 errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C4146	unary minus operator applied to unsigned type, result still unsigned	CppUI	C:\Users\danie\source\repos\CppUI\CppUI\oqs\sig\dilithium\pqclean_dilithium4_clean\packing.c	264	
and
Severity	Code	Description	Project	File	Line	Suppression State
Error	C4146	unary minus operator applied to unsigned type, result still unsigned	CppUI	C:\Users\danie\source\repos\CppUI\CppUI\oqs\sig\dilithium\pqclean_dilithium4_clean\sign.c	61

**Comment by baentsch** [comment]
Thanks for your error report. Unfortunately, this is a bit too short to let us meaningfully comment on it (compiler version, options, ?). Also, this code exists identically in the upstream repos it actually originates with/is maintained in, e.g., [in PQCrystals](
https://github.com/pq-crystals/dilithium/blob/497a98bc7efe48cb0d18fd20d6d9a4b5629406ef/ref/packing.c#L264), so I'm afraid we can't really do something about it other than say that we know this code builds on Windows (see AppVeyor testing [here](https://ci.appveyor.com/project/dstebila/liboqs)).

**Comment by christianpaquin** [comment]
To complement @baentsch's comment, we now use cmake to build on Windows (we used to have VS projects), as documented [here](https://github.com/open-quantum-safe/liboqs#windows). See the appveyor [build script](https://github.com/open-quantum-safe/liboqs/blob/main/appveyor_build.bat) for details. If this doesn't work for you, please provide more details on your build process. Thanks.

**Comment by Dan-J-D** [comment]
Fixed: Visual studio doesnt like making unsigned ints negative so casting the var to int then back fixes it.

**Comment by baentsch** [comment]
I would invite @Dan-J-D to report this upstream ([here](https://github.com/pq-crystals/dilithium) or [here](https://github.com/PQClean/PQClean) ), so it's getting fixed for everyone.
