### ISSUE TITLE
Rainbow V crashes on Windows

### ISSUE THREAD

**Issue by vsoftco** [open-quantum-safe/liboqs#879]
Crashes on all language wrappers (c++/go/python), e.g. https://ci.appveyor.com/project/vsoftco/liboqs-python Most likely another stack issue...

**Comment by christianpaquin** [comment]
Rainbow 3/5 were not supported on Windows. The test was disabling them on windows (see [here](https://github.com/open-quantum-safe/liboqs-python/blob/main/tests/test_sig.py#L8)), but the rainbow names changed so we need to update the test guard.

**Comment by christianpaquin** [comment]
Fixed on liboqs-python commit [eef9c6](https://github.com/open-quantum-safe/liboqs-python/commit/eef9c6ec663e7642f17d7a59fc9c8ec657903a10).
