### ISSUE TITLE
Contributing guide update

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#884]
This is to foster a discussion on updates to [Contributing wiki](https://github.com/open-quantum-safe/liboqs/wiki/Contributing-guide)

> The code must build on Linux, macOS, and Windows.

This is not true for all algorithms, right? Suggested rephrase:

> The code must build at least on Linux (x86_64). Optimizations and other operating systems supported may be supported and must be suitably registered for each algorithm in https://github.com/open-quantum-safe/liboqs/blob/main/.CMake/alg_support.cmake

Also this statement isn't quite correct for all algorithms: 

> Source code must be formatted in accordance with our formatting requirements (make prettyprint).

Issues: a) We're not using `make` any more and b) this only applies to OQS core code, not the actual algorithms. So I suggest to introduce a new section "Common code" and move the above statement there changed as follows:

> Source code contributed to OQS core code must be formatted in accordance with our formatting requirements. Non-OQS core code is any code not originally created in this repository but only imported manually or automatically, such as specific quantum-safe algorithms. Adherence to our formatting requirements is successfully tested by executing `./tests/run_astyle.sh` in the liboqs project root folder without "Formatting" statements returned. Passing this test is a prerequisite for successful CI.

The `Automated inclusion` section needs to be re-written once #883 is landed.

Regarding [Testing](https://github.com/open-quantum-safe/liboqs/wiki/Contributing-guide#testing):

What about changing that heading to "Continuous Integration Testing (CI)" ?

Issues: We are not testing Centos 7 any more, so we need to drop the statement. 

Regarding Ubuntu: Would it be time to upgrade to a more recent LTS than 18.04? Canonical main stream is 20.04. -> I'd suggest to agree a time frame for this update.

Do we further want to posit

> Normal pull requests (PRs) must have all CI tests pass. Non-standard PRs must explain the reasons for breaking CI as well as a plan how to get CI to work again.

If so, we further face the issue that only core team members can actually trigger full CI. So should the further demand passing all CI tests locally be explicitly stated? Not really sure what to recommend here, so leaving a recommendation away at this time.

Next steps: Please comment below with changes, additions, etc. so we can agree in a next meeting how to close out this issue.

**Comment by christianpaquin** [comment]
These changes look good to me.

**Comment by dstebila** [comment]
All good suggestions, thanks for checking on this.  

Re: CI: The fact that only core team can trigger CI is a bit annoying.  According to the [CircleCI documentation](https://circleci.com/docs/2.0/private-images/), they've got an agreement with Docker to pull without rate limits for now, but make no promises for the future.  We could revert back to unauthenticated Docker pulls in our CircleCI config for now, and then if their agreement stops we can re-enable authentication.

**Comment by baentsch** [comment]
> We could revert back to unauthenticated Docker pulls in our CircleCI config for now

I'd also think this eases cooperation: See #885

**Comment by baentsch** [comment]
Mostly implemented. Will close when new code import wording is available (after #883 is merged).

**Comment by baentsch** [comment]
Closing this issue as first cut at such wording is now available after #883 merged: https://github.com/open-quantum-safe/liboqs/wiki/Contributing-guide#automated-inclusion Further explanation/documentation, e.g., to aid using this for #882 and/or #887, of course would be welcome -- tagging @bhess as last action on this issue).
