### ISSUE TITLE
liboqs split key pair 

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/liboqs#886]
Hello, this is just a question. With liboqs python, I was able to generate both the public and private key with the following script 	 
        algorithm = oqs.Signature(algorithm)
	public_key = algorithm.generate_keypair()
	private_key = algorithm.export_secret_key()
How would I be able to do this in C++? I have been able to generate the private key but confused about the public key.

**Comment by dstebila** [comment]
Are you using liboqs directly or the [liboqs-cpp](https://github.com/open-quantum-safe/liboqs-cpp) wrapper for C++?

If you are using liboqs directly, the [`OQS_SIG_keypair` function](https://openquantumsafe.org/liboqs/api/sig#sig_8h_1ac5c527513c5c353ba90a1a9ee386458e) generates the public key and private key simultaneously.

**Comment by dstebila** [comment]
Closing, please make future questions on the discussions board rather than as an issue.
