### ISSUE TITLE
Expert review needed for Picnic constant time warning

### ISSUE THREAD

**Issue by jschanck** [open-quantum-safe/liboqs#889]
In picnic3_simulate.c.i a return code is set by branching on the output of "timingsafe_bcmp".
```c
  if (timingsafe_bcmp(output, pubKey, params->output_size) != 0) {
    ret = -1;
  }
  return ret;
```
The name "timingsafe_bcmp" suggests to me that `ret` should be set using a constant time arithmetic expression instead, but I'd appreciate a review from someone familiar with the Picnic code.

**Comment by dstebila** [comment]
Tagging @bhess and @christianpaquin

**Comment by christianpaquin** [comment]
I forwarded this to the picnic devs; waiting for review.

**Comment by sebastinas** [comment]
This compare does not need to be constant time as it does not leak bits of the secret key. The if is there as a safeguard to ensure we do not break signing when working on the code and for debugging (see https://github.com/IAIK/Picnic/blob/master/picnic3_simulate.c.i#L44). I'll add a comment and some TIMECOP annotations for this part of the to make this clear.
