### ISSUE TITLE
McBits performance

### ISSUE THREAD

**Issue by sebastianv89** [open-quantum-safe/liboqs#89]
I've been told that the reported speed of the McBits implementation in liboqs is significantly slower than reported by the author.  I'll try to find out what is going on and see if I can fix it. I'll keep track of my findings in this issue thread.

**Comment by dstebila** [comment]
Yes, Tanja approached me about it at Real World Crypto, so it would be great if we can fix that.  Thanks for offering.

**Comment by sebastianv89** [comment]
Just got an email from Tung Chou (the developer). He said the numbers reported in the Crystals slides actually look reasonable, so I don't think there's a reason for us to change anything.
