### ISSUE TITLE
OQS_kex_alice_priv_free should not require a OQS_KEX pointer

### ISSUE THREAD

**Issue by jjl** [open-quantum-safe/liboqs#90]
None of the algorithms appear to actually use this and it made it slightly irritating to wrap in C++.

My suggestion would be simply to drop this parameter, which would make the API marginally simpler to understand

**Comment by dstebila** [comment]
Good suggestion. I want to simplify the KEX API even more and will include this in the plans.

**Comment by dstebila** [comment]
Will be done as part of #91.
