### ISSUE TITLE
Portability tests on ubuntu-focal CI

### ISSUE THREAD

**Issue by bhess** [open-quantum-safe/liboqs#901]
Portability tests are skipped on the new ubuntu-focal CI, for example here:

https://app.circleci.com/pipelines/github/open-quantum-safe/liboqs/1218/workflows/50fa1837-6443-4ad6-aac7-fa8fe6d1716f/jobs/12325/parallel-runs/0/steps/0-104

The likely cause is

https://github.com/open-quantum-safe/liboqs/blob/1ead54fc9adb441b017d296ec5c01b1cb30dbbfe/tests/test_portability.py#L27

With python3 on Focal, the string "Ubuntu" is reported with `platform.version()` rather than `platform.platform()`

**Comment by baentsch** [comment]
Good catch. Thanks!
