### ISSUE TITLE
Simplify KEX API

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#91]
I was talking with Dan Bernstein at Real World Crypto, and he had some suggestions about our KEX API, some of which carry forward into the design of a signature API.

Some of his comments (my wording) were:

1. the API should not require malloc's (in other words, callers pass in byte arrays of appropriate size, rather than the callee allocating it)
2. make the API as close to Supercop / NIST as possible to make it easier for people to submit
3. having the OQS_KEX or OQS_SIGN data structure is an extra hurdle for people wanting to submit
4. avoid passing the OQS_KEX or OQS_SIGN data structures down multiple levels of the stack
5. every input should be byte strings (i.e., don't use void * for private keys)
6. don't pass a random number generator down, instead rely on a global random number generator function like random_bytes
7. don't have functions representing "families of schemes" parameterized by different values, instead have each function correspond to one scheme

My opinions:

1. okay
2. okay
3. I would like to have the OQS_KEX or OQS_SIGN data structure for a few reasons: still maintaining a generic high level API that is parameterized by the scheme, and to include metadata such as key sizes and security levels
4. okay
5. For ephemeral/passive key exchange where the private key is only used once, I think void * is okay, but for schemes with long-term keys, each scheme would have to provide an explicit serialization/deserialization that the caller has to make use of; so I think for signatures byte strings is simpler (and matches Supercop / NIST)
6. It's not clear to me how to do transforms based on determinism for KEMs if you don't pass an RNG down. But then again it's also not clear to me how to do such transforms even if you do pass an RNG down. Thoughts?
7. Probably would simplify the API.

**Comment by dstebila** [comment]
See also #90

**Comment by jjl** [comment]
Largely agree with all of this, but mostly for different reasons. I've started wrapping oqs in a c++ api and most of these things made it more difficult than it could have been. The existing API as it stands is not the easiest (at least from c++) to integrate with other crypto (e.g. HMAC). Making everything byte strings would be a good start.

The two major problems I see are:
- we currently don't have a way to easily tell what the size of the buffer we need to allocate for a key or message is, so we'll need to construct one
- moving to a global RNG makes it difficult to fake input during testing and replay against an RNG state etc.

**Comment by jjl** [comment]
Oh and i think the named parameters string should go at the minimum - so far as i can tell it's only used for frodo and we only support one set of parameters for it anyway.

**Comment by jjl** [comment]
Hi @dstebila , how is progress coming with this?

I'm happy to do some of the work to speed things up if you've made a list of what you want out of the changes.

**Comment by dstebila** [comment]
A candidate new simplified KEM (previously KEX) API is present in a branch: https://github.com/open-quantum-safe/liboqs/blob/ds-nist-branch/src/kem/kem.h  

It incorporates many of these ideas.  Feedback welcome.

**Comment by dstebila** [comment]
Further to this new candidate simplified KEM API, I've created an example of how to use the API with statically allocated memory using individual algorithms' functions directly, and dynamically allocated memory using the generic OQS_KEM object: https://github.com/open-quantum-safe/liboqs/blob/ds-nist-branch/src/kem/example_kem.c.

**Comment by dstebila** [comment]
New KEM API is stable on nist-branch and underway on master-new-api branch, so closing this.
