### ISSUE TITLE
Update SPHINCS+ to R3 specification

### ISSUE THREAD

**Issue by thomwiggers** [open-quantum-safe/liboqs#937]
It flew under the radar for quite a while, but it's recently been pointed out to us that the parameters for SPHINCS+ had been updated back in september.

There's a PR in PQClean that will hopefully be merged soon (https://github.com/PQClean/PQClean/pull/377).  Once that's merged, it'll have to be updated here.

**Comment by dstebila** [comment]
We're planning to do a 0.5.0 release today, so I would bump this to a future release.

Does SPHINCS+ Round 3 have algorithm/KAT changes? If so it would cause a bump to 0.6.

**Comment by thomwiggers** [comment]
Yep, signature sizes are different.

**Comment by dstebila** [comment]
It's been merged into PQClean, so work can start on a liboqs PR.
