### ISSUE TITLE
compilation fails with 0.5.0 branch with error OPENSSL_NO_EC2M - not found

### ISSUE THREAD

**Issue by jhfeng** [open-quantum-safe/liboqs#952]
When build with 0.5.0 code on Ubuntu 18.04

```
mkdir: created directory 'build'
+ cd build
+ cmake -DCMAKE_BUILD_TYPE=Release -DOQS_BUILD_ONLY_LIB=ON -DOQS_PORTABLE_BUILD=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/usr/src/openssl/oqs ..
-- The C compiler identification is GNU 7.5.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "1.1.1", minimum required is "1.1.1") 
**-- Looking for OPENSSL_NO_EC2M
-- Looking for OPENSSL_NO_EC2M - not found
CMake Error at src/CMakeLists.txt:82 (target_link_options):
  Unknown CMake command "target_link_options".**


-- Configuring incomplete, errors occurred!
See also "/usr/src/liboqs/build/CMakeFiles/CMakeOutput.log".
See also "/usr/src/liboqs/build/CMakeFiles/CMakeError.log".
```

BUT, the compilation works with `main` branch code.

**Comment by jschanck** [comment]
This is actually not about OPENSSL_NO_EC2M---it's that your CMake doesn't have target_link_options. You should be able to compile the 0.5.0 branch with CMake 3.13.5 or later. The main branch is no longer using target_link_options and can be compiled with CMake 3.5 or later.

**Comment by baentsch** [comment]
@jhfeng do you have a specific need for Ubuntu 18? CI moved to Ubuntu 20 and that also has a more current cmake. Nevertheless @jschanck's comment is right in that that dependency on a more current `cmake` is gone (for now) and that this has nothing to do with NO_EC2M. Suggest to close or rename the issue.

**Comment by jhfeng** [comment]
Thanks @jschanck @baentsch, I can close the issue. yes, I need run the bits on ubuntu 18 at this time. With change on target_link_options in next release. I'm fine with it.
