### ISSUE TITLE
SIGILL in SIDH code

### ISSUE THREAD

**Issue by thomwiggers** [open-quantum-safe/liboqs#961]
I'm having trouble reproducing this locally, but on Github Actions for `liboqs-rust` I'm getting SIGILL in SIDH consistently.

https://github.com/open-quantum-safe/liboqs-rust/runs/2276909119#step:12:62

```
test kem::SidhP434::test_encaps_decaps ... error: test failed, to rerun pass '-p oqs --lib'

Caused by:
  process didn't exit successfully: `/home/runner/work/liboqs-rust/liboqs-rust/target/debug/deps/oqs-c655d61dbe5addf1 --test-threads 1` (signal: 4, SIGILL: illegal instruction)
```

For debugging purposes, I already pulled out the support CPU flags on Github Actions:

```
 flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse 
sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 
pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti fsgsbase bmi1 
avx2 smep bmi2 erms invpcid xsaveopt md_clear
```

The difference with my local set of `flags`:

* My computer doesn't have `hypervisor`
* GHA don't have `{'ida', 'flush_l1d', 'tsc_adjust', 'hwp_epp', 'vpid', 'ibpb', 'bts', 'tm', 'xsaves', 'ssbd', 'acpi', 'dtes64', 'dts', 'vmx', 'hwp_notify', 'pts', 'stibp', 'x2apic', 'intel_pt', 'xsavec', 'tpr_shadow', 'xgetbv1', 'ept', 'hwp_act_window', 'rdseed', 'hwp', 'adx', 'tsc_deadline_timer', 'sdbg', 'smap', 'tm2', 'est', 'ibrs', 'arat', 'aperfmperf', 'pebs', 'dtherm', 'ept_ad', 'clflushopt', 'mpx', 'epb', 'pdcm', 'nonstop_tsc', 'monitor', 'cpuid_fault', 'xtpr', '3dnowprefetch', 'pln', 'art', 'arch_perfmon', 'vnmi', 'pbe', 'ds_cpl', 'flexpriority'}`

**Comment by jschanck** [comment]
It's adx. SIKE's CMakeLists assumes that "BMI2" implies presence of both `mulx` and `adox` instructions. But there are Nahalem processors, like that GitHub actions Ivy Bridge machine, with `mulx` but not `adox`.

**Comment by thomwiggers** [comment]
Great detective work 👏🏻
