### ISSUE TITLE
No documentation available to easily cross compile a library for Windows

### ISSUE THREAD

**Issue by zerjioang** [open-quantum-safe/liboqs#978]
I wanted to compile a liboqs library for windows using linux and I was unable to find a way to do it just following the documentation. We should have a section in readme specifying how to properly cross compile. For example

## Cross compiling LIBOQS from Ubuntu to Windows
To build a `.dll` file

```bash
sudo apt install cmake gcc gcc-mingw-w64 ninja-install
git clone https://github.com/open-quantum-safe/liboqs
cd liboqs
mkdir build && cd build
cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../.CMake/toolchain_windows-amd64.cmake -DOQS_DIST_BUILD=ON -DBUILD_SHARED_LIBS=ON ..
ninja
```

The result of ninja process, will generate a `bin/liboqs.dll` file on project root directory

**Comment by baentsch** [comment]
Isn't [this](https://github.com/open-quantum-safe/liboqs#cross-compilation) what you're suggesting?

**Comment by zerjioang** [comment]
@baentsch  yes, to add it to the readme as part of offical guidelines for newcomers

**Comment by baentsch** [comment]
@zerjioang Thanks for the suggestion. When I run your suggestion to build a DLL above, I encounter some issues:
- `ninja-install` doesn't seem to be an ubuntu-installable APT package; only `ninja-build` works for me
- After running `ninja`, I only seem to be getting a file `liboqs.dll.a` which subsequently cannot be executed on Windows.

--> Could you please update your description as to what needs to be done to arrive at a Windows-executable DLL? Would you want to do that as part of a PR to update [README.md](https://github.com/open-quantum-safe/liboqs/blob/main/README.md)? Are you using this DLL to handle https://github.com/open-quantum-safe/liboqs-python/issues/36 (i.e., are cross-building the Windows-DLL for the python wrapper and not build it on Windows natively)? May this explain the naming issue there?

**Comment by zerjioang** [comment]
@baentsch  Okey, I'll do a PR with changes for review & approval

FYI: I choose to try cross compilation first, because I already had setup the environment for compilation in my Ubuntu. That's the only reason, to try this way first. Because I can always rely on Windows, download msys2 and do the compilation process again to generate the DLL

**Comment by baentsch** [comment]
Thanks for the explanation (and in advance for the PR). Does the issue https://github.com/open-quantum-safe/liboqs-python/issues/36 also surface if you build "natively" on Windows?

**Comment by zerjioang** [comment]
@baentsch  I PR you. Sadly I cannot test in windows at the moment, so i cant give you an answer

**Comment by baentsch** [comment]
Closed with update to [Wiki](https://github.com/open-quantum-safe/liboqs/wiki/Platform-specific-notes-for-building-liboqs#cross-building-a-windows-dll). Thanks for the suggestion and text, @zerjioang !
