### ISSUE TITLE
Encaps/decaps errors for AVX2 implementation of HQC-192

### ISSUE THREAD

**Issue by jschanck** [open-quantum-safe/liboqs#990]
Here are some NIST DRBG seeds that reproduce the failure seen [here](https://app.circleci.com/pipelines/github/open-quantum-safe/liboqs/1456/workflows/8d44fca0-68bd-4837-8c28-06f5b146cc85/jobs/14096). 

I didn't run tests for very long, but I only observed failures in the AVX2 implementation of HQC-192. I did not see any failures in the reference implementation of HQC-192 or in any implementation of the other two parameter sets.

``` 
6518FFC7BD1151BB4DCD3B9D51E172F56EA0D885181D262BFB6CCDAAECDA6D6AE2A26C49CC58D9EDE2F9307EE9A2D177

73AE11F8F9B2FF972432A761867976DF73C8E0FEA9BDA8E66D96BDC50D830A0B7FE2BC1FB81638C4A7FA9786F0524697

8A197C0B41FBD8D63F3902396329877C2D43E5D685581E3C7FFE1281545AC7AE76DCFB351D8FF96CA2A59697CD0B8652
 
A4CB8C35B16DFA6D577D000C8EB6740F5069DEAD4788BB65ED645D04856E2376EF1518108D85ABC6B1C1F96E76DB50E3
```

**Comment by jschanck** [comment]
I've done some tests with the first seed above (6518...).

The original HQC-192 code (upstream from PQClean) passes the encaps/decaps test with -O3 and segfaults with -O0. PQClean fails the encaps/decaps test with both -O3 and -O0, but does not segfault. The O0 segfaults make debugging fun!

The KAT output between upstream and PQClean is identical. Since some configurations of upstream negotiate the correct key, this means that the bug is in decapsulation. Based on the changes I made to get the code into PQClean the bug is probably in reed_solomon.c

I'll self-assign and make a fix in PQClean once I figure it out.

**Comment by thomwiggers** [comment]
I'm also quickly getting failures in HQC-128 when I run multi-threaded tests. I'll try to get a seed.

**Comment by thomwiggers** [comment]
weirdly enough, when I have `NUM_THREADS 40` (https://gist.github.com/thomwiggers/c23e2c4e01971ccfd5496466b72a89c6) I immediately get decapsulation failed in HQC but when I run 40 parallel processes with `NUM_THREADS 1` it doesn't happen. Might be on my end then.
