### ISSUE TITLE
Cygwin support 

### ISSUE THREAD

**Issue by huaraz** [open-quantum-safe/liboqs#997]
Is it possible to add cygwin support ? I get asm compile errors e.g.

$ ninja
[18/1508] Building ASM object src/kem/...les/bike1_l1_fo.dir/additional/red.S.o
FAILED: src/kem/bike/CMakeFiles/bike1_l1_fo.dir/additional/red.S.o
/usr/bin/cc -DAVX2 -DFUNC_PREFIX=OQS_KEM_bike1_l1_fo -DLEVEL=1 -Iinclude -I/usr/include -fPIC -march=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -Wno-maybe-uninitialized -mavx2 -include /home/moelma/git/liboqs/src/kem/bike/functions_renaming.h -MD -MT src/kem/bike/CMakeFiles/bike1_l1_fo.dir/additional/red.S.o -MF src/kem/bike/CMakeFiles/bike1_l1_fo.dir/additional/red.S.o.d -o src/kem/bike/CMakeFiles/bike1_l1_fo.dir/additional/red.S.o -c ../src/kem/bike/additional/red.S
../src/kem/bike/additional/red.S: Assembler messages:
../src/kem/bike/additional/red.S:19: Error: unknown pseudo-op: .hidden' ../src/kem/bike/additional/red.S:21: Warning: .type pseudo-op used outside of .def/.endef: ignored. ../src/kem/bike/additional/red.S:21: Error: junk at end of line, first unrecognized character is O'
../src/kem/bike/additional/red.S:58: Warning: .size pseudo-op used outside of .def/.endef: ignored.
../src/kem/bike/additional/red.S:58: Error: junk at end of line, first unrecognized character is `O'
[19/1508] Building ASM object src/kem/.../bike1_l1_fo.dir/additional/gf_mul.S.o

I also saw the following:

FAILED: tests/kat_sig.exe
: && /usr/bin/cc -Wl,--enable-auto-import -Wl,--stack,16777216 tests/CMakeFiles/kat_sig.dir/kat_sig.c.o -o tests/kat_sig.exe -Wl,--out-implib,tests/libkat_sig.dll.a -Wl,--major-image-version,0,--minor-image-version,0 lib/liboqs.a -lm /usr/lib/libcrypto.dll.a && :
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3.c.o):xkcp_sha3.c:(.text$Keccak_Dispatch+0x47): undefined reference to KeccakP1600_Initialize' /usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3.c.o):xkcp_sha3.c:(.rdata$.refptr.KeccakP1600_ExtractBytes[.refptr.KeccakP1600_ExtractBytes]+0x0): undefined reference to KeccakP1600_ExtractBytes'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3.c.o):xkcp_sha3.c:(.rdata$.refptr.KeccakP1600_Permute_24rounds[.refptr.KeccakP1600_Permute_24rounds]+0x0): undefined reference to KeccakP1600_Permute_24rounds' /usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3.c.o):xkcp_sha3.c:(.rdata$.refptr.KeccakP1600_AddBytes[.refptr.KeccakP1600_AddBytes]+0x0): undefined reference to KeccakP1600_AddBytes'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3.c.o):xkcp_sha3.c:(.rdata$.refptr.KeccakP1600_AddByte[.refptr.KeccakP1600_AddByte]+0x0): undefined reference to KeccakP1600_AddByte' /usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3.c.o):xkcp_sha3.c:(.rdata$.refptr.KeccakP1600_Initialize[.refptr.KeccakP1600_Initialize]+0x0): undefined reference to KeccakP1600_Initialize'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3x4.c.o):xkcp_sha3x4.c:(.text$Keccak_X4_Dispatch+0x47): undefined reference to KeccakP1600times4_InitializeAll' /usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3x4.c.o):xkcp_sha3x4.c:(.rdata$.refptr.KeccakP1600times4_ExtractBytes[.refptr.KeccakP1600times4_ExtractBytes]+0x0): undefined reference to KeccakP1600times4_ExtractBytes'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3x4.c.o):xkcp_sha3x4.c:(.rdata$.refptr.KeccakP1600times4_PermuteAll_24rounds[.refptr.KeccakP1600times4_PermuteAll_24rounds]+0x0): undefined reference to KeccakP1600times4_PermuteAll_24rounds' /usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3x4.c.o):xkcp_sha3x4.c:(.rdata$.refptr.KeccakP1600times4_AddBytes[.refptr.KeccakP1600times4_AddBytes]+0x0): undefined reference to KeccakP1600times4_AddBytes'
/usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3x4.c.o):xkcp_sha3x4.c:(.rdata$.refptr.KeccakP1600times4_AddByte[.refptr.KeccakP1600times4_AddByte]+0x0): undefined reference to KeccakP1600times4_AddByte' /usr/lib/gcc/x86_64-pc-cygwin/10/../../../../x86_64-pc-cygwin/bin/ld: lib/liboqs.a(xkcp_sha3x4.c.o):xkcp_sha3x4.c:(.rdata$.refptr.KeccakP1600times4_InitializeAll[.refptr.KeccakP1600times4_InitializeAll]+0x0): undefined reference to KeccakP1600times4_InitializeAll'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Thank you
Markus

**Comment by baentsch** [comment]
Thanks for this report. It [seems](https://github.com/open-quantum-safe/liboqs/blob/1b25f45f352122d4e4c00bddac4ec5f5b649dd2b/.CMake/alg_support.cmake#L30-L31), BIKE is not supported on Win32 platforms and the compile shouldn't be attempted to begin with. Tagging @jschanck @xvzcf for possible further information. Until then, you may want to try building turning BIKE explicitly off in the (cyg)win build, e.g., starting the build with `cmake -GNinja -DOQS_ENABLE_KEM_BIKE=OFF ..`

**Comment by baentsch** [comment]
Here's the (expected) lib build result on Linux

```
nm lib/liboqs.a | grep KeccakP1600times4_InitializeAll
0000000000000000 T KeccakP1600times4_InitializeAll
                 U KeccakP1600times4_InitializeAll
```

and from the (pretty slow) Win VM wrt to one specific Keccak symbol:
```
nm lib/liboqs.a | grep KeccakP1600times4_InitializeAll
0000000000000000 r .rdata$.refptr.KeccakP1600times4_InitializeAll
0000000000000000 R .refptr.KeccakP1600times4_InitializeAll
                 U KeccakP1600times4_InitializeAll

```
I have the hunch (or hope :) @jschanck may have an idea why this (and all Keccak) symbols "fail to materialize" in `liboqs.a` under cygwin.

**Comment by christianpaquin** [comment]
> @huaraz As you may see from the above, cygwin support for all algorithms may not be straightforward/require "digging" into various algorithm's code. Can I ask why you wouldn't want to/cannot use the ["standard" Windows build procedure](https://github.com/open-quantum-safe/liboqs#windows), i.e., using [MSVC](https://visualstudio.microsoft.com)?

Or use the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10); that's what I've been running for my OQS dev for years.

**Comment by huaraz** [comment]
> > @huaraz As you may see from the above, cygwin support for all algorithms may not be straightforward/require "digging" into various algorithm's code. Can I ask why you wouldn't want to/cannot use the ["standard" Windows build procedure](https://github.com/open-quantum-safe/liboqs#windows), i.e., using [MSVC](https://visualstudio.microsoft.com)?
> 
> Or use the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10); that's what I've been running for my OQS dev for years.

Thanks for looking into it.  I work mostly on Unix, but in the office I have only Windows and use cygwin for my "Unix" tasks/scripts. I'll check if I can compile native and use from my cygwin environment.

**Comment by baentsch** [comment]
Checking the status after #999 (thanks, @jschanck !), one further surprising complication: There's a decade-old [issue regarding psutil not working under cygwin](https://github.com/giampaolo/psutil/issues/82). --> Do we want to/can we replace `psutil` in testing? @xvzcf ?

**Comment by baentsch** [comment]
@huaraz All information above is now collected in [a wiki entry to build liboqs using cygwin](https://github.com/open-quantum-safe/liboqs/wiki/Platform-specific-notes-for-building-liboqs#using-cygwin). Please close this issue if OK for you or add further comments/feedback.

**Comment by huaraz** [comment]
That worked perfectly ! 

Thank you
Markus

**Comment by markus-moeller-db** [comment]
> > @huaraz ... Can I ask why you wouldn't want to/cannot use the ["standard" Windows build procedure](https://github.com/open-quantum-safe/liboqs#windows), i.e., using [MSVC](https://visualstudio.microsoft.com)?
> 

@christianpaquin  
I have now compiled liboqs using Visual Studio,  but openssh does not seem to be supported using MSVC or did I miss it ? 

Thank you
Markus

**Comment by huaraz** [comment]
> @huaraz ..... Can I ask why you wouldn't want to/cannot use the ["standard" Windows build procedure](https://github.com/open-quantum-safe/liboqs#windows), i.e., using [MSVC](https://visualstudio.microsoft.com)?
> 

@baentsch I was now also successful with MSVC, but that does not really help with openssh which can't be compiled under MSVC or did I miss it ? 

Thank you
Markus

**Comment by baentsch** [comment]
> @baentsch I was now also successful with MSVC, but that does not really help with openssh which can't be compiled under MSVC or did I miss it ?

Please pardon my grin: After suggesting to move this issue from [oqs-openssh](https://github.com/open-quantum-safe/openssh) here I'd now need to suggest you open this question there. Reason: I just don't know enough about openssh to answer this, but I'd be really surprised if this were impossible (quick [google search result](https://www.cs.bham.ac.uk/~smp/projects/ssh-windows/compile/)). Also tagging @xvzcf and @christianpaquin who might know more. 

In addition, if the cygwin build works for `liboqs` what about a cygwin build of openssh? That "feels" even more realistic given the API match between the packages.

**Comment by huaraz** [comment]
Yes I can now fully build oqs-openssh under cygwin.   I thought the 2 projects were closer linked i.e. when you mentioned MSVC I assumed it would work for both.

Thank you again
Markus

**Comment by baentsch** [comment]
Well, I guess the main reason that these are different projects is that many have upstreams and "inherit" their quirks (like which build environments are working). `liboqs` does not have an upstream, so _is_ different from all others (and we can improve things more easily. In that regard, thanks again for raising the cygwin issue here: With #1001 merging, now all PQ algorithms will work under windows -- _only_ if using Cygwin).
